### ISSUE TITLE
Ecolink Door Sensor action not detected on Node-RED

### ISSUE THREAD

**Issue by oguime** [OpenZWave/node-openzwave-shared#1]
The **Ecolink Door Sensor** is not detected on **Node-RED** (openzwave+node-openzwave-shared+node-red-contrib-openzwave) but **Openzwave Control Panel** shows it's working.

[Product manual](http://www.zwaveproducts.com/layout/manuals/Ecolink-DWZWAVE2-ECO_manual_rev1.pdf)

[OZW_Log.txt](https://gist.github.com/oguime/97044608f10e05d71fa5)

**Comment by ekarak** [comment]
Received this mail from Gilson:

Hi Elias,

The sensor was showing as Probe (Sleeping) on ozwcp so I pressed a button nearby the led and the status then became Awake.

A few hours latter it started appearing also on Node-RED. Seems to be working fine now.

Thanks,
Gilson

**Comment by oguime** [comment]
Hi Elias,
Today I had to reset Node-RED and after that the Ecolink Door Sensor would not show again. I reset my Z-Stick and added just the door sensor, waited for the process to complete and pressed tthe button closed to the LED. It worked again, but as soon as I reset Node-RED (by restarting the Raspberry PI) it went to Probe1 (Sleeping) state again (I turned to the ozwcp again to check):

![image](https://cloud.githubusercontent.com/assets/5217023/7800621/9897cad2-02ee-11e5-9ac9-d4722a5f1b7a.png)

Seems unlikely that it should be required to include the sensor everytime Node-RED is restarted...

[OZW_Log.txt](https://gist.github.com/oguime/153357b642e1ebfaeab5) shows that Z-Wave noticed the door sensor being triggered at the end.

Can you help?

Thanks,
Gilson

**Comment by ekarak** [comment]
Hey Gilson, 
I've added [some more command classes in the startup process to have polling automatically enabled] 
(https://github.com/OpenZWave/node-red-contrib-openzwave/blob/master/10-zwave.js#L203). I suspect that polling was disabled for your device and that a proper association group was not being set.
Can you please upgrade to 1.1.0 and retry?

**Comment by oguime** [comment]
Hi Elias,

Will do as soon as I get home.

Is a npm update enough?

Should I also update Openzwave itself and node-red-contrib-openzwave as
well?

Thanks,
Gilson

**Comment by ekarak** [comment]
Only openzwave-shared needs updating.

Στις 6 Οκτωβρίου 2015 4:27:16 μ.μ. EEST, ο/η Gilson <notifications@github.com> έγραψε:
>Hi Elias,
>
>Will do as soon as I get home.
>
>Is a npm update enough?
>
>Should I also update Openzwave itself and node-red-contrib-openzwave as
>well?
>
>Thanks,
>Gilson
>On Oct 6, 2015 4:21 AM, "Elias Karakoulakis" <notifications@github.com>
>wrote:
>
>> Hey Gilson,
>> I've added some more command classes in the startup process to have
>> polling automatically enabled
>>
><https://github.com/OpenZWave/node-red-contrib-openzwave/blob/master/10-zwave.js#L203>.
>> I suspect that polling was disabled for your device and that a proper
>> association group was not being set.
>> Can you please upgrade to 1.1.0 and retry?
>>
>> —
>> Reply to this email directly or view it on GitHub
>>
><https://github.com/OpenZWave/node-openzwave-shared/issues/1#issuecomment-145766162>
>> .
>>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/OpenZWave/node-openzwave-shared/issues/1#issuecomment-145855712

-- 
Sent from my mobile device with K-9 Mail. Please excuse my brevity.
