### ISSUE TITLE
Error: libopenzwave.so.1.4: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by polarathene** [OpenZWave/node-openzwave-shared#100]
```
[nodemon] starting `node index.js`
module.js:568
    return process.dlopen(module, path._makeLong(filename));
                            ^
Error: libopenzwave.so.1.4: cannot open shared object file: No such file or directory
```

I am trying to get this running in a Docker container. I downloaded the the latest git archive via [the link on this repo's ReadMe](https://github.com/OpenZWave/open-zwave/archive/master.zip), and then have the following in my Dockerfile:

```
# Initial prerequisites
USER        root
ENV         DEBIAN_FRONTEND noninteractive
RUN         apt-get -y update && apt-get -y install \
                libudev-dev

# Install OpenZWave
USER        root
COPY        open-zwave-master $HOME/src/open-zwave/
WORKDIR     $HOME/src/open-zwave/
RUN         make && make install
```

I sourced this snippet from an [open-zwave python docker container](https://github.com/OpenZWave/docker-openzwave/blob/master/Dockerfile). It builds fine but when building it mentions: `Building OpenZWave Version 1.4.-1`

I searched node_modules but didn't see any direct version reference hard coded in. Any idea why `node-openzwave-shared` is looking for `1.4` and not allowing `1.4-1`? How could I go about fixing this besides installing an earlier release(as this may become a problem in future?).

**EDIT:** Just tried the [snapshots] as well as an earlier `1.4` folder I had from before, but they all seemed to state they were building `1.4-1` as well :| I might be doing something wrong with Docker.

**Comment by polarathene** [comment]
I added an ENV `ENV         LD_LIBRARY_PATH /usr/local/lib64` to my Dockerfile based on [similar closed issue solution](https://github.com/OpenZWave/node-openzwave-shared/issues/98#issuecomment-223970867). I got the path by running:  `ld -lopenzwave --verbose` which listed the following:

```
attempt to open //usr/x86_64-linux-gnu/lib64/libopenzwave.so failed
attempt to open //usr/x86_64-linux-gnu/lib64/libopenzwave.a failed
attempt to open //usr/local/lib/x86_64-linux-gnu/libopenzwave.so failed
attempt to open //usr/local/lib/x86_64-linux-gnu/libopenzwave.a failed
attempt to open //usr/local/lib64/libopenzwave.so succeeded
```

Seems like it was able to find it, the ENV was empty when I echoed it, adding the path seems to work, and now I have this issue:

```
[nodemon] starting `node index.js`
module.js:568
    return process.dlopen(module, path._makeLong(filename));
                            ^
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/local/lib64/libopenzwave.so.1.4)
```

I run this in my docker container to see what versions I have: `strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX`
```
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_DEBUG_MESSAGE_LENGTH
```
`ls -l  /usr/lib/x86_64-linux-gnu/libstdc++.so.6`
`lrwxrwxrwx 1 root root 19 Dec 25  2014 /usr/lib/x86_64-linux-gnu/libstdc++.so.6 -> libstdc++.so.6.0.20`

So a slightly outdated version. I've learnt this is due to Debian Jessie `g++` package being `4.9.2-10`, listed [here on packages.debian.org](https://packages.debian.org/jessie/g++). Verified with `g++ -dumpversion` and `g++ --version`.

I've been looking into how to upgrade the GCC package to 5+ but not had much luck, some are using an ubuntu ppa which required quite a few packages to be added to use, I ended up with `Failed to fetch http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/dists/jessie/main/binary-amd64/Packages  404  Not Found` during my attempt. Debian Stretch would fix this but I'm building off the official NodeJS docker image, which I'd have to give up.

Closing as this appears to be distro specific.

**Comment by ekarak** [comment]
I've got some prebuilt packages for OpenZWave on ARM / Raspbian 7.10 (compiled alongside with my 3733t r00tk1ts, har har) in https://github.com/ekarak/openzwave-debs-raspbian - please do try these and tell me if they work on Jessie.

**Comment by polarathene** [comment]
@ekarak Won't that be an issue since I'm not using ARM but x86? From what I understand OpenZWave is using some C++ feature that requires the newer glibc/libc6 not available on Jessie? Or is there another compilation step somewhere to avoid this? Compiling the git repo worked fine, it was just when trying to use it with this node package.

Giving an Alpine linux image a go today, had an issue with `-printf` in `find` from a python call this node package did, fixed that but adding the `findutils` package. Current issue now is `Dynamic module loading not supported` hopefully can solve that :)

**Comment by polarathene** [comment]
@ekarak I got this working with Alpine. The dynamic module loading issue was due to nodejs being statically compiled, I also needed to add `eudev` package as `udev` was not supported,  worked seamlessly as a replacement.

On an Ubuntu docker image for openHAB which I was using to try out their ZWave binding, I had another issue with Ubuntu using a gid of `10` instead of `14` for the group `uucp`. The group for /dev/ttyACM0 appeared as `unknown`. That is only going to be an issue with VMs and Containers I guess, incase anyone else runs into the issue, you just need to add this group to your user to be able to access the zwave controller, I created a new group and assigned it like so in my Dockerfile:

```
USER root
RUN groupadd --gid 14 uucp-gid14
RUN usermod -aG uucp-gid14 openhab
USER openhab
```

You could also reassign the groupname a different gid `groupmod -g 14 uucp`, but you'd need to add the groupname to the user afterwards as it and all files previously using `uucp` with gid of 10 will still reference that by gid 10.

Not sure if a docker example would be useful to you in the project, especially since it's a bit difficult to deal with issues like gid and what the device address is. I could perhaps contribute one if you're interested.
