### ISSUE TITLE
Crashes Node-Red

### ISSUE THREAD

**Issue by erikvg01** [OpenZWave/node-openzwave-shared#102]
Hello.  When OpenZwave receives anything from a zwave device, it is crashing node-red.

Complete relevant log:

24 Jun 14:44:54 - [red] Uncaught Exception:
24 Jun 14:44:54 - TypeError: Cannot read property 'comclass' of undefined
at EventEmitter.nodeEvent (/home/pi/.node-red/node_modules/node-red-contrib-openzwave/10-zwave.js:216:24)
at EventEmitter.emit (events.js:106:17)
at addonModule.Emitter.emit (/home/pi/.node-red/node_modules/openzwave-shared/lib/openzwave-shared.js:39:5)
Initialising OpenZWave 1.4.0 binary addon for Node.JS.
OpenZWave Security API is ENABLED
ZWave device db    : /usr/local/etc/openzwave/
User settings path : /home/pi/.node-red/node_modules/openzwave-shared/build/Release/../../
Option Overrides : --Logging false --ConsoleOutput false --QueueLogLevel 6
nodered.service: main process exited, code=exited, status=1/FAILURE
Unit nodered.service entered failed state.
nodered.service holdoff time over, scheduling restart.
Stopping Node-RED graphical event wiring tool....
Starting Node-RED graphical event wiring tool....

**Comment by ekarak** [comment]
this is related to OpenZWave/node-red-contrib-openzwave#25

Apparently [the NodeEvent notification isn't passing a ZWave ValueID](https://github.com/OpenZWave/open-zwave/blob/master/cpp/src/command_classes/Basic.cpp#L227) - I think this event never worked :)

Going to fix this in a jiffy

**Comment by ekarak** [comment]
I've published 1.1.7 of the NodeRed plugin, this should resolve this issue.
