### ISSUE TITLE
rest api to control zwave network

### ISSUE THREAD

**Issue by Vebryn** [OpenZWave/node-openzwave-shared#105]
Hello,

I was wondering if there is a project that implements node-openzwave-shared to expose a rest api to control our home automation ?

My search reveals full home automation interfaces (OpenHAB, OpenRemote, Jeedom, etc.).

Best regards.

**Comment by carpaij** [comment]
@Vebryn,

I´m working on my own home automation application in angular.js which uses node-openzwave-shared as a REST API that enables you to do basic zwave API commands:

- setValue
- setNodeLocation
- setNodeName
- hardReset
- softReset
- beginControllerCommand
- cancelControllerCommand

Will this be sufficient for your use case? This is still early work in progress, but I can split this Zwave API and create a seperate git repo for it.

**Comment by Vebryn** [comment]
Hi,

I'm looking for a lightweight REST API. I'm currently using a pseudo-rest api based on express framework. My development skills are limited. Your solution is interesting. I will be happy to test and contribute to your angular api.

**Comment by carpaij** [comment]
@Vebryn: Unfortunately I haven't had the time yet to finish the API, but on second thoughts a REST API won't be the best solution for the zwave protocol as you won't receive any instant updates from the zwave network. 

A better solution would be an API using websockets, but that might be harder for you to integrate with.

Any how what does your current pseudo-rest api look like? It might already be very similar to what I have in mind. Would be bad if I simply create what you already made yourself, right?

**Comment by ekarak** [comment]
REST is not a panacea, nor is this support forum a place to discuss another project :)
the problem with REST is that it doesn't support  asynchronous events by default, and one needs to use an additional layer like WebSockets to get status feedback (or start polling....)

Resolving this
