### ISSUE TITLE
setNodeOn missing

### ISSUE THREAD

**Issue by goliatone** [OpenZWave/node-openzwave-shared#11]
After installing the library on a raspberry pi, if I open a `repl` I get the following error trying to use `setNodeOn`:

```
zwave-repl> zwave.setNodeOn(3)
TypeError: Object [object Object] has no method 'setNodeOn'
    at repl:1:8
    at REPLServer.self.eval (repl.js:112:21)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.EventEmitter.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
    at Interface._line (readline.js:531:8)
    at Interface._ttyWrite (readline.js:760:14)
    at ReadStream.onkeypress (readline.js:99:10)
    at ReadStream.EventEmitter.emit (events.js:98:17)
    at emitKey (readline.js:1095:12)
```

**Comment by ekarak** [comment]
Apologies :) this call (setNodeOn) is probably left over from a previous
version. Will fix this asap.
Στις 9 Αυγ 2015 5:26 μ.μ., ο χρήστης "goliatone" <notifications@github.com>
έγραψε:

**Comment by goliatone** [comment]
@ekarak perfect, thank you

**Comment by AviFix** [comment]
Hi,

I'm following the README-api.md doc.

the connection works fine' but "setNodeOn" or any other action resolves with an error that it's not a function.

how do i turn a switch on?

Thanks a lot
Avi

**Comment by ekarak** [comment]
Terribly sorry for the inconvenience! please try the following:

*zwave.setValue(3, 37, 1, 0, true); // node 3: turn on (the hard way)
zwave.setValue(3, 37, 1, 0, false); // node 3: turn off (the hard way)*


2015-08-13 13:18 GMT+03:00 AviFix <notifications@github.com>:

> Hi,
>
> I'm following the README-api.md doc.
>
> the connection works fine' but "setNodeOn" or any other action resolves
> with an error that it's not a function.
>
> how do i turn a switch on?
>
> Thanks a lot
> Avi
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenZWave/node-openzwave-shared/issues/11#issuecomment-130603715>
> .
>



-- 
Elias Karakoulakis
Electrical & Computer Engineer NTUA Athens
Msc Information Systems, AUEB Athens
KNX Advanced Partner

**Comment by AviFix** [comment]
Hi,

Thanks for your replay.

that dosn't work to.

this is my code:

```
 var OpenZWave = require('openzwave-shared');

var zwave = new OpenZWave('/dev/ttyACM0', {
    saveconfig: true
});
var nodes = [];

zwave.on('connected', function(homeid) {
    console.log('=================== CONNECTED! ====================');

});
zwave.connect();
zwave.setValue(5, 37, 1, 0, true);

```
Can you please tell me what is wrong?

Thanks a lot
Avi

**Comment by ekarak** [comment]
connect() takes some time, so any commands you issue while the library
initialises will get lost.
You need to issue the 'setValue'  command *after* you're received a
'initialisation complete' message from the ZWave library.

2015-08-13 14:28 GMT+03:00 AviFix <notifications@github.com>:

> Hi,
>
> Thanks for your replay.
>
> that dosn't work to.
>
> this is my code:
>
>  var OpenZWave = require('openzwave-shared');
>
> var zwave = new OpenZWave('/dev/ttyACM0', {
>     saveconfig: true
> });
> var nodes = [];
>
> zwave.on('connected', function(homeid) {
>     console.log('=================== CONNECTED! ====================');
>
> });
> zwave.connect();
> zwave.setValue(5, 37, 1, 0, true);
>
>
> Can you please tell me what is wrong?
>
> Thanks a lot
> Avi
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenZWave/node-openzwave-shared/issues/11#issuecomment-130629075>
> .
>



-- 
Elias Karakoulakis
Electrical & Computer Engineer NTUA Athens
Msc Information Systems, AUEB Athens
KNX Advanced Partner

**Comment by AviFix** [comment]
do you happen to have a basic working sample?

**Comment by goliatone** [comment]
@AviFix 

```js
 var OpenZWave = require('openzwave-shared');

var zwave = new OpenZWave('/dev/ttyACM0', {
    saveconfig: true
});
var nodes = [];

zwave.on('connected', function(homeid) {
    console.log('=================== CONNECTED! ====================');
    zwave.setValue(5, 37, 1, 0, true);
});
zwave.connect();
```

**Comment by AviFix** [comment]
Thank you for the example.

when runing it i get the folowing error:

```
=================== CONNECTED! ====================
/home/avi/openZwave/test3.js:10
    zwave.setValue(5, 37, 1, 0, true);
          ^
TypeError: Illegal invocation
    at null.<anonymous> (/home/avi/openZwave/test3.js:10:11)
    at emit (events.js:104:17)
    at ZWave.connect (/usr/lib/node_modules/openzwave-shared/lib/openzwave-shared.js:78:13)
    at Object.<anonymous> (/home/avi/openZwave/test3.js:12:7)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
```

Any ideas?

**Comment by ekarak** [comment]
I've added the missing setNodeOn/Off methods, so the docs and the code are now aligned.
As a rough guide. just copy-paste the example script in a node.js REPL and after OZW finishes initialisation you can start sending commands over the air. BTW are you using anything other than Node.JS?
Closing this issue (version 1.0.3 released in NPM)
