### ISSUE TITLE
the function removeNode() .

### ISSUE THREAD

**Issue by spatchola** [OpenZWave/node-openzwave-shared#110]
when i execute removeNode()  and i press the button on the device , the device is removed but this function doesn't return anything , and  i want a notification to tell me it is done ?   what can i do ?

**Comment by japita-se** [comment]
Yes you are right. There is any update on this?

**Comment by ekarak** [comment]
there's already a 'node removed' event, which I see I forgot to include in the documentation. Please register an event handler as follows:
```
zwave.on('node removed', function(nodeid){...})
```
