### ISSUE TITLE
Issue while using Aeotec Z-Stick Gen5

### ISSUE THREAD

**Issue by matteodisabatino** [OpenZWave/node-openzwave-shared#112]
Hello, I'm using this module since 6 months, I've developed several codes and all work very great.
Recently I've bought a new dongle: Aeotec Z-Stick Gen5 (sorry but I don't remember the previous one, I haven't with me at the moment), but with this new dongle nothing works although my codes are exactly the same.
It seems the module is correctly instanced but when I try to use the method setValue I receive this message: `TypeError: setValue: OpenZWave valueId not found`

Where could the problem be?

**Comment by ekarak** [comment]
Resolving this call: 
this is clearly not an issue with the Node.JS library, see
https://groups.google.com/forum/#!topic/openzwave/4nOiY27pn_s
Please raise this with

**Comment by ekarak** [comment]
https://github.com/OpenZWave/open-zwave/issues/485
