### ISSUE TITLE
Install on Window fails

### ISSUE THREAD

**Issue by jonaswikstrom** [OpenZWave/node-openzwave-shared#114]
Hello

Installed node-openzwave-shared successfully on Linux but his time I have to install it on a Windows 10 machine. I have the newest release of Node. This is the error:

![capture](https://cloud.githubusercontent.com/assets/16499417/18157470/113a8068-701e-11e6-8002-9988acfb2f20.PNG)

Any clue what this error is?

**Comment by ekarak** [comment]
No, no clue whatdoever. I've not used Windows for development for many many years. 
By the looks of it this looks as if npm is holding a file open in that temporary directory, and Windows is very unlike Unix on that it doesn't allow drastic actions on a directory with open files. Sorry.

**Comment by jonaswikstrom** [comment]
Alright so let me get this straight?
You don't have the competence and knowledge and then directly close the case. Is it by laziness?! 

Why don't you spare peoples time by removing the text "Since there is no standard installation location for Open Z-Wave on Windows, it will be automatically downloaded, compiled, and installed when you install this module." if you guys can't stand for it.
