### ISSUE TITLE
Node Hangs After 2nd Scan

### ISSUE THREAD

**Issue by japita-se** [OpenZWave/node-openzwave-shared#115]
I send an MQTT message from outside in order to start a scan of the network and publish back the results.
I am doin it inside a Raspberry.
Here the code.

```
var ZWave = require('openzwave-shared');
var os    = require('os');
var zwave = new ZWave({
        ConsoleOutput:false
    });
 var zwavedriverpaths = {
        "darwin" : '/dev/cu.usbmodem1411',
        "linux"  : '/dev/ttyAMA0',
        "windows": '\\\\.\\COM3'
    }
const mqtt = require('mqtt');
client = mqtt.connect(url,options); // url and options not shown
zwave.on('scan complete', function() {
        console.log('====> scan complete, hit ^C to finish.');
        zwave.disconnect();          
    });


client.on('message', function(topic, message, packet){
                zwave.connect( zwavedriverpaths[os.platform()] ); // asynchronus call. Handled by events.

});
```

From web, I publish the message to start the scan. The first scan is OK. If I resend a message, node jumps to 100%CPU usage and the event loop is blocked.
Why? I am using the node implementation for Raspbian.

**Comment by japita-se** [comment]
It seems that the node version on my Rasp was faulty. Uninstalled and re-installed again. It seems now to work.

**Comment by ekarak** [comment]
oh wait - you're connecting on every message. This is not right.

**Comment by ekarak** [comment]
You shouldn't use OpenZWave by connecting and disconnecting - that doesn't make sense! 
This issue tracker deals not with usage questions, you should use the [OpenZWave users mailing list](https://groups.google.com/forum/#!forum/openzwave) instead.

**Comment by japita-se** [comment]
Ok, sorry and thank you!
