### ISSUE TITLE
Ma

### ISSUE THREAD

**Issue by japita-se** [OpenZWave/node-openzwave-shared#116]
I did:
1) connect()
2) addNode -> pressed 3 times the zwave device button -> node included
3) disconnect()
4) connect():
I was supposed to have the nodes structure.
I have it (I can see two node records), but for some strange reason the manufacturer details are not shown. I mean, they are empty.
Why

**Comment by ekarak** [comment]
are the manufacturer details shown when the node is first included?

**Comment by ekarak** [comment]
This issue tracker deals not with usage questions, you should use the [OpenZWave users mailing list](https://groups.google.com/forum/#!forum/openzwave) instead.
Your issue sounds as if OpenZWave cannot find the relevant device XML from disk. Is this a "known" device? First check if [the official device database](http://www.openzwave.com/device-database/) knows about your device, and if yes, check your OpenZWave installation for the device database (should be under /etc/openwave or /usr/local/etc/openzwave). 
You probably have a stale OpenZWave installation that needs an update.
