### ISSUE TITLE
How to detect if the dongle is unplugged?

### ISSUE THREAD

**Issue by matteodisabatino** [OpenZWave/node-openzwave-shared#117]
Hello all,
Image I'm running a node script that use this module and image that at a certain moment I decide to unplug the ZWave dongle. Is there a way to detect it? For example, is there an event (i.e. "disconnect") that is sent when dongle is unplugged?

**Comment by ekarak** [comment]
this is a hot debate in the OpenZWave developer forum, see https://github.com/OpenZWave/open-zwave/issues/111, but this is surely *not* an issue with the Node.JS API itself. Closing.

**Comment by matteodisabatino** [comment]
Thanks for your answer but I think it's not correct for my question, probably I wrote it in the wrong way, I try to write it better: is there an event that is emitted by the library when I unplug the dongle while the process is running?

**Comment by Fishwaldo** [comment]
No. As @ekarak pointed out, its tracked in that ticket he linked too.

**Comment by matteodisabatino** [comment]
Understood, thanks. Maybe I've not read the link properly, sorry.
