### ISSUE TITLE
save config to xml

### ISSUE THREAD

**Issue by yybd** [OpenZWave/node-openzwave-shared#118]
Is it possible to add a function to save the settings?

// =================================================================
	NAN_METHOD(OZW::WriteConfig)
	// =================================================================
	{
		Nan::HandleScope scope;	
		OpenZWave::Manager::Get()->WriteConfig(homeid)	
	}

**Comment by ekarak** [comment]
feel free to fork, add your changes and then do a pull request
thanks!

**Comment by japita-se** [comment]
any news on that?
