### ISSUE TITLE
Controller not working

### ISSUE THREAD

**Issue by goliatone** [OpenZWave/node-openzwave-shared#12]
I installed the [open zwave control panel][1] and its working perfect. 
The network has a switch and a door sensor. I can turn the switch on and off through the control panel, I also see the updated status of the door sensor. However, the test script I made was working yesterday but today seems non responsive.  `setValue` has no effect and I get no events when the door sensor changes states.
Any ideas?

[1]:https://github.com/OpenZWave/open-zwave-control-panel

**Comment by goliatone** [comment]
I know this in itself is not really helpful but I don't know how to describe it better than that. 
I connect the controller, if I `tail -f OZW_log.txt` log file I can see all the chatter happening, ie, every time I manually switch on/off a binary switch I can see the updates in the log.

**Comment by ekarak** [comment]
Hi, can you please try copying  the OpenZWave config XML that you've created with the OZWCP over to the file generated by OZW in your node app? (you could also initialise the openzwave-shared library by pointing it to the existing XML config)

**Comment by ekarak** [comment]
please try version 1.0.6 which I just released on npm.

**Comment by goliatone** [comment]
will do when i get some bandwidth, prob this weekend. Had to leave the node route and I moved onto the raw OpenZWave lib. Really looking forward for the node wrapper to really work! 
Thanks for all the work

**Comment by ekarak** [comment]
resolving, fixed in 1.0.6
