### ISSUE TITLE
zwave.getNeighbours() function is not working

### ISSUE THREAD

**Issue by kranthisai** [OpenZWave/node-openzwave-shared#120]
Hi, 
    I am getting the following error, when using getNeighbours(). Also, I couldn't find anything in the repo when I searched for getNeighbours(). 

```
console.log(zwave.getNeighbours());
                      ^
```

TypeError: undefined is not a function
    at EventEmitter.<anonymous> (/**_/openzwave-shared/test2.js:129:27)
    at EventEmitter.emit (events.js:118:17)
    at addonModule.Emitter.emit (/**_/openzwave-shared/lib/openzwave-shared.js:39:5)

**Comment by kmoughon** [comment]
This is a international issue... Check your spelling of the function. If you search the repo you will find 'getNeighbors', the US English spelling. I work at a company with offices in Scotland and Florida, we run into this issue all the time.

**Comment by ekarak** [comment]
```$ grep -ri neigh src/
src/openzwave.cc:	  Nan::SetPrototypeMethod(t, "requestNodeNeighborUpdate", 
src/openzwave.cc:		Nan::SetPrototypeMethod(t, "getNodeNeighbors", 
```

not an issue -resolving

**Comment by lobando** [comment]
Thanks,
Thanks,
When calling getNodeNeighbors we are getting 

```
*** Error in `node': free(): invalid pointer: 0x00007fffa9abcc00 ***
Aborted (core dumped)
```

are we doing something wrong?

**Comment by ekarak** [comment]
you're right! I'm deleting the neighbors array no matter if I don't have to.
Just a minute while I fix this...

**Comment by ekarak** [comment]
can you please checkout the latest master and retry?

**Comment by kranthisai** [comment]
Thanks, I retried. Got empty array this time. I want to create some routing table to understand which sensor is connected to which repeater. Is this the function right?

**Comment by ekarak** [comment]
Yes thats correct, but you need to do a requestNeighborUdate first. Will
confirm this once I get home

Στις 20 Σεπ 2016 7:35 μ.μ., ο χρήστης "Kranthi" <notifications@github.com>
έγραψε:

**Comment by kranthisai** [comment]
Thanks.. I tried requestNodeNeighborUpdate for all the nodeids, still getNodeneighbor function is returning empty array..

**Comment by magorski** [comment]
You sure that `getNeighbours ` method still exist in `node-openzwave-shared`? From What I see it's been removed in commit [2573b7f7c64](https://github.com/OpenZWave/node-openzwave-shared/commit/2573b7f7c642c17f09a4d7db14c01c08578c281e#diff-029cc5ebec5955c4f364155485889aa3L421). When I'm trying to run it Im getting `TypeError: zwave.getNeighbors is not a function` error.

I think it's been replaced by `getNodeNeighbors()` function but documentation never got updated (no mention of `getNodeNeighbors()` in docs).

BTW, looks like you need to run `requestNodeNeighborUpdate` (and wait some seconds/minutes?) before you use `getNodeNeighbors()` otherwise you getting empty array.

**Comment by kranthisai** [comment]
Thanks @magorski . I tried even today but it didn't worked for me. After requestNodeNeighborUpdate, my program sleeps for 5 minutes before executing getNodeNeighbors(). Got the following error today: *** Error in `node': double free or corruption (out): 0x00007ffd9388e9d0 ***Aborted (core dumped)

**Comment by ekarak** [comment]
Is this still an issue? Can you paste an example that replicates this?
BTW, `getNodeNeighbors()` requires a node id argument, are you sure you're passing a value?

**Comment by ekarak** [comment]
Just added a simple dump of the node neighbors in test.js and it seems to be working for me:
 
```
== Driver Statistics:
{"m_SOFCnt":15,"m_ACKWaiting":0,"m_readAborts":0,"m_badChecksum":0,"m_readCnt":15,"m_writeCnt":13,"m_CANCnt":0,"m_NAKCnt":0,"m_ACKCnt":13,"m_OOFCnt":0,"m_dropped":0,"m_retries":0,"m_callbacks":0,"m_badroutes":0}
== Node 1 neighbors: [2]
== Node 1 Statistics:
```

Resolving

**Comment by SlyAndrew** [comment]
getNodeNeighbors() does not exist. Doc must be updated.

**Comment by ekarak** [comment]
https://github.com/OpenZWave/node-openzwave-shared/blob/master/src/openzwave.cc#L139

**Comment by SlyAndrew** [comment]
@ekarak  sorry I meant getNeightbors() => it 's not defined.
https://github.com/OpenZWave/node-openzwave-shared/blob/master/README-api.md

**Comment by ekarak** [comment]
fixed the typo, thanks
