### ISSUE TITLE
Different behavior on different platforms

### ISSUE THREAD

**Issue by teifip** [OpenZWave/node-openzwave-shared#121]
I'm using `node-openzwave-shared` 1.2.0 with `open-zwave` 1.4.164. My controller is an Aetec Z-Stick Gen5 and I have a few Ecolink sensors.
When I run my code on a Mac, I can see `node available` events from all the nodes. Instead, when I run the code on a Raspberry Pi 3 with Raspbian Jessie, I don't get the `node available` events for the Ecolink sensors.

I've repeated this observation multiple times, and it is always consistent. Both on the Mac and on the Raspberry Pi 3 I've build the libraries starting from the .tar.zg file dowloaded from the OpenZWave repository.

Any idea of what can be the cause for the different behaviors on the two platforms? I would appreciate very much hints for what to look at.

**Comment by ekarak** [comment]
Is your openzwave config.xml the same?

Στις 18 Σεπ 2016 11:25 π.μ., ο χρήστης "teifip" <notifications@github.com>
έγραψε:

**Comment by teifip** [comment]
Thanks a lot for your kind/prompt support! I did not pay attention to the the network configuration caching mechanism. After I left everything running for 20-30 min on the Raspberry Pi, all the sensors became available. Now the cache has been built, and all the nodes show up promptly exactly like when I run the controller on the Mac.

By the way, the current definitions for Ecolink are as follows:

```
<Manufacturer id="014a" name="Ecolink">
          <Product type="0001" id="0001" name="Door/Window Sensor"/>
          <Product type="0001" id="0003" name="Garage Door Sensor"/>
</Manufacturer>
```

With the sensors I have, they should rather be like this:

```
<Manufacturer id="014a" name="Ecolink">
          <Product type="0001" id="0001" name="PIR Motion Sensor"/>
          <Product type="0001" id="0002" name="Door/Window Sensor"/>
          <Product type="0001" id="0003" name="Garage Door Sensor"/>
</Manufacturer>
```

Here is the [official vendor reference](http://www.discoverecolink.com/wp-content/uploads/Advanced-Zwave-Configuration-v2.pdf). Do you think I should report this on the `open-zwave` issues?
