### ISSUE TITLE
Other ZWAVE Commands

### ISSUE THREAD

**Issue by japita-se** [OpenZWave/node-openzwave-shared#122]
This library is a life-saver! Congratulations.
However, is there any way to add or implement additional zwave commands, like:
COMMAND_CLASS_POWERLEVEL
COMMAND_CLASS_SWITCH_ALL
COMMAND_CLASS_CONFIGURATION

Moreover, there is no mention how to use
zwave.requestAllConfigParams(nodeId);
zwave.requestConfigParam(nodeId, paramId);
zwave.setConfigParam(nodeId, paramId, paramValue, <sizeof paramValue>);

**Comment by ekarak** [comment]
Correct. As spare time is limited, please I urge you to feel free and drop in a PR with the missing features.
