### ISSUE TITLE
sceneGetValues returns current value, not scene value

### ISSUE THREAD

**Issue by RoboPhred** [OpenZWave/node-openzwave-shared#123]
sceneGetValues calls zwaveSceneValue2v8Value in utils.cc, which in turn gets its value from setValObj.  This makes it return the current values rather than the scene values.
It would be more reasonable for this to return values pulled from Scene::GetValue, which returns the value that the scene will set the value id to.

**Comment by ekarak** [comment]
PR? :)

**Comment by ekarak** [comment]
I'll submit a patch for this shortly

**Comment by ekarak** [comment]
Reporter, please checkout this branch: https://github.com/OpenZWave/node-openzwave-shared/tree/bugfix/%23123-get-scene-values 

and give me a shout if its working as intended.

**Comment by ekarak** [comment]
@RoboPhred ping
