### ISSUE TITLE
Node Information does not persist after restart

### ISSUE THREAD

**Issue by jodyalbritton** [OpenZWave/node-openzwave-shared#125]
Is this by design or have I misconfigured something? The basic node information does not persist after a restart. Devices must wake up an send this info back to the server or be woken manually. I have 
SaveConfiguration: true set as an option but after every restart the nodes have no info. 

  "nodeid": 24,
  "manufacturer": "",
  "manufacturerid": "",
  "product": "",
  "producttype": "",
  "productid": "",
  "type": "",
  "name": "",
  "loc": "",

**Comment by ekarak** [comment]
yes, you need to call `writeConfig()` to persist the NIF (node information frame) to disk. I need to update the docs, thank you for reminding me :)

**Comment by jodyalbritton** [comment]
I tried calling zwave.writeConfig() in several places and none seem to work. Do I need to specify the homeid or any params. Looking through the source code it's hard to get an idea of how the command works.

**Comment by Gielert** [comment]
Did you install the library from the master or the npm registry. Because iirc the zwave.writeConfig() function isn't pushed to npm yet.

**Comment by ekarak** [comment]
is this working for you guys? can you please report?

**Comment by Gielert** [comment]
For me, yes it does. On some weird occasional moments, the NIF will be mangled (But thats probably because I quit the process sometimes during scanning). But other than that it works.

**Comment by ekarak** [comment]
ok, resolving then.
