### ISSUE TITLE
COMMAND_CLASS_WAKE_UP

### ISSUE THREAD

**Issue by japita-se** [OpenZWave/node-openzwave-shared#126]
Is this command implemented?
I see only setConfigParam: but which class is supposed ?

**Comment by ekarak** [comment]
Please refrain from asking usage questions in a bugfix tracking system.
OpenZWave exposes *values* that can be altered. If your device exposes a COMMAND_CLASS_WAKE_UP value, then it will be exposed and you can control it.

**Comment by japita-se** [comment]
How? I see only this:
`zwave.setConfigParam(nodeId, paramId, paramValue, <sizeof paramValue>);`
The command class is not within the functions parameters...

**Comment by ptorrent** [comment]
Hello,

Same problem here, how do you solve this problem ?
