### ISSUE TITLE
setConfigParam for Fibaro not Work

### ISSUE THREAD

**Issue by japita-se** [OpenZWave/node-openzwave-shared#127]
I have a Fibaro Motion sensor (FGMS 001).
I tried to set a config param with
`setConfigParam(57,1,12,1).`
But nothing happens. With other devices, when I set a config param I receive a "value changed" event.

**Comment by ekarak** [comment]
Please enable debug logging and attach your logs.

**Comment by ekarak** [comment]
resolving.
