### ISSUE TITLE
requestAllConfigParams Crashes

### ISSUE THREAD

**Issue by Evaske** [OpenZWave/node-openzwave-shared#136]
Can't seem to get requestAllConfigParams to work or for any of the configuration params functions to do what they're supposed to.

Any idea what we can do with this?

zwave.requestAllConfigParams(nodeId);
zwave.requestConfigParam(nodeId, paramId);
zwave.setConfigParam(nodeId, paramId, paramValue, <sizeof paramValue>);

**Comment by ekarak** [comment]
please enable debugging in OpenZWave so that we can capture some output

**Comment by Evaske** [comment]
Managed to get it working. Might want to update the Readme somewhere on the use of getting/setting configs so it mentions the need for 'value change' etc.

**Comment by ekarak** [comment]
please provide a PR for the updated Readme :)

**Comment by ekarak** [comment]
resolving - I've also added a long-missing feature, that is a rudimentary arguments check
