### ISSUE TITLE
setValue too slow

### ISSUE THREAD

**Issue by japita-se** [OpenZWave/node-openzwave-shared#137]
I noticed that when the number of sensors increases (say 3) setValue becomes very slow. I mean the sensor reacts too slowly....
This issue has been tested on two different Raspberry.
Anyone had the same problem?

**Comment by ekarak** [comment]
This is not a nodeJS specific issue, and is probably not even an OpenZWave issue.
Please ask generic OpenZWave usage questions on the mailing list.
You should also provide logs from OZW that can help an experienced user explain that behaviour.
