### ISSUE TITLE
AutoAssociation

### ISSUE THREAD

**Issue by japita-se** [OpenZWave/node-openzwave-shared#142]
OZW sets autoassociation to true for included devices.

https://groups.google.com/forum/#!searchin/openzwave/associations%7Csort:relevance/openzwave/mXRCSZsvcnI/c2SJJnOJCAAJ

This should be a parameter  also with nodeJS.

**Comment by ekarak** [comment]
This should work as-is:

>                s_instance->AddOptionBool(              "Associate",                            true );                                         // Enable automatic association of the controller with group one of every device.

Have you tried setting this option in the constructor? It should appear in the "Option Overrides" printout as well.

```
var zwave = new OpenZWave({
	ConsoleOutput: false,
	Logging: false,
	Associate: false   ***********
});
```

**Comment by japita-se** [comment]
I will try, thank you.
