### ISSUE TITLE
Question on removeAssociations

### ISSUE THREAD

**Issue by japita-se** [OpenZWave/node-openzwave-shared#143]
I did not find any other place to ask this. So, I apologize if this is not the right place.
I tried `getAssociations()` for a given node, say 65.
After loopin on all the groupIds, I get this (formatted by me) result:
```
group_id    Associations to nodes
1	          64=>1,255	
2	          64=>	
3	          64=>1
```

This tells me that node 64 has 3 groups, and 2 associations to node 1 (the controller).
I suppose that 255 is the broadcast node, isnt'it?
Well, suppose that I want to remove associations to node 1. First question: is it possible?
I used r`emoveAssociation(64,1,1).`
If I redo `getAssosociations` nothing is changed, I get the same table as above.
Is it correct?

**Comment by ekarak** [comment]
you shouldn't remove associations with the controller, otherwise you won't be getting updates when the device status changes (eg by manual button press).
As far as I know, there is no "broadcast" node in ZWave.

**Comment by japita-se** [comment]
Thnk you ekarak. And what is that "255" ?

**Comment by ekarak** [comment]
I don't know. Please google it.
