### ISSUE TITLE
Problem on NPM install

### ISSUE THREAD

**Issue by mrjpsycho** [OpenZWave/node-openzwave-shared#144]
Hi,

I've just moved to a new install of Raspbian after my SD card died, and the latest version (v1.2.9 at the time of posting) is causing errors when I attempt to perform an `npm install`. I've installed the 3 ARM HF packages and can confirm the library, system, and other files are where I would expect them to be. However, during the install it appears that the `find` commands as part of `lib/ozwpaths.js` is failing due to `Permission Denied` output causing a 1 return code when searching for the `sysconfdir`. 

When running find locally I get: 
```
$ find /etc -name zwcfg.xsd
/etc/openzwave/zwcfg.xsd
find: `/etc/ssl/private': Permission denied
```

This causes the following stack trace during the install:
```
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
find: \`/etc/ssl/private': Permission denied
gyp: Call to 'node -e "console.log(require('./lib/ozwpaths.js').libdir)"' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: \`gyp\` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/pi/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.34-v7+
gyp ERR! command "/home/pi/.nvm/versions/node/v6.9.1/bin/node" "/home/pi/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/scripts/node_modules/openzwave-shared
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN zwave_test@0.0.0 No repository field.
npm ERR! Linux 4.4.34-v7+
npm ERR! argv "/home/pi/.nvm/versions/node/v6.9.1/bin/node" "/home/pi/.nvm/versions/node/v6.9.1/bin/npm" "install"
npm ERR! node v6.9.1
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE

npm ERR! openzwave-shared@1.2.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
```

I expect simply running find in some way to suppress these permission errors, or some slight change to the way these files are located would stop this occurring. But I am not sure which would be the least complex option.

**Comment by ekarak** [comment]
The find mechanism exists only for installations where the pkg-config file is missing. I tweaked it recently due to the fact that busybox-based distributions had trouble locating files (as they have a handicapped `find`, a soft link to busybox actually). 
On Raspbian (which is a real Debian), `pkg-config` should return the configuration items for OpenZWave.
Can you please check if `pkg-config  --exists libopenzwave` returns any results? If not installed, please do a `sudo apt-get install pkg-config` first. Thanks

**Comment by ekarak** [comment]
I've just pushed a small fix, that is to supress stderr from the `find` process:
```
    var cmdfmt = "find %s -name %s 2>/dev/null";
```

Can you please fetch the latest master and retry? Or did you have any luck with the pkg-config approach?

**Comment by mrjpsycho** [comment]
Hi, 

Thanks for the rapid response, and apologies for my late response.

Master works fine now with the suppressed errors. I'm yet to figure out why pkg-config can't find the library, but from an initial look, I think its a missing .pc file when installing from the package. More googling on that required.

Thanks for the fix to suppress the errors, as this works perfectly.
