### ISSUE TITLE
No such file `undefined` on NPM install

### ISSUE THREAD

**Issue by toastystarfish** [OpenZWave/node-openzwave-shared#145]
find: `undefined': No such file or directory
gyp: Call to 'find undefined -name ZWSecurity.h | wc -l' returned exit status 0. while trying to load binding.gyp

I was following this setup guide:
[README-raspbian](https://github.com/OpenZWave/node-openzwave-shared/blob/master/README-raspbian.md)

MinOZW runs just fine then get this error on npm install.

**Comment by ekarak** [comment]
can you please update to version 1.3.1 (just an `npm update openzwave-shared` will do) and share the results please?

**Comment by NewtonEhv** [comment]
Same Issues here:

npm WARN lifecycle openzwave-shared@1.3.1~preinstall: cannot run in wd %s %s (wd=%s) openzwave-shared@1.3.1 node lib/install-ozw.js /usr/lib/node_modules/.staging/openzwave-shared-96c2ab2f

> openzwave-shared@1.3.1 install /usr/lib/node_modules/openzwave-shared
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/7.5.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/openzwave-shared/.node-gyp"
find: `undefined': No such file or directory
gyp: Call to 'find undefined -name ZWSecurity.h | wc -l' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:308:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:192:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.38-v7+
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/openzwave-shared
gyp ERR! node -v v7.5.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
npm ERR! Linux 4.4.38-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "openzwave-shared"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! openzwave-shared@1.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the openzwave-shared@1.3.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the openzwave-shared package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs openzwave-shared
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls openzwave-shared
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/lib/node_modules/node-red/npm-debug.log

Using a Raspberry Pi3, did an apt update and upgrade.

**Comment by ekarak** [comment]
Now *this shouldn't happen.*, its as if the OZW_INC variable in binding.gyp isn't bound to a variable. The installation script cannot locate your OpenZWave install.
- How have you installed OpenZWave on your Pi?
- Could you please navigate to  /usr/lib/node_modules/openzwave-shared and run
`node -p "require('./lib/ozwpaths.js').includedir"` ? It should print out something like `/usr/local/include/openzwave`. Thanks

**Comment by NewtonEhv** [comment]
- OpenZwave is installed on in the directory /home/pi/open-zwave-read-only/ as described in https://www.domoticz.com/wiki/Installing_and_running_Domoticz_on_a_Raspberry_PI#Build_Support_for_OpenZWave.
- The directory /usr/lib/node_modules/openzwave-shared does not exist, I do have a directory /root/.npm/openzwave-shared/1.3.1. When runnin the command above i get
root@Appia:~/.npm/openzwave-shared# node -p "require('./lib/ozwpaths.js').includedir"
module.js:472
    throw err;
    ^

Error: Cannot find module './lib/ozwpaths.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at [eval]:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:23:33)
    at Object.exports.runInThisContext (vm.js:74:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:571:32)
    at Immediate.<anonymous> (bootstrap_node.js:383:29)

Am I messing-up install directories and/or users?

Thnx for support!

**Comment by ekarak** [comment]
OK, I see where the issue is, Domoticz is using a custom install prefix, and there's no way to pass this information over to the installation script.
Can you do a last check for me please, could you see if you got `pkg-config` installed on your system?

`sudo apt-get install pkg-config`

then try

`pkg-config --exists libopenzwave` 

and post back your results

**Comment by NewtonEhv** [comment]
Pkg-Config is present:
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
pkg-config is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
 and running _`pkg-config --exists`_ libopenzwave yields an empty return. 

Running `locate libeopenzwave` I get:

/home/pi/open-zwave-read-only/cpp/build/libopenzwave.pc.in
/home/pi/open-zwave-read-only/debian/libopenzwave1.3-dev.install
/home/pi/open-zwave-read-only/debian/libopenzwave1.3.install
/home/pi/open-zwave-read-only/debian/libopenzwave1.3.lintian-overrides
/home/pi/open-zwave-read-only/debian/libopenzwave-doc.doc-base
/home/pi/open-zwave-read-only/libopenzwave.a
/home/pi/open-zwave-read-only/libopenzwave.so
/home/pi/open-zwave-read-only/libopenzwave.so.1.4

In what location should openzwave be installed? I can't find a clear instruction. I do see that in this https://www.domoticz.com/wiki/Install.txt#OpenZWave version of the Domoticz install they do this: 
```
git clone https://github.com/OpenZWave/open-zwave.git
ln -s open-zwave-read-only open-zwave
```
So guess if I 'move' (or recompile) the openzwave files to the right directory voor node-openzwave-shared and create a symlink to it for Domocits, both should work. Right?

**Comment by ekarak** [comment]
ok so here's the current situation:

> running `pkg-config --exists libopenzwave` yields an empty return.

- openzwave is merely decompressed and compiled under the home folder by the Domoticz script
- This would be OK, if OpenZWave provided a valid libopenzwave.pc file to point to that home folder  but this doesn't happen as the Domoticz installation script for OZW does not invoke `sudo make install`
- BTW: the symlink for `open-zwave-read-only` is a relic from the days when the OpenZWave repo was hosted in google's subversion services. Probably kept for backward compatibility.

Can you please try `sudo make install` from within /home/pi/open-zwave-read-only/? 
This will copy over the include headers and the compiled library under /usr/local.

**Comment by NewtonEhv** [comment]
It did the trick!  Thnx for the help.

**Comment by ekarak** [comment]
closing issue, thanks
