### ISSUE TITLE
can't npm install

### ISSUE THREAD

**Issue by Lesani** [OpenZWave/node-openzwave-shared#146]
Hello!

I followed the "install" instructions of:
https://github.com/OpenZWave/node-openzwave-shared/blob/master/README-raspbian.md
I did both manually compile and install with dpkg, on both cases I cat the issue
MinOZW starts nicely

npm install openzwave-shared gives me:

[13:45:25] pi@openHABianPi:~/open-zwave$ npm install openzwave-shared

> openzwave-shared@1.3.0 preinstall /home/pi/open-zwave/node_modules/.staging/openzwave-shared-3af7da75
> node lib/install-ozw.js

> openzwave-shared@1.3.0 install /home/pi/open-zwave/node_modules/openzwave-shared
> node-gyp rebuild

/bin/sh: 1: pkg-config: not found
gyp: Call to 'node -e "console.log(require('./lib/ozwpaths.js').libdir)"' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:308:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-1-rpi2
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/open-zwave/node_modules/openzwave-shared
gyp ERR! node -v v6.9.4
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/open-zwave/package.json'
npm WARN open-zwave No description
npm WARN open-zwave No repository field.
npm WARN open-zwave No README data
npm WARN open-zwave No license field.
npm ERR! Linux 4.4.0-1-rpi2
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "openzwave-shared"
npm ERR! node v6.9.4
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

please advise

**Comment by ekarak** [comment]
can you please updating to latest master from github and then 'npm install .'  ?

**Comment by tjakie** [comment]
I got the same issue I am trying to install it on Ubuntu 16.04.1 LTS.
MinOZW works like a charm tried it on different versions. but with no luck.:(

[npm-debug.log.txt](https://github.com/OpenZWave/node-openzwave-shared/files/740097/npm-debug.log.txt)

Don't get exactly what you mean by: 
`can you please updating to latest master from github and then 'npm install .' ?`

I've downloaded the repo from zip and then tried npm install but then i got a error about the license.

Please help:)

**Comment by ekarak** [comment]
I've plublished a new version to npm. Please do `npm update`  to try it.

**Comment by tjakie** [comment]
you are AWESOME!!:)

**Comment by ekarak** [comment]
I suppose we can close this then :)
