### ISSUE TITLE
Node 4.0 install fails

### ISSUE THREAD

**Issue by Codelica** [OpenZWave/node-openzwave-shared#15]
Ok, so I didn't expect it to install yet, but it would have been nice. :)

Install of openzwave-shared@1.0.4 with Node 4.0 results in a variety of Nan and V8 errors during compile.  Probably not a surprise with all the changes to both at this point.  I tried bumping Nan up from 1.9 to the current 2.0.9 which just resulted in different errors.  I can include logs if it helps.

Hopefully node will be a little more stable now that things have been merged into 4.0.  For now I'll try going back to v0.12.

Thanks for making this! :+1:

**Comment by ekarak** [comment]
NodeJS is so unstable like the heavier elements in the periodic table; I need to put on my lead shield and start working again (sigh)...: btw: I have some Delphi code back from late 90's that is STILL running untouched :)

**Comment by ekarak** [comment]
OK, I've sort-of upgraded to the new NaN 2.0.9. Warning: This is one of the most ugly pieces of code I've written in years! 
```		OpenZWave::Options::Get()->AddOptionBool("ConsoleOutput",
			Nan::Get(opts, Nan::New<String>("consoleoutput").ToLocalChecked()).ToLocalChecked()->ToBoolean()->Value());```
**Strong suspicion that node.js is doomed.**
