### ISSUE TITLE
How to use dev branch of open-zwave?

### ISSUE THREAD

**Issue by AlCalzone** [OpenZWave/node-openzwave-shared#150]
I'm currently trying to use the dev branch of open-zwave in combination with this library and ioBroker to get my new WallMote to work. 
After a small [code change](https://github.com/OpenZWave/open-zwave/issues/1172) I managed to compile it on my Raspberry Pi 2. 
libopenzwave.so points to version 1.5 (checked with `ls -al`) but openzwave-shared still seems to use version 1.4

So, how can I use the freshly compiled version 1.5?

**Comment by ekarak** [comment]
- uninstall the old version of the library (1.4), incl. /usr/local/lib64/libopenzwave.so AND the headers under /usr/local/include/openzwave
- `sudo make install` the development branch of OpenZWave to compile and install it on your system
- `sudo ldconfig -r` to rebuild the linker cache

then try rebuilding this package: `node-gyp configure` and `node-gyp rebuild`

Let me know how this goes.

**Comment by AlCalzone** [comment]
Gonna try tonight and report back. As a linux noob, how do I do this part?

> uninstall the old version of the library (1.4), incl. /usr/local/lib64/libopenzwave.so AND the headers under /usr/local/include/openzwave

**Comment by AlCalzone** [comment]
Mevermind, I just deleted the files you mentioned, i guess that counts as "uninstalling".

Anyways, it seemed to work. The OZW_Log.txt now reads:
`2017-03-14 19:04:46.376 Always, OpenZwave Version 1.5.0 Starting Up`

**Comment by ekarak** [comment]
thanks, resolving
