### ISSUE TITLE
Calling createScene returns an error saying 'requires 2 parameters'

### ISSUE THREAD

**Issue by CenturionD** [OpenZWave/node-openzwave-shared#152]
[https://github.com/OpenZWave/node-openzwave-shared/blob/master/src/openzwave-scenes.cc#L31](https://github.com/OpenZWave/node-openzwave-shared/blob/master/src/openzwave-scenes.cc#L31)

In the file `openzwave-scene.cc`
`
NAN_METHOD(OZW::CreateScene)
{
       Nan::HandleScope scope;
	CheckMinArgs(2, "label");
        std::string label = (*String::Utf8Value(info[0]->ToString()));
        SceneInfo *scene;
`

The CheckMinArgs number should be 1, not 2.

Workaround for those who have this issue:

`zwave.createScene('example name', 'example name');`

**Comment by ekarak** [comment]
I've released version 1.3.3 with this fix, please update.
