### ISSUE TITLE
zwave.setvalue response 

### ISSUE THREAD

**Issue by pejko** [OpenZWave/node-openzwave-shared#155]
Hi i have this strange issue
I call in one of my functions something like this
`zwave.setValue({ node_id:data.nodeId, class_id: data.classId, instance:data.instance, index: data.index }, data.command);`  
where i send the needed variables when i call my function
this works fine only on first atempt, but when i call the function second time with different command  it just wont work. 
when i make two functions with 2 different commands and call them one after another than everything works fine.
Does the setValue have some response ? so i could see if my command was executed or if its hangs somewhere? Thank you and sorry for ma terrible english :)

**Comment by ekarak** [comment]
you can subscribe to 1) the zWave ValueID's 'value changed/refreshed' handler and 2) the 'node event' handler, you should be able to get notifications when something is happening.

**Comment by pejko** [comment]
the 'value changed/refreshed' sound just right, thank you ekrak for your time and this great add-on
