### ISSUE TITLE
Does this library need an update for central scene support?

### ISSUE THREAD

**Issue by AlCalzone** [OpenZWave/node-openzwave-shared#162]
I've been trying to get the central scene support to work on my Raspberry Pi 2. Openzwave has a pending pull request that includes this functionality into the Dev branch, but after applying that and compiling from source, I cannot get it to work.
See https://github.com/OpenZWave/open-zwave/issues/1171 and https://github.com/OpenZWave/open-zwave/pull/1125

I'm always getting the error `Cannot find endpoint map to instance for Command Class COMMAND_CLASS_CENTRAL_SCENE endpoint 0`. 

Could it be that this library needs support for CS aswell before I can use the new feature?

**Comment by AlCalzone** [comment]
I'd love to, but I have no clue about C++ and/or wrapping that in nodejs. Guess I'll have to wait a bit then.

**Comment by ekarak** [comment]
the pull requests are still open on the main repo, so we'll have to wait until the API is sstabilised....

**Comment by daviwil2** [comment]
Any news on this? OpenZWave PRs #993, #1124 and #1125 seem to have come to a close with a merge into the main branch, any news on when we'll see this enabled in node-openzwave-shared? Thanks!

**Comment by xGouley** [comment]
Need it too! :D

**Comment by lukescott** [comment]
As far as I can tell this is not on the master branch, but it is on the dev branch. Has anyone had any luck in getting this to work?

**Comment by AddoSolutions** [comment]
Same here, doesn't appear to work on the master branch.

**Comment by AddoSolutions** [comment]
Scratch that, so I cloned master of openzwave, then download/patched the files in the master branch as shown here: https://github.com/OpenZWave/open-zwave/pull/1125/files

From there, I re-built and installed that project and then rebuild this one, and on my HomeSeer WD-100+ I get:

```javascript
zwave.on('value changed', function(nodeid, comclass, value) {
    console.log(['value changed', nodeid, value.value]);
});
```

```json
[ 'value changed', 12, 'Pressed 2 Times' ]
[ 'value changed', 12, 1 ]
[ 'value changed', 12, 13 ]
```

So no modifications needed?

**Comment by AlCalzone** [comment]
I can confirm. Master branch + patch 1125 works. Although the command class seems to have no name (it appears as "CLASSES_91").
