### ISSUE TITLE
Broken NPM build on Raspian

### ISSUE THREAD

**Issue by vincemic** [OpenZWave/node-openzwave-shared#164]
The path to OpenZWave 'Manager.h' is no longer valid. I believe this was caused by a recent change to binding.gyp. I haven't been able to investigate further yet, but reverting to older version helps.

**Comment by ekarak** [comment]
thanks for this report, I'll try to look into this tomorrow.

**Comment by Tzyinc** [comment]
any updates? I'm also facing this issue. In the meantime, which version works?

**Comment by s0meone** [comment]
Can confirm this issue on Ubuntu 14.04 as well. Version 1.4.0 does not build, downgrading to 1.2.9 does work.

```
In file included from ../src/callbacks.cc:18:0:
../src/openzwave.hpp:29:21: fatal error: Manager.h: No such file or directory
 #include "Manager.h"
                     ^
compilation terminated.
```

Will try to investigate.

**Comment by s0meone** [comment]
Reverting commit 35f7b25fdb2da6ab475f4f67bc126d1d43fedb91 fixes the issue.

**Comment by s0meone** [comment]
[This](https://github.com/OpenZWave/node-openzwave-shared/commit/35f7b25fdb2da6ab475f4f67bc126d1d43fedb91#diff-21e418851ae48f9b11907837add9e39aR51) check is probably incomplete. See the following output in my test environment:

```
$ which nodejs
/usr/bin/nodejs

$ which node
/var/lib/jenkins/.nvm/versions/node/v5.3.0/bin/node

$ nodejs -v
v0.10.25

$ node -v
v5.3.0
```

After removing the old `nodejs` package from the system, everything works: `apt-get remove nodejs`.

Hope this helps anyone.

**Comment by ekarak** [comment]
@s0meone what's your distro?

**Comment by s0meone** [comment]
Ubuntu 14.04 LTS

**Comment by ekarak** [comment]
I guess I need to revert the priority of node vs nodejs and check if we're above 0.10.x...

**Comment by Zombitch** [comment]
Same probleme here, but removing nodejs doesn't help :( any other idea ?

**Comment by Haris07** [comment]
Hi I have the same issue while building on Raspbian. Can anybody help me how I can downgrade the version to make it work. 
I am following this link right now but no success. 
https://github.com/OpenZWave/node-openzwave-shared/blob/master/README-raspbian.md

**Comment by Zombitch** [comment]
After some investigations, my problem was due to Meteor and not directly to node-openzwave-shared. So my "solution" was to redesign my app as a NodeJS app instead of a Meteor App.

**Comment by Haris07** [comment]
@Zombitch : Can you help me in resolving my problem. I have this issue. 
![capture1](https://user-images.githubusercontent.com/4725634/28239201-405c05b0-69a1-11e7-95d8-2a94d5121ad8.PNG)

**Comment by nouknouk** [comment]
FYI: same error string here, but it was my mistake: i forgot to install the libopenzwave library before on my rpi.

Once the libopenzwave is well installed on the system, everything behaves well.

**Comment by zeronote** [comment]
As for @nouknouk , Manager.h is provided by libopenzwave-dev, so installing it solves the issue.

(rpi, 2017-09-07-raspbian-stretch)

**Comment by ekarak** [comment]
https://github.com/OpenZWave/node-openzwave-shared/pull/189 was merged moments ago and should fix Raspbian installation issues. Resolving.
