### ISSUE TITLE
Problem npm install on Travis-CI node 6+7

### ISSUE THREAD

**Issue by Apollon77** [OpenZWave/node-openzwave-shared#166]
We use your library in a project and soem some days we have the problem that on Travis-CI the npm install failes for node 6+7. node 4 everything works.

Do you have any idea?

Error is:

```
> openzwave-shared@1.3.4 preinstall /home/travis/build/ioBroker/ioBroker.zwave/node_modules/.staging/openzwave-shared-bf5cfb5d

> node lib/install-ozw.js

npm WARN prefer global jsonlint@1.6.2 should be installed with -g

npm WARN prefer global jshint@2.8.0 should be installed with -g

> openzwave-shared@1.3.4 install /home/travis/build/ioBroker/ioBroker.zwave/node_modules/openzwave-shared

> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR

not found: nodejs

gyp: Call to 'which nodejs || which node' returned exit status 0 while in binding.gyp. while trying to load binding.gyp

gyp ERR! configure error 

gyp ERR! stack Error: `gyp` failed with exit code: 1

gyp ERR! stack     at ChildProcess.onCpExit (/home/travis/.nvm/versions/node/v6.10.3/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)

gyp ERR! stack     at emitTwo (events.js:106:13)

gyp ERR! stack     at ChildProcess.emit (events.js:191:7)

gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

gyp ERR! System Linux 3.13.0-115-generic

gyp ERR! command "/home/travis/.nvm/versions/node/v6.10.3/bin/node" "/home/travis/.nvm/versions/node/v6.10.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"

gyp ERR! cwd /home/travis/build/ioBroker/ioBroker.zwave/node_modules/openzwave-shared

gyp ERR! node -v v6.10.3

gyp ERR! node-gyp -v v3.4.0

gyp ERR! not ok 
```

Details at all can be found here: https://travis-ci.org/ioBroker/ioBroker.zwave/jobs/229261908

**Comment by ekarak** [comment]
this `which nodejs||which node` check was specifically added to address an issue with Ubuntu's in that the default NodeJS package installs the main binary as `nodejs` instead of `node` (so as not to conflict with another AX.25 related amateur radio networking package). It could even be that the container is missing the `which` command. I'll take a look.

**Comment by ekarak** [comment]
Most worrying line in these logs is the following:```Starting with io.js 3 and Node.js 4, building native extensions requires C++11-compatible compiler, which seems unavailable on this VM. Please read https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements.```

**Comment by ekarak** [comment]
I just pulled a docker image for Precise and successfully compiled openzwave-shared

```
root@e4a9b80139d4:/# npm install openzwave-shared
npm WARN lifecycle openzwave-shared@1.3.4~preinstall: cannot run in wd %s %s (wd=%s) openzwave-shared@1.3.4 node lib/install-ozw.js /node_modules/.staging/openzwave-shared-582ae4e9

> openzwave-shared@1.3.4 install /node_modules/openzwave-shared
> node-gyp rebuild

make: Entering directory `/node_modules/openzwave-shared/build'
  CXX(target) Release/obj.target/openzwave_shared/src/callbacks.o
  CXX(target) Release/obj.target/openzwave_shared/src/openzwave.o
  CXX(target) Release/obj.target/openzwave_shared/src/openzwave-config.o
...
  SOLINK_MODULE(target) Release/obj.target/openzwave_shared.node
  COPY Release/openzwave_shared.node
make: Leaving directory `/node_modules/openzwave-shared/build'
/
`-- openzwave-shared@1.3.4 
  `-- nan@2.5.0 

npm WARN enoent ENOENT: no such file or directory, open '/package.json'
npm WARN !invalid#1 No description
npm WARN !invalid#1 No repository field.
npm WARN !invalid#1 No README data
npm WARN !invalid#1 No license field.
root@e4a9b80139d4:/# ```

**Comment by ekarak** [comment]
I also manually ran a Travis build and it was successful for Node 6 on Precise 12.04.5:
https://travis-ci.org/OpenZWave/node-openzwave-shared/builds/223095033

I'll add a Node 7 target in my travis.yml to see if it breaks

**Comment by ekarak** [comment]
also seems to work with NodeJS 7.10 
https://travis-ci.org/OpenZWave/node-openzwave-shared/jobs/229405998

**Comment by Apollon77** [comment]
We Currently use the sudo: required option .. I will try to remove that. With sudo:required Travis is not using docker image but a "real"machine. Maybe something with this only ... will try to remove that later today and see if it works then

**Comment by Apollon77** [comment]
Ok, we need to have "sudo" for Travis. WOuld it be possible for you to test travis with ours with a "sudo: required" ?! Thank you

**Comment by Apollon77** [comment]
PS: can you send me the content of your travis config file?!

**Comment by ekarak** [comment]
https://github.com/OpenZWave/node-openzwave-shared/blob/master/.travis.yml

**Comment by Apollon77** [comment]
Just as short followup: I have created a symbolic link to nodejs from node because it seems even iv "which nodejs || which node" produces a correct output, the exitcvode seems to be strange sometimes (at least on travis-ci). So with ensuring that "nodejs" is there and the first command already gives the successfull output it works!

https://travis-ci.org/ioBroker/ioBroker.zwave/jobs/260966071#L45

I think node is more common then nodejs, or !? Maybe switch order in your command? :-))
