### ISSUE TITLE
node-gyp rebuild failed on Raspberry Pi 2

### ISSUE THREAD

**Issue by oguime** [OpenZWave/node-openzwave-shared#17]
Hi,

Could not install using sudo npm install openzwave-shared --unsafe-perm -g.

This is the npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'openzwave-shared',
1 verbose cli   '--unsafe-perm',
1 verbose cli   '-g' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose node symlink /usr/bin/node
5 verbose install initial load of /usr/lib/package.json
6 verbose readDependencies loading dependencies from /usr/lib/package.json
7 silly cache add args [ 'openzwave-shared', null ]
8 verbose cache add spec openzwave-shared
9 silly cache add parsed spec { raw: 'openzwave-shared',
9 silly cache add   scope: null,
9 silly cache add   name: 'openzwave-shared',
9 silly cache add   rawSpec: '',
9 silly cache add   spec: '*',
9 silly cache add   type: 'range' }
10 silly addNamed openzwave-shared@*
11 verbose addNamed "*" is a valid semver range for openzwave-shared
12 silly addNameRange { name: 'openzwave-shared', range: '*', hasData: false }
13 silly mapToRegistry name openzwave-shared
14 silly mapToRegistry using default registry
15 silly mapToRegistry registry https://registry.npmjs.org/
16 silly mapToRegistry uri https://registry.npmjs.org/openzwave-shared
17 verbose addNameRange registry:https://registry.npmjs.org/openzwave-shared not in flight; fetching
18 verbose request uri https://registry.npmjs.org/openzwave-shared
19 verbose request no auth needed
20 info attempt registry request try #1 at 20:23:41
21 verbose request id bbbfafbfb75e3dcc
22 verbose etag "BCCPVR61G5G1MJO20BJ2UCP1M"
23 http request GET https://registry.npmjs.org/openzwave-shared
24 http 304 https://registry.npmjs.org/openzwave-shared
25 silly get cb [ 304,
25 silly get   { date: 'Sun, 20 Sep 2015 23:23:42 GMT',
25 silly get     via: '1.1 varnish',
25 silly get     'cache-control': 'max-age=60',
25 silly get     etag: '"BCCPVR61G5G1MJO20BJ2UCP1M"',
25 silly get     age: '0',
25 silly get     connection: 'keep-alive',
25 silly get     'x-served-by': 'cache-iad2121-IAD',
25 silly get     'x-cache': 'MISS',
25 silly get     'x-cache-hits': '0',
25 silly get     'x-timer': 'S1442791422.461269,VS0,VE12',
25 silly get     vary: 'Accept' } ]
26 verbose etag https://registry.npmjs.org/openzwave-shared from cache
27 verbose get saving openzwave-shared to /root/.npm/registry.npmjs.org/openzwave-shared/.cache.json
28 silly addNameRange number 2 { name: 'openzwave-shared', range: '*', hasData: true }
29 silly addNameRange versions [ 'openzwave-shared',
29 silly addNameRange   [ '0.0.1',
29 silly addNameRange     '0.0.2',
29 silly addNameRange     '0.1.0',
29 silly addNameRange     '1.0.0',
29 silly addNameRange     '1.0.1',
29 silly addNameRange     '1.0.2',
29 silly addNameRange     '1.0.3',
29 silly addNameRange     '1.0.4',
29 silly addNameRange     '1.0.5' ] ]
30 silly addNamed openzwave-shared@1.0.5
31 verbose addNamed "1.0.5" is a plain semver version for openzwave-shared
32 silly cache afterAdd openzwave-shared@1.0.5
33 verbose afterAdd /root/.npm/openzwave-shared/1.0.5/package/package.json not in flight; writing
34 verbose afterAdd /root/.npm/openzwave-shared/1.0.5/package/package.json written
35 silly install resolved [ { name: 'openzwave-shared',
35 silly install resolved     version: '1.0.5',
35 silly install resolved     description: 'Node.JS bindings for OpenZWave including the long-missing management functions',
35 silly install resolved     main: './lib/openzwave-shared.js',
35 silly install resolved     dependencies: { nan: '~2.0.9' },
35 silly install resolved     scripts: { test: 'node test.js', install: 'node-gyp rebuild' },
35 silly install resolved     repository:
35 silly install resolved      { type: 'git',
35 silly install resolved        url: 'git://github.com/OpenZWave/node-openzwave-shared.git' },
35 silly install resolved     keywords: [ 'zwave', 'z-wave', 'home automation', 'openzwave' ],
35 silly install resolved     author:
35 silly install resolved      { name: 'Elias Karakoulakis',
35 silly install resolved        email: 'elias.karakoulakis@gmail.com' },
35 silly install resolved     contributors: [ [Object] ],
35 silly install resolved     licenses: [ [Object], [Object] ],
35 silly install resolved     gypfile: true,
35 silly install resolved     gitHead: '249e9ada37f314f36e236bce9c1c28ba5a4e7b82',
35 silly install resolved     bugs: { url: 'https://github.com/OpenZWave/node-openzwave-shared/issues' },
35 silly install resolved     homepage: 'https://github.com/OpenZWave/node-openzwave-shared#readme',
35 silly install resolved     _id: 'openzwave-shared@1.0.5',
35 silly install resolved     _shasum: '863821702473c551dc7eba70411d4ec6fc53f383',
35 silly install resolved     _from: 'openzwave-shared@*',
35 silly install resolved     _npmVersion: '2.10.1',
35 silly install resolved     _nodeVersion: '0.12.4',
35 silly install resolved     _npmUser: { name: 'ekarak', email: 'elias.karakoulakis@gmail.com' },
35 silly install resolved     maintainers: [ [Object] ],
35 silly install resolved     dist:
35 silly install resolved      { shasum: '863821702473c551dc7eba70411d4ec6fc53f383',
35 silly install resolved        tarball: 'http://registry.npmjs.org/openzwave-shared/-/openzwave-shared-1.0.5.tgz' },
35 silly install resolved     directories: {},
35 silly install resolved     _resolved: 'https://registry.npmjs.org/openzwave-shared/-/openzwave-shared-1.0.5.tgz',
35 silly install resolved     readme: 'ERROR: No README data found!' } ]
36 info install openzwave-shared@1.0.5 into /usr/lib
37 info installOne openzwave-shared@1.0.5
38 verbose installOne of openzwave-shared to /usr/lib not in flight; installing
39 verbose lock using /root/.npm/_locks/openzwave-shared-f315b58a40445133.lock for /usr/lib/node_modules/openzwave-shared
40 silly install write writing openzwave-shared 1.0.5 to /usr/lib/node_modules/openzwave-shared
41 verbose unbuild lib/node_modules/openzwave-shared
42 silly gentlyRm /usr/lib/node_modules/openzwave-shared is being purged from base /usr
43 verbose gentlyRm don't care about contents; nuking /usr/lib/node_modules/openzwave-shared
44 verbose tar unpack /root/.npm/openzwave-shared/1.0.5/package.tgz
45 verbose tar unpacking to /usr/lib/node_modules/openzwave-shared
46 silly gentlyRm /usr/lib/node_modules/openzwave-shared is being purged
47 verbose gentlyRm don't care about contents; nuking /usr/lib/node_modules/openzwave-shared
48 silly gunzTarPerm modes [ '755', '644' ]
49 silly gunzTarPerm extractEntry package.json
50 silly gunzTarPerm modified mode [ 'package.json', 436, 420 ]
51 silly gunzTarPerm extractEntry .npmignore
52 silly gunzTarPerm modified mode [ '.npmignore', 436, 420 ]
53 silly gunzTarPerm extractEntry README.md
54 silly gunzTarPerm modified mode [ 'README.md', 436, 420 ]
55 silly gunzTarPerm extractEntry test.js
56 silly gunzTarPerm modified mode [ 'test.js', 436, 420 ]
57 silly gunzTarPerm extractEntry test2.js
58 silly gunzTarPerm modified mode [ 'test2.js', 436, 420 ]
59 silly gunzTarPerm extractEntry README-raspbian.md
60 silly gunzTarPerm modified mode [ 'README-raspbian.md', 436, 420 ]
61 silly gunzTarPerm extractEntry README-ubuntu.md
62 silly gunzTarPerm modified mode [ 'README-ubuntu.md', 436, 420 ]
63 silly gunzTarPerm extractEntry binding.gyp
64 silly gunzTarPerm modified mode [ 'binding.gyp', 436, 420 ]
65 silly gunzTarPerm extractEntry LICENSE.md
66 silly gunzTarPerm modified mode [ 'LICENSE.md', 436, 420 ]
67 silly gunzTarPerm extractEntry lib/openzwave-shared.js
68 silly gunzTarPerm modified mode [ 'lib/openzwave-shared.js', 436, 420 ]
69 silly gunzTarPerm extractEntry notes.txt
70 silly gunzTarPerm modified mode [ 'notes.txt', 436, 420 ]
71 silly gunzTarPerm extractEntry README-api.md
72 silly gunzTarPerm modified mode [ 'README-api.md', 436, 420 ]
73 silly gunzTarPerm extractEntry src/openzwave-polling.cc
74 silly gunzTarPerm modified mode [ 'src/openzwave-polling.cc', 436, 420 ]
75 silly gunzTarPerm extractEntry src/callbacks.cc
76 silly gunzTarPerm modified mode [ 'src/callbacks.cc', 436, 420 ]
77 silly gunzTarPerm extractEntry src/openzwave-driver.cc
78 silly gunzTarPerm modified mode [ 'src/openzwave-driver.cc', 436, 420 ]
79 silly gunzTarPerm extractEntry src/openzwave-groups.cc
80 silly gunzTarPerm modified mode [ 'src/openzwave-groups.cc', 436, 420 ]
81 silly gunzTarPerm extractEntry src/openzwave-network.cc
82 silly gunzTarPerm modified mode [ 'src/openzwave-network.cc', 436, 420 ]
83 silly gunzTarPerm extractEntry src/openzwave-nodes.cc
84 silly gunzTarPerm modified mode [ 'src/openzwave-nodes.cc', 436, 420 ]
85 silly gunzTarPerm extractEntry src/openzwave-config.cc
86 silly gunzTarPerm modified mode [ 'src/openzwave-config.cc', 436, 420 ]
87 silly gunzTarPerm extractEntry src/openzwave-scenes.cc
88 silly gunzTarPerm modified mode [ 'src/openzwave-scenes.cc', 436, 420 ]
89 silly gunzTarPerm extractEntry src/openzwave-values.cc
90 silly gunzTarPerm modified mode [ 'src/openzwave-values.cc', 436, 420 ]
91 silly gunzTarPerm extractEntry src/openzwave.cc
92 silly gunzTarPerm modified mode [ 'src/openzwave.cc', 436, 420 ]
93 silly gunzTarPerm extractEntry src/openzwave.hpp
94 silly gunzTarPerm modified mode [ 'src/openzwave.hpp', 436, 420 ]
95 silly gunzTarPerm extractEntry src/utils.cc
96 silly gunzTarPerm modified mode [ 'src/utils.cc', 436, 420 ]
97 silly gunzTarPerm extractEntry README-events.md
98 silly gunzTarPerm modified mode [ 'README-events.md', 436, 420 ]
99 silly gunzTarPerm extractEntry README-example.md
100 silly gunzTarPerm modified mode [ 'README-example.md', 436, 420 ]
101 verbose write writing to /usr/lib/node_modules/openzwave-shared/package.json
102 info preinstall openzwave-shared@1.0.5
103 verbose readDependencies loading dependencies from /usr/lib/node_modules/openzwave-shared/package.json
104 silly prepareForInstallMany adding nan@~2.0.9 from openzwave-shared dependencies
105 verbose readDependencies loading dependencies from /usr/lib/node_modules/openzwave-shared/package.json
106 silly cache add args [ 'nan@~2.0.9', null ]
107 verbose cache add spec nan@~2.0.9
108 silly cache add parsed spec { raw: 'nan@~2.0.9',
108 silly cache add   scope: null,
108 silly cache add   name: 'nan',
108 silly cache add   rawSpec: '~2.0.9',
108 silly cache add   spec: '>=2.0.9 <2.1.0',
108 silly cache add   type: 'range' }
109 silly addNamed nan@>=2.0.9 <2.1.0
110 verbose addNamed ">=2.0.9 <2.1.0" is a valid semver range for nan
111 silly addNameRange { name: 'nan', range: '>=2.0.9 <2.1.0', hasData: false }
112 silly mapToRegistry name nan
113 silly mapToRegistry using default registry
114 silly mapToRegistry registry https://registry.npmjs.org/
115 silly mapToRegistry uri https://registry.npmjs.org/nan
116 verbose addNameRange registry:https://registry.npmjs.org/nan not in flight; fetching
117 verbose request uri https://registry.npmjs.org/nan
118 verbose request no auth needed
119 info attempt registry request try #1 at 20:23:43
120 verbose etag "1L4RU1AM541YSVP1YQFXG1Y1J"
121 http request GET https://registry.npmjs.org/nan
122 http 304 https://registry.npmjs.org/nan
123 silly get cb [ 304,
123 silly get   { date: 'Sun, 20 Sep 2015 23:23:44 GMT',
123 silly get     via: '1.1 varnish',
123 silly get     'cache-control': 'max-age=60',
123 silly get     etag: '"1L4RU1AM541YSVP1YQFXG1Y1J"',
123 silly get     age: '46',
123 silly get     connection: 'keep-alive',
123 silly get     'x-served-by': 'cache-iad2143-IAD',
123 silly get     'x-cache': 'HIT',
123 silly get     'x-cache-hits': '2',
123 silly get     'x-timer': 'S1442791424.232181,VS0,VE0',
123 silly get     vary: 'Accept' } ]
124 verbose etag https://registry.npmjs.org/nan from cache
125 verbose get saving nan to /root/.npm/registry.npmjs.org/nan/.cache.json
126 silly addNameRange number 2 { name: 'nan', range: '>=2.0.9 <2.1.0', hasData: true }
127 silly addNameRange versions [ 'nan',
127 silly addNameRange   [ '0.3.0-wip',
127 silly addNameRange     '0.3.0-wip2',
127 silly addNameRange     '0.3.0',
127 silly addNameRange     '0.3.1',
127 silly addNameRange     '0.3.2',
127 silly addNameRange     '0.4.0',
127 silly addNameRange     '0.4.1',
127 silly addNameRange     '0.4.2',
127 silly addNameRange     '0.4.3',
127 silly addNameRange     '0.4.4',
127 silly addNameRange     '0.5.0',
127 silly addNameRange     '0.5.1',
127 silly addNameRange     '0.5.2',
127 silly addNameRange     '0.6.0',
127 silly addNameRange     '0.7.0',
127 silly addNameRange     '0.7.1',
127 silly addNameRange     '0.8.0',
127 silly addNameRange     '1.0.0',
127 silly addNameRange     '1.1.0',
127 silly addNameRange     '1.1.1',
127 silly addNameRange     '1.1.2',
127 silly addNameRange     '1.2.0',
127 silly addNameRange     '1.3.0',
127 silly addNameRange     '1.4.0',
127 silly addNameRange     '1.4.1',
127 silly addNameRange     '1.5.0',
127 silly addNameRange     '1.4.2',
127 silly addNameRange     '1.4.3',
127 silly addNameRange     '1.5.1',
127 silly addNameRange     '1.5.2',
127 silly addNameRange     '1.6.0',
127 silly addNameRange     '1.5.3',
127 silly addNameRange     '1.6.1',
127 silly addNameRange     '1.6.2',
127 silly addNameRange     '1.7.0',
127 silly addNameRange     '1.8.0',
127 silly addNameRange     '1.8.1',
127 silly addNameRange     '1.8.2',
127 silly addNameRange     '1.8.3',
127 silly addNameRange     '1.8.4',
127 silly addNameRange     '1.9.0',
127 silly addNameRange     '2.0.0',
127 silly addNameRange     '2.0.1',
127 silly addNameRange     '2.0.2',
127 silly addNameRange     '2.0.3',
127 silly addNameRange     '2.0.4',
127 silly addNameRange     '2.0.5',
127 silly addNameRange     '2.0.6',
127 silly addNameRange     '2.0.7',
127 silly addNameRange     '2.0.8',
127 silly addNameRange     '2.0.9' ] ]
128 silly addNamed nan@2.0.9
129 verbose addNamed "2.0.9" is a plain semver version for nan
130 silly cache afterAdd nan@2.0.9
131 verbose afterAdd /root/.npm/nan/2.0.9/package/package.json not in flight; writing
132 verbose afterAdd /root/.npm/nan/2.0.9/package/package.json written
133 silly install resolved [ { name: 'nan',
133 silly install resolved     version: '2.0.9',
133 silly install resolved     description: 'Native Abstractions for Node.js: C++ header for Node 0.8 -> 4 compatibility',
133 silly install resolved     main: 'include_dirs.js',
133 silly install resolved     repository: { type: 'git', url: 'git://github.com/nodejs/nan.git' },
133 silly install resolved     scripts:
133 silly install resolved      { test: 'tap --gc test/js/*-test.js',
133 silly install resolved        'rebuild-tests': 'pangyp rebuild --msvs_version=2013 --directory test',
133 silly install resolved        docs: 'doc/.build.sh' },
133 silly install resolved     contributors:
133 silly install resolved      [ [Object],
133 silly install resolved        [Object],
133 silly install resolved        [Object],
133 silly install resolved        [Object],
133 silly install resolved        [Object],
133 silly install resolved        [Object],
133 silly install resolved        [Object] ],
133 silly install resolved     devDependencies:
133 silly install resolved      { bindings: '~1.2.1',
133 silly install resolved        commander: '^2.8.1',
133 silly install resolved        glob: '^5.0.14',
133 silly install resolved        'node-gyp': '~2.0.2',
133 silly install resolved        pangyp: '~2.2.0',
133 silly install resolved        tap: '~0.7.1',
133 silly install resolved        xtend: '~4.0.0' },
133 silly install resolved     license: 'MIT',
133 silly install resolved     bugs: { url: 'https://github.com/nodejs/nan/issues' },
133 silly install resolved     homepage: 'https://github.com/nodejs/nan#readme',
133 silly install resolved     _id: 'nan@2.0.9',
133 silly install resolved     _shasum: 'd02a770f46778842cceb94e17cab31ffc7234a05',
133 silly install resolved     _resolved: 'https://registry.npmjs.org/nan/-/nan-2.0.9.tgz',
133 silly install resolved     _from: 'nan@>=2.0.9 <2.1.0',
133 silly install resolved     _npmVersion: '2.14.2',
133 silly install resolved     _nodeVersion: '4.0.0',
133 silly install resolved     _npmUser: { name: 'kkoopa', email: 'bbyholm@abo.fi' },
133 silly install resolved     maintainers: [ [Object], [Object] ],
133 silly install resolved     dist:
133 silly install resolved      { shasum: 'd02a770f46778842cceb94e17cab31ffc7234a05',
133 silly install resolved        tarball: 'http://registry.npmjs.org/nan/-/nan-2.0.9.tgz' },
133 silly install resolved     directories: {},
133 silly install resolved     readme: 'ERROR: No README data found!' } ]
134 info install nan@2.0.9 into /usr/lib/node_modules/openzwave-shared
135 info installOne nan@2.0.9
136 verbose installOne of nan to /usr/lib/node_modules/openzwave-shared not in flight; installing
137 verbose lock using /root/.npm/_locks/nan-2cd25d6ba96a3d35.lock for /usr/lib/node_modules/openzwave-shared/node_modules/nan
138 silly install write writing nan 2.0.9 to /usr/lib/node_modules/openzwave-shared/node_modules/nan
139 verbose unbuild lib/node_modules/openzwave-shared/node_modules/nan
140 silly gentlyRm /usr/lib/node_modules/openzwave-shared/node_modules/nan is being purged from base /usr
141 verbose gentlyRm don't care about contents; nuking /usr/lib/node_modules/openzwave-shared/node_modules/nan
142 verbose tar unpack /root/.npm/nan/2.0.9/package.tgz
143 verbose tar unpacking to /usr/lib/node_modules/openzwave-shared/node_modules/nan
144 silly gentlyRm /usr/lib/node_modules/openzwave-shared/node_modules/nan is being purged
145 verbose gentlyRm don't care about contents; nuking /usr/lib/node_modules/openzwave-shared/node_modules/nan
146 silly gunzTarPerm modes [ '755', '644' ]
147 silly gunzTarPerm extractEntry package.json
148 silly gunzTarPerm modified mode [ 'package.json', 436, 420 ]
149 silly gunzTarPerm extractEntry README.md
150 silly gunzTarPerm modified mode [ 'README.md', 436, 420 ]
151 silly gunzTarPerm extractEntry include_dirs.js
152 silly gunzTarPerm modified mode [ 'include_dirs.js', 436, 420 ]
153 silly gunzTarPerm extractEntry nan_converters.h
154 silly gunzTarPerm modified mode [ 'nan_converters.h', 436, 420 ]
155 silly gunzTarPerm extractEntry LICENSE.md
156 silly gunzTarPerm modified mode [ 'LICENSE.md', 436, 420 ]
157 silly gunzTarPerm extractEntry .dntrc
158 silly gunzTarPerm modified mode [ '.dntrc', 436, 420 ]
159 silly gunzTarPerm extractEntry appveyor.yml
160 silly gunzTarPerm modified mode [ 'appveyor.yml', 436, 420 ]
161 silly gunzTarPerm extractEntry doc/new.md
162 silly gunzTarPerm modified mode [ 'doc/new.md', 436, 420 ]
163 silly gunzTarPerm extractEntry doc/.build.sh
164 silly gunzTarPerm modified mode [ 'doc/.build.sh', 509, 493 ]
165 silly gunzTarPerm extractEntry doc/buffers.md
166 silly gunzTarPerm modified mode [ 'doc/buffers.md', 436, 420 ]
167 silly gunzTarPerm extractEntry doc/callback.md
168 silly gunzTarPerm modified mode [ 'doc/callback.md', 436, 420 ]
169 silly gunzTarPerm extractEntry doc/converters.md
170 silly gunzTarPerm modified mode [ 'doc/converters.md', 436, 420 ]
171 silly gunzTarPerm extractEntry doc/errors.md
172 silly gunzTarPerm modified mode [ 'doc/errors.md', 436, 420 ]
173 silly gunzTarPerm extractEntry doc/maybe_types.md
174 silly gunzTarPerm modified mode [ 'doc/maybe_types.md', 436, 420 ]
175 silly gunzTarPerm extractEntry doc/methods.md
176 silly gunzTarPerm modified mode [ 'doc/methods.md', 436, 420 ]
177 silly gunzTarPerm extractEntry doc/asyncworker.md
178 silly gunzTarPerm modified mode [ 'doc/asyncworker.md', 436, 420 ]
179 silly gunzTarPerm extractEntry doc/node_misc.md
180 silly gunzTarPerm modified mode [ 'doc/node_misc.md', 436, 420 ]
181 silly gunzTarPerm extractEntry doc/persistent.md
182 silly gunzTarPerm modified mode [ 'doc/persistent.md', 436, 420 ]
183 silly gunzTarPerm extractEntry doc/scopes.md
184 silly gunzTarPerm modified mode [ 'doc/scopes.md', 436, 420 ]
185 silly gunzTarPerm extractEntry doc/script.md
186 silly gunzTarPerm modified mode [ 'doc/script.md', 436, 420 ]
187 silly gunzTarPerm extractEntry doc/string_bytes.md
188 silly gunzTarPerm modified mode [ 'doc/string_bytes.md', 436, 420 ]
189 silly gunzTarPerm extractEntry doc/v8_internals.md
190 silly gunzTarPerm modified mode [ 'doc/v8_internals.md', 436, 420 ]
191 silly gunzTarPerm extractEntry doc/v8_misc.md
192 silly gunzTarPerm modified mode [ 'doc/v8_misc.md', 436, 420 ]
193 silly gunzTarPerm extractEntry nan.h
194 silly gunzTarPerm modified mode [ 'nan.h', 436, 420 ]
195 silly gunzTarPerm extractEntry nan_callbacks.h
196 silly gunzTarPerm modified mode [ 'nan_callbacks.h', 436, 420 ]
197 silly gunzTarPerm extractEntry nan_callbacks_12_inl.h
198 silly gunzTarPerm modified mode [ 'nan_callbacks_12_inl.h', 436, 420 ]
199 silly gunzTarPerm extractEntry nan_callbacks_pre_12_inl.h
200 silly gunzTarPerm modified mode [ 'nan_callbacks_pre_12_inl.h', 436, 420 ]
201 silly gunzTarPerm extractEntry nan_converters_43_inl.h
202 silly gunzTarPerm modified mode [ 'nan_converters_43_inl.h', 436, 420 ]
203 silly gunzTarPerm extractEntry nan_converters_pre_43_inl.h
204 silly gunzTarPerm modified mode [ 'nan_converters_pre_43_inl.h', 436, 420 ]
205 silly gunzTarPerm extractEntry nan_implementation_12_inl.h
206 silly gunzTarPerm modified mode [ 'nan_implementation_12_inl.h', 436, 420 ]
207 silly gunzTarPerm extractEntry nan_implementation_pre_12_inl.h
208 silly gunzTarPerm modified mode [ 'nan_implementation_pre_12_inl.h', 436, 420 ]
209 silly gunzTarPerm extractEntry nan_maybe_43_inl.h
210 silly gunzTarPerm modified mode [ 'nan_maybe_43_inl.h', 436, 420 ]
211 silly gunzTarPerm extractEntry nan_maybe_pre_43_inl.h
212 silly gunzTarPerm modified mode [ 'nan_maybe_pre_43_inl.h', 436, 420 ]
213 silly gunzTarPerm extractEntry nan_new.h
214 silly gunzTarPerm modified mode [ 'nan_new.h', 436, 420 ]
215 silly gunzTarPerm extractEntry nan_object_wrap.h
216 silly gunzTarPerm modified mode [ 'nan_object_wrap.h', 436, 420 ]
217 silly gunzTarPerm extractEntry nan_persistent_12_inl.h
218 silly gunzTarPerm modified mode [ 'nan_persistent_12_inl.h', 436, 420 ]
219 silly gunzTarPerm extractEntry nan_persistent_pre_12_inl.h
220 silly gunzTarPerm modified mode [ 'nan_persistent_pre_12_inl.h', 436, 420 ]
221 silly gunzTarPerm extractEntry nan_string_bytes.h
222 silly gunzTarPerm modified mode [ 'nan_string_bytes.h', 436, 420 ]
223 silly gunzTarPerm extractEntry nan_weak.h
224 silly gunzTarPerm modified mode [ 'nan_weak.h', 436, 420 ]
225 silly gunzTarPerm extractEntry CHANGELOG.md
226 silly gunzTarPerm modified mode [ 'CHANGELOG.md', 436, 420 ]
227 silly gunzTarPerm extractEntry tools/package.json
228 silly gunzTarPerm modified mode [ 'tools/package.json', 436, 420 ]
229 silly gunzTarPerm extractEntry tools/README.md
230 silly gunzTarPerm modified mode [ 'tools/README.md', 436, 420 ]
231 silly gunzTarPerm extractEntry tools/1to2.js
232 silly gunzTarPerm modified mode [ 'tools/1to2.js', 509, 493 ]
233 verbose write writing to /usr/lib/node_modules/openzwave-shared/node_modules/nan/package.json
234 info preinstall nan@2.0.9
235 verbose readDependencies loading dependencies from /usr/lib/node_modules/openzwave-shared/node_modules/nan/package.json
236 verbose readDependencies loading dependencies from /usr/lib/node_modules/openzwave-shared/node_modules/nan/package.json
237 silly install resolved []
238 verbose about to build /usr/lib/node_modules/openzwave-shared/node_modules/nan
239 info build /usr/lib/node_modules/openzwave-shared/node_modules/nan
240 info linkStuff nan@2.0.9
241 silly linkStuff nan@2.0.9 has /usr/lib/node_modules/openzwave-shared/node_modules as its parent node_modules
242 silly linkStuff nan@2.0.9 is part of a global install
243 silly linkStuff nan@2.0.9 is installed into a global node_modules
244 verbose linkBins nan@2.0.9
245 verbose linkMans nan@2.0.9
246 verbose rebuildBundles nan@2.0.9
247 info install nan@2.0.9
248 info postinstall nan@2.0.9
249 verbose unlock done using /root/.npm/_locks/nan-2cd25d6ba96a3d35.lock for /usr/lib/node_modules/openzwave-shared/node_modules/nan
250 verbose about to build /usr/lib/node_modules/openzwave-shared
251 info build /usr/lib/node_modules/openzwave-shared
252 info linkStuff openzwave-shared@1.0.5
253 silly linkStuff openzwave-shared@1.0.5 has /usr/lib/node_modules as its parent node_modules
254 silly linkStuff openzwave-shared@1.0.5 is part of a global install
255 silly linkStuff openzwave-shared@1.0.5 is installed into a global node_modules
256 silly linkStuff openzwave-shared@1.0.5 is installed into the top-level global node_modules
257 verbose linkBins openzwave-shared@1.0.5
258 verbose linkMans openzwave-shared@1.0.5
259 verbose rebuildBundles openzwave-shared@1.0.5
260 verbose rebuildBundles [ 'nan' ]
261 info install openzwave-shared@1.0.5
262 verbose unsafe-perm in lifecycle true
263 info openzwave-shared@1.0.5 Failed to exec install script
264 verbose unlock done using /root/.npm/_locks/openzwave-shared-f315b58a40445133.lock for /usr/lib/node_modules/openzwave-shared
265 verbose stack Error: openzwave-shared@1.0.5 install: `node-gyp rebuild`
265 verbose stack Exit status 1
265 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
265 verbose stack     at EventEmitter.emit (events.js:110:17)
265 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
265 verbose stack     at ChildProcess.emit (events.js:110:17)
265 verbose stack     at maybeClose (child_process.js:1015:16)
265 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
266 verbose pkgid openzwave-shared@1.0.5
267 verbose cwd /home/pi/openzwave-1.3.487
268 error Linux 4.1.6-v7+
269 error argv "/usr/bin/node" "/usr/bin/npm" "install" "openzwave-shared" "--unsafe-perm" "-g"
270 error node v0.12.7
271 error npm  v2.11.3
272 error code ELIFECYCLE
273 error openzwave-shared@1.0.5 install: `node-gyp rebuild`
273 error Exit status 1
274 error Failed at the openzwave-shared@1.0.5 install script 'node-gyp rebuild'.
274 error This is most likely a problem with the openzwave-shared package,
274 error not with npm itself.
274 error Tell the author that this fails on your system:
274 error     node-gyp rebuild
274 error You can get their info via:
274 error     npm owner ls openzwave-shared
274 error There is likely additional logging output above.
275 verbose exit [ 1, true ]
276 verbose unbuild lib/node_modules/openzwave-shared
277 info preuninstall openzwave-shared@1.0.5
278 info uninstall openzwave-shared@1.0.5
279 verbose unbuild rmStuff openzwave-shared@1.0.5 from /usr/lib/node_modules
280 info postuninstall openzwave-shared@1.0.5
281 silly gentlyRm /usr/lib/node_modules/openzwave-shared is being purged from base /usr
282 verbose gentlyRm don't care about contents; nuking /usr/lib/node_modules/openzwave-shared
283 silly vacuum-fs purging /usr/lib/node_modules/openzwave-shared
284 silly vacuum-fs quitting because other entries in /usr/lib/node_modules

**Comment by ekarak** [comment]
please try version 1.0.6 which I just released on npm.

**Comment by oguime** [comment]
Hi ekarak,

1.0.6 installed fine, thanks a lot!

**Comment by ekarak** [comment]
resolving
