### ISSUE TITLE
Config Parameter "value changed"

### ISSUE THREAD

**Issue by japita-se** [OpenZWave/node-openzwave-shared#170]
I try to set a parameter by using setConfigParam.
I supposed that when the device receive this message, it will reply with an event "value changed".
But, it seems that for some devices this does not happens.
For example the Door/Windows of Aeotec DSB29, if I send "17" for class "121" (Binay Report), it will behave correctly even if no "value changed" event has been fired.

**Comment by ekarak** [comment]
I'm sorry, I can't help you with individual device issues. Please check on the main OpenZWave mailing list, and please *please* open an issue if you suspect a bug exists in the *NodeJS addon* and *not OpenZWave*.

**Comment by japita-se** [comment]
Actually, it does not work at all.
We are trying to set the configuration parameter, setConfParam.
This is the sequence:
1. setConfParam to some node
2. OpenZwave "fire" value changed event.
3. Restart the software (scan of the network).
4. The device respond with old values!
