### ISSUE TITLE
how I can store the node information after the first scan 

### ISSUE THREAD

**Issue by YasserENISO** [OpenZWave/node-openzwave-shared#171]
I have installed the library open zwave and also the addon node open zwave shared and when I run the scan by testing Test2.js all the nodes are well defined in the network ! But now I like to know where I can find this result? In which file to store them in the mysql database .

I am a beginner in development and specially the nodejs but i like to learn more to realize my application! And thank you in advance for your help

**Comment by ekarak** [comment]
Hello, 

The test.js and test2.js scripts in the root directory shows how to store node information (see the `nodes` array). Its really a hierarchical structure that you need to serialise it to the database to a proper schema. There's really no need for you to store this information in a DB, as the OpenZWave library will rebuild the current list of nodes in the network upon bootup.

**Comment by YasserENISO** [comment]
thank you :)
