### ISSUE TITLE
Problem with PIR sensors

### ISSUE THREAD

**Issue by Marconapo** [OpenZWave/node-openzwave-shared#172]
Hi everybody!
I have got a problem with Philio PST02-A and Aeotec Multisensor Gen5.
According to their manual while burglar triggers I have to receive values 8 or 254 for the first and 7 or 1 for the latter.
For both I receive the first value that indicates a movement but I don't receive the second one that indicates the PIR go back to the initial state.
Considering the situation I wrote to the companies of these sensors asking them any suggestion; they gave me but although I followed them I didn't solve the problem, so I tried various settings and various version of the library node-openzwave-shared but the situation doesn't change.
Is that a known bug?

**Comment by ekarak** [comment]
I'm sorry, I can't help you with individual device issues. Please check on the main OpenZWave mailing list, and please *please* open an issue if you suspect a bug exists in the *NodeJS addon* and *not OpenZWave*.
