### ISSUE TITLE
Polling Not Work Properly

### ISSUE THREAD

**Issue by japita-se** [OpenZWave/node-openzwave-shared#175]
We tried 1.4.0.
But the polling is not working anymore.
For example, we had an AEOTEC smart switch 2nd edition.
With version 1.3.4, no problem: the device reported every values (voltage, power, and so on).
Moreover, we could catch timeout events.

With version 1.4.0, some classes values are gone and also no timeout events are available.

**Comment by ekarak** [comment]
please take a look at the README where I quote:

> API change notice (v1.4.0) enablePoll() and disablePoll() used to affect only the first ValueID of any given command class. This is wrong, as for multi-instance devices you probably need to poll multiple ValueID's. These calls now accept a valueId, in very much the same way as setValue() does. This means that you now have to pass a valueID object (or its 4 constituents) for each value you want to enable/disable polling for.

Therefore you need to enablePoll() for each of the ValueID's you're interested in.
