### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by Zombitch** [OpenZWave/node-openzwave-shared#188]
Hi,

In the file [README-example.md](https://github.com/OpenZWave/node-openzwave-shared/blob/master/README-example.md) there is a mistake that prevent the example to work.

On the listener "value added" you should affect the variable**valueId** instead of **value** since it has been renamed here : 

> zwave.on('value added', function(nodeid, comclass, valueId) {
>  if (!nodes[nodeid]['classes'][comclass])
>         nodes[nodeid]['classes'][comclass] = {};
>     nodes[nodeid]['classes'][comclass][valueId.index] = **value**; // Should be valueId
> });

It looks like a missed copy/paste ;)

Regards,
Zombitch

**Comment by ekarak** [comment]
thanks, I fixed the typo.
