### ISSUE TITLE
Setting a button to false should release it

### ISSUE THREAD

**Issue by AlCalzone** [OpenZWave/node-openzwave-shared#192]
https://github.com/OpenZWave/node-openzwave-shared/blob/master/src/openzwave-values.cc#L78
When a valueID for a button is changed, this line always presses the button and ignores the value. IMO setting the value to false, it should release the button.

As Start/StopLevelChange is bound to button Press/Release in OZW, this would allow stopping moving blinds by setting the value to false mid-motion.

**Comment by ekarak** [comment]
1st look is that this is a sane patch, and I'm willing to merge it
Really low on free time - apologies for the delay

**Comment by ekarak** [comment]
See https://github.com/OpenZWave/node-openzwave-shared/pull/206
