### ISSUE TITLE
z-wave battery node working in OZW panel, but when start node-red nothing happens, empty debug.

### ISSUE THREAD

**Issue by tridiumcontrols** [OpenZWave/node-openzwave-shared#194]
Hi, 

I have 4 z-wave smoke detectors, and not sure why it's doing this. I installed OZW control panel on my raspberry pi 3, I added the devices through the OZW control panel web interface, the first alert smoke/co is battery powered, with OZW control panel running node is working as expected.

![screen shot 2017-09-30 at 4 23 19 pm](https://user-images.githubusercontent.com/22411662/31050338-583758be-a5fc-11e7-9f1c-61c7036695d0.png)

but when I shutdown OZW and start up node-red, after scan is completed, the smoke sensor isn't listed as node ready, when I try to wake up the device, the debug window is empty, and even pressing the test button on the smoke detector, and nothing is being sent to the debug window, and the z-wave out node shows "scan complete" and no other events are working.

What is interesting is when I send a addNode command through the node-red interface to add a node, the device gets paired, and all works just fine for the session, BUT, on a reboot of the raspberry pi3, or start/stop the node-red service, and I wake up the device again to test it, and the debug window is empty, nothing is reported. BUT when i close node-red and start up OZW control panel, the device is listed, and operates just fine, I press the test button and events are coming in as expected. What can I do about this?

**Comment by ekarak** [comment]
First of all, this is **NOT** an issue with the Node.js driver, but with the Node-Red adapter. Hence I'm going to close this issue, and I'll kindly ask that if you don't  find a solution to open up an issue [in the Node-Red project](https://github.com/OpenZWave/node-red-contrib-openzwave)

You probably need to define the configuration directory that OpenZWave can use to load and save your network topology (that includes the battery devices). This file is named `zwcfg_xxxx.xml` where xxxx is the hex representation of your HomeID. If you run OZWCP and it produces that file, you need to copy that file to a location that the Node-Red adapter expects this to be.

According to [this lline](https://github.com/OpenZWave/node-red-contrib-openzwave/blob/master/10-zwave.js#L349), the location of this file should be the Node-Red user directory (`/home/foobar`). 

You can override the Node-Red userDir property by 
```$ node-red --userDir ./config```
