### ISSUE TITLE
Errors build for ..\src\utils.cc

### ISSUE THREAD

**Issue by jbreslin** [OpenZWave/node-openzwave-shared#196]
Hi,

I am looking for some assistance with a build issue in utils.cc, My node and node-red installations are working fine under Windows 10 but the compiler is failing with the attached errors and I am afraid I do not have the skills to identify and resolve. Any assistance would be much appreciated.

Many thanks
JohnB

..\src\utils.cc(65): error C2065: 'uint': undeclared identifier [C:\Program Files\nodejs\node_modules\openzwave-shared\build\openzwave_shared.vcxproj]
..\src\utils.cc(65): error C2146: syntax error: missing ')' before identifier 'node_id' [C:\Program Files\nodejs\node_modules\openzwave-shared\build\openzwave_shared.vcxproj]
..\src\utils.cc(65): error C2143: syntax error: missing ';' before '{' [C:\Program Files\nodejs\node_modules\openzwave-shared\build\openzwave_shared.vcxproj]
..\src\utils.cc(65): error C2447: '{': missing function header (old-style formal list?) [C:\Program Files\nodejs\node_modules\openzwave-shared\build\openzwave_shared.vcxproj]

{ I have removed a number of "warning C4244: '=': conversion from 'double' to 'uint8'....from here. }

..\src\utils.cc(331): error C2660: 'OZW::getValueIdDescriptor': function does not take 4 arguments [C:\Program Files\nodejs\node_modules\openzwave-shared\build\openzwave_shared.vcxproj]

**Comment by ekarak** [comment]
Apologies - no Windows environment for me to replicate this. I suspect this is a MSVC compiler quirk. 
More than happy to accept a pull request that fixes this issue, of course!

**Comment by gms1** [comment]
this isn't a compiler quirk, please use uint8 instead of uint as everywhere else
```
std::string getValueIdDescriptor(uint node_id, uint class_id, uint instance, uint index) {
```
(from C++ standard point of view 'uint8_t' would be even better)

**Comment by ekarak** [comment]
fixed. Thanks!
https://github.com/OpenZWave/node-openzwave-shared/commit/146b205cc5beccf0f6fb0ef9a4b52ba78b977502
