### ISSUE TITLE
Broken Build on Raspbian Stretch

### ISSUE THREAD

**Issue by japita-se** [OpenZWave/node-openzwave-shared#197]
On a fresh install of openzwave-shared on latest raspbian OS, we see a lot of 

```
gyp WARN EACCES attempting to reinstall using temporary dev dir ..
gyp WARN EACCES user "root" does not have permission to access the dev dir...

```

**Comment by ekarak** [comment]
https://duckduckgo.com/?q=gyp+WARN+EACCES+user+%22root%22+does+not+have+permission+to+access+the+dev+dir&t=canonical&ia=qa
