### ISSUE TITLE
Doesn't open config from zwcfg xml file

### ISSUE THREAD

**Issue by fraser73** [OpenZWave/node-openzwave-shared#198]
I've just rebuilt my pi with node-red and node-red-contrib-openzwave. All seems to work ok, except for in the previous build I had stored the zwcfg_{homeID}.xml and zwscene,xml files in the directory ".../node_moduled/node-red-contrib-openzwave/node_modules/openzwave-shared." This was so that I could make config changes with open zwave control panel and import them into node-red. The config files no-longer appear to be loaded from this location and I can't see where they are referenced in the code to work out where they are loaded from. Can you advise?

openzwave-shared = 1.4.0
node-red-contrib-openzwave = 1.2.1
node-red = 0.17.5
node = 6.11.4
Raspbian = Jessie, fully updated.

**Comment by fraser73** [comment]
In answer to my own question - This appears to be a possible change in node-red or node-red-contrib-openzwave, which does try to load/save the zwcfg file, however from the specified Node-Red "userDir". This is based on noticing that the OZW_Log.txt was being written there.

**Comment by ekarak** [comment]
Thanks - I had a similar issue raised on the node-red-contrib-openzwave project.
I need to add a note about this in the docs.
