### ISSUE TITLE
incorrect or unclear docs with regard to "test2.js"

### ISSUE THREAD

**Issue by JoeStrout** [OpenZWave/node-openzwave-shared#199]
I've followed the installation instructions up to the *Installation and Test Script*, where it says

> To try it out, boot up NodeJS, and use the .load shell helper function to boot up a basic OpenZWave CLI. This will initialise and expose 1) a zwave object that you can use to send commands and 2) the nodes object to get a list of all nodes

But when I try the commands shown, I get:

```
> .load test2.js
Failed to load:test2.js
> console.log(nodes[1])
ReferenceError: nodes is not defined

```
`zwave` is also undefined.  Where is this test2.js script supposed to be?  Or is that just a placeholder, and if so, what are we meant to put there?  What exactly does one need to type to get the zwave and nodes objects described?

**Comment by ekarak** [comment]
https://github.com/OpenZWave/node-openzwave-shared/blob/master/test2.js
resolving.

**Comment by JoeStrout** [comment]
I'm still getting "Failed to load:test2.js".  The read-me file hasn't changed, and still gives directions that do not work.  I don't understand why this issue was closed.

Can you please tell me what I must do to actually test2.js to load, as shown on the docs?  Perhaps it's obvious to somebody familiar with Node, but it's not obvious to me.

**Comment by JoeStrout** [comment]
To further elaborate: upon restarting node-RED, I get the following log message:

`[warn] [zwave] Error: libopenzwave.so.1.4: cannot open shared object file: No such file or directory (line:46)`

**Comment by carryonrewardless** [comment]
I have the same issue and also a newbie on node-red, openzwave. There are 3 instances of a file called test2.js on the FS but not the version found here:
[https://github.com/OpenZWave/node-openzwave-shared/blob/master/test2.js]
Where should a copy of this file be placed?

**Comment by carryonrewardless** [comment]
Answering my question & hopefully that for the OP, it turns out there is a copy of test2.js in this folder:

> /home/ubuntu/.node-red/node_modules/openzwave-shared
so that means you run the command 
`node test2.js `
in this folder.  The script assumes you have a zwave device plugged into the USB port.
