### ISSUE TITLE
Error on Windows Build: ..\src\utils.cc(331): error C2660: 'OZW::getValueIdDescriptor': function does not take 4 arguments 

### ISSUE THREAD

**Issue by Apollon77** [OpenZWave/node-openzwave-shared#211]
I use your zwave lib in a project and activated the build on appveyor-ci (great Windows CI tool!!) and my build get's killed by error:

..\src\utils.cc(331): error C2660: 'OZW::getValueIdDescriptor': function does not take 4 arguments [C:\projects\ioBroker.zwave\node_modules\openzwave-shared\build\openzwave_shared.vcxproj]

Full log:
https://ci.appveyor.com/project/Apollon77/iobroker-zwave/build/test-1/job/slv11x9i9h798r6h

How that can be fixed to get used on windows?

**Comment by Apollon77** [comment]
Any news here? Is anyone interested in a working windows version?

**Comment by Apollon77** [comment]
So I looked around in code a bit and The method getValueIdDescriptor is fdefined twice in utils.cc.

One time as
```
	std::string getValueIdDescriptor(OpenZWave::ValueID value) {
```
and one time as 
```
	std::string getValueIdDescriptor(uint8 node_id, uint8 class_id, uint8 instance, uint8 index) {
```

But I also found other issues:
..\src\utils.cc(65): error C2065: 'uint': undeclared identifier [C:\projects\ioBroker.zwave\node_modules\openzwave-shared\build\openzwave_shared.vcxproj]
265
..\src\utils.cc(65): error C2146: syntax error: missing ')' before identifier 'node_id' [C:\projects\ioBroker.zwave\node_modules\openzwave-shared\build\openzwave_shared.vcxproj]
266
..\src\utils.cc(65): error C2143: syntax error: missing ';' before '{' [C:\projects\ioBroker.zwave\node_modules\openzwave-shared\build\openzwave_shared.vcxproj]
267
..\src\utils.cc(65): error C2447: '{': missing function header (old-style formal list?) [C:\projects\ioBroker.zwave\node_modules\openzwave-shared\build\openzwave_shared.vcxproj]

ABer der Fehler ist scheinbar gefixt

**Comment by atrovato** [comment]
I still have this issues, did you fix it ? (as issue is closed)
