### ISSUE TITLE
High Power

### ISSUE THREAD

**Issue by japita-se** [OpenZWave/node-openzwave-shared#212]
Is it possible to set he high power parameter of this OZW function?
`http://openzwave.com/dev/classOpenZWave_1_1Manager.html#aa11faf40f19f0cda202d2353a60dbf7b`

**Comment by ekarak** [comment]
this argument is only used in the legacy mode to issue controller commands (`BeginControllerCommand`), and is not supported in newer versions of the OpenZWave API.  You can try building node-openzwave-shared against an old OpenZWave version so that you get that exposed to Javascript.
