### ISSUE TITLE
ApplicationSatus

### ISSUE THREAD

**Issue by japita-se** [OpenZWave/node-openzwave-shared#216]
Is the ApplicationSatus used/implemented in the wrapper?
Ref.:
[Application Statuts](https://github.com/OpenZWave/open-zwave/blob/master/cpp/src/command_classes/ApplicationStatus.cpp)

I mean, the controller can handle Appication Status Reports?
Moreover, is the Versione Class handled?
[Versione CC](http://www.openzwave.com/dev/Version_8cpp.html)

**Comment by ekarak** [comment]
As far as I see, _this is just another command class_; if the device node exposes a ValueID object that is related to this particular command class then I see no reason why you can't get the application status as with any other command class... 
Do you have an example on how this is used in other projects?
