### ISSUE TITLE
include mismatch in openzwave.hpp and openzwave home folder structure

### ISSUE THREAD

**Issue by emretapci** [OpenZWave/node-openzwave-shared#222]
The script in binding.gyp file assigns ...\AppData\Local\OpenZWave to variable OZW_HOME and include directory is therefore ...\AppData\Local\OpenZWave\include.

But in node-openzwave-shared\src\openzwave.hpp file, openzwave include references are like `#include "openzwave/Manager.h"`. So, `node-gyp rebuild` cannot find the include files.

**Comment by sogaani** [comment]
hi @emretapci.

I met same issue with windows. And I made pull request #219 to fix it. Can you review it?

Thanks.

**Comment by emretapci** [comment]
I think the better solution is to remove "openzwave/" prefixes in openzwave.hpp file \#include directives.

**Comment by sogaani** [comment]
@emretapci You are right.
I see binding.gyp again.
On Linux and Mac, binding.gyp add "**/include/openzwave/"  to include path.

I delete my pull request.

**Comment by Apollon77** [comment]
Is anyone able to continue here? A version buildable on windows would be awesome!!

**Comment by ekarak** [comment]
ok I've just pushed a new branch ( bugfix/issue#222-inclusion-paths ) that removes the paths from the #include stanzas, I'm now trying to build it on Appveyor. Apologies for the delay, I have no Windows dev environment.

**Comment by ekarak** [comment]
Version 1.4.3 just released. This includes the fix in #222 and adds Appveyor CI support for Windows builds.
