### ISSUE TITLE
Windowsd build error: Cannot open include file: 'openzwave/Manager.h'

### ISSUE THREAD

**Issue by Apollon77** [OpenZWave/node-openzwave-shared#223]
One former issue is fixed, but now:

see: https://ci.appveyor.com/project/Apollon77/iobroker-zwave/build/test-16/job/3eyvmlgbsmwxgr4p#L164

**Comment by AlCalzone** [comment]
related to https://github.com/OpenZWave/node-openzwave-shared/issues/222

**Comment by ekarak** [comment]
Version 1.4.3 just released. This includes the fix in #222 and adds Appveyor CI support for Windows builds.
