### ISSUE TITLE
smartlock - dealing with user codes

### ISSUE THREAD

**Issue by tomnguyenn** [OpenZWave/node-openzwave-shared#226]
Hi,

I'm having some issues trying to manipulate user codes for a Schlage BE469. I can create codes by assigning the codes as a buffer to the different instances in the 0x63 comclass but I cannot delete codes or display previously created codes. I have tried assigning an empty buffer to the same instance of a previously assigned code, but that does not delete it from the list of codes. Has anyone else had any luck?

**Comment by ekarak** [comment]
Resolving. Please do understand that this is an *issue tracking system* used for reporting bugs, and is not meant to be used for development guidance. Please use the gitter chatroom for questions to other developers.
