### ISSUE TITLE
Example Door Lock

### ISSUE THREAD

**Issue by Cloudhomebr** [OpenZWave/node-openzwave-shared#23]
Hi,

First of all, thanks you very much for creating this library! I'm from Brazil and waiting for some API like that.
Do yout have some example of DoorLock like Yale?
Thanks.

**Comment by ekarak** [comment]
I do not have any security devices like door locks. I think you could find some examples though from the official OpenZWave mailing lists though.

**Comment by ekarak** [comment]
Hey,
I've just added support for the latest OpenZWave that supports secure devices. I don't have access to a secure device so I can't really test it. Can you please update both your OpenZWave library and openzwave-shared and give it a try?

**Comment by Cloudhomebr** [comment]
Hi,
Thanks, work very fine on Yale Door Lock

Steps that i use:

1) Create a security key: https://www.random.org/cgi-bin/randbyte?nbytes=16&format=h
1) Alter and add the security key: /usr/local/etc/openzwave/options.xml uncoment Network Security Key (dont know if its necessary)
3) Start with de security key: 
var zwave = new ZWave({
    Logging: true,
    ConsoleOutput: true,
    NetworkKey: "0x5f, .... "
});
4) Remove the device from old network: zwave.removeNode();
5) Add the device to new network: zwave.addNode(homeid, true);
6) After add, teste comands:
zwave.setValue(nodeid, commandclass, instance, index, value);
zwave.setValue(3, 98, 1, 0, true); // To lock
zwave.setValue(3, 98, 1, 0, false); // To unlock

Thanks for the support.
