### ISSUE TITLE
Add support for secure inclusion (ie adding door locks)

### ISSUE THREAD

**Issue by g00dnatur3** [OpenZWave/node-openzwave-shared#24]
Hi,

Could you please update the library to expose the "addNode" function from the openzwave.

Please look here
`http://www.openzwave.com/dev/classOpenZWave_1_1Manager.html`

```
bool 	AddNode (uint32 const _homeId, bool _doSecurity=true)
 	Start the Inclusion Process to add a Node to the Network. The Status of the Node Inclusion is communicated via Notifications. Specifically, you should monitor ControllerCommand Notifications.
```

the ideal api would be `zwave.addNode(homeId, doSecurity)`

I think this would be easy to do, and would make the library support secure inclusion

Thank you

**Comment by ekarak** [comment]
hmm, I see the OpenZWave API has deprecated the 'BeginControllerCommand' call which you can currently use to add nodes (albeit I'm not sure if it also does secure inclusion too).
Thanks for the tip, I'll add this later this week.

**Comment by ekarak** [comment]
Please try out [the security branch I've just created.](https://github.com/OpenZWave/node-openzwave-shared/tree/security)
You need to install [my own fork of the OpenZWave library](https://github.com/ekarak/open-zwave) which contains a [vital patch for the pkg-config descriptor](https://github.com/OpenZWave/open-zwave/pull/668)
I've also added some crude documentation for it as well.

**Comment by ekarak** [comment]
The pull request I've committed to the upstream OpenZWave API has been just merged, as such I'm merging this into master. You should simply update (`git pull`) the latest OpenZWave from github, then test my latest code.

Issue resolved.
