### ISSUE TITLE
battery level

### ISSUE THREAD

**Issue by patryk-kawalarz** [OpenZWave/node-openzwave-shared#240]
How to get current battery level of any node?

**Comment by ekarak** [comment]
again., usage question in the bugfix forum. Short answer: Use an event handler on the relevant valueId for the battery level notification (command class 128 decimal)
```
var zwnode = context.global.openzwaveNodes[msg.payload.nodeid];
if (zwnode && msg.payload && msg.payload.cmdclass == 128) {
  return({"topic": "write", "payload": {"zwmsg": msg, "zwnode": zwnode}});
}
```
