### ISSUE TITLE
Is it possible to do firmware update over the air (OTA) with this module?

### ISSUE THREAD

**Issue by RadoslavMarinov** [OpenZWave/node-openzwave-shared#242]
Is it possible to do firmware update over the air (OTA) with this module? If yes, how?

**Comment by ekarak** [comment]
This is not the proper forum to ask this; this is a question whether the main OpenZWave ( C++ ) library will support this command class:
COMMAND_CLASS_FIRMWARE_UPDATE_MD | 0x7A | 122
I've just checked openzwave-master, and no support for this (yet! feel free to chip in..)
