### ISSUE TITLE
NodeID per class and not per node

### ISSUE THREAD

**Issue by Harel-M** [OpenZWave/node-openzwave-shared#247]
Hi,
I see in the example file (test2.js) that in the "nodes" array, the NodeID is specified per caommand class, and not once per node.
I would expect it will be mentioned for a node, similar to the manufacturer, product, type etc.
Is there a specific reason for it?
For example, upon a "node removed" even, I would run through the node array and remove the one with the relevant node ID, without scanning through the classes.

Can you share your view on this?
Thanks,

**Comment by Harel-M** [comment]
I think I figured it out... the nodeid will always be the node's index in the array. This is the reasons for all the null values, right?
Can a new node be inserted instead of a null, or will it always be added at the end of the array?

Thanks,

**Comment by ekarak** [comment]
test2.js is merely a script to show how one can use the information that the underlying OpenZWave library provides. Therefore its not mandatory to use its data representation schema as-is, you can adapt it to your needs.
