### ISSUE TITLE
setLevel command does not work

### ISSUE THREAD

**Issue by stockmopar** [OpenZWave/node-openzwave-shared#25]
I had to use SetValue to set my dimmers level.  It appears that "setLevel" is missing from openzwave.cc .

Not a big deal but might want to update README-api.md to not advertise the setLevel command.

**Comment by ekarak** [comment]
You're right - I've forgotten about setNodeLevel completely, I've also
misnamed a couple of other ancillary calls as well. I've now added these
but I'll publish those later as I need to update the docs as well.

Thanks for the bug report.

2015-10-06 21:59 GMT+03:00 stockmopar <notifications@github.com>:

> I had to use SetValue to set my dimmers level. It appears that "setLevel"
> is missing from openzwave.cc .
>
> Not a big deal but might want to update README-api.md to not advertise the
> setLevel command.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenZWave/node-openzwave-shared/issues/25>.
>



-- 
Elias Karakoulakis
Electrical & Computer Engineer NTUA Athens
Msc Information Systems, AUEB Athens
KNX Advanced Partner

**Comment by stockmopar** [comment]
I tried the new SetNodeLevel command you implemented but it doesn't appear to be working.  That might possibly for my specific device (2gig WD500Z-1 Z-Wave Wall Dimmer).  The command that did work was: zwave.setValue(<nodeid>,<commandclass>,<instance>,<index>,<level>);

**Comment by ekarak** [comment]
It doesn't work for my only dimmer either. It seems OpenZWave is directly setting the level value on the BASIC command class, which in case of my dimmer is the ON/OFF class (and I guess for your dimmer too):
```//-----------------------------------------------------------------------------
// <Node::SetLevel>
// Helper method to set a device's basic level
//-----------------------------------------------------------------------------
void Node::SetLevel
(
                uint8 const _level
)
{
        // Level is 0-99, with 0 = off and 99 = fully on. 255 = turn on at last level.
        uint8 adjustedLevel = _level;
        if( ( _level > 99 ) && ( _level < 255 ) )
        {
                adjustedLevel = 99;
        }

        if( Basic* cc = static_cast<Basic*>( GetCommandClass( Basic::StaticGetCommandClassId() ) ) )
        {
                cc->Set( adjustedLevel );
        }
}
```

Thanks for the tip. I guess I have to update the docs :)
Resolving issue.

**Comment by ekarak** [comment]
For the record, the SetValue command I use for my dimmer is:    ```zwave.setValue(5,38,1,0,50);```
where 
5: zwave node ID, 
38: CommandClassMultilevel (Dimmers)
1, 0: instance, index
50: level (50%)

**Comment by Fishwaldo** [comment]
Any of the Node:Set* methods are going to be very hit and miss if they work. They rely on the device "correctly" supporting the Basic CC, and it being discovered correctly (which isn't always the case).

If your updating the docs, I'd say in big RED LETTERS - DONT USE THESE FUNCTIONS! (I will update the OZW code with roughly the same message soon)

**Comment by Mirarkitty** [comment]
With Basic::Set rewritten like this, it works fine for me:

void Basic::Set
(
        uint8 const _level
)
{
        // This may look like a long winded way to do this, but
        // it ensures that all the proper notifications get sent.
        if( ValueByte* value = static_cast<ValueByte*>( GetValue( 1, 0 ) ) )
        {
                value->Set( _level );
                value->Release();
        }
        else
        {
                Log::Write( LogLevel_Info, GetNodeId(), "Basic::Set - Setting node %d to level %d", GetNodeId(), _level );
                Msg* msg = new Msg( "BasicCmd_Set", GetNodeId(), REQUEST, FUNC_ID_ZW_SEND_DATA, true );
                msg->SetInstance( this, 1 );
                msg->Append( GetNodeId() );
                msg->Append( 3 );
                msg->Append( GetCommandClassId() );
                msg->Append( BasicCmd_Set );
                msg->Append( _level );
                msg->Append( GetDriver()->GetTransmitOptions() );
                GetDriver()->SendMsg( msg, Driver::MsgQueue_Send );
        }
}

Seems like Basic can't get a Value from nothing. This will force a Basic Set. I'm not sure about instance, I hardcoded it to 1 above.
