### ISSUE TITLE
How to get manufacturer info from battery powered device

### ISSUE THREAD

**Issue by reneklootwijk** [OpenZWave/node-openzwave-shared#251]
I never get the manufacturer info from battery powered devices and they do not react on the refreshNodeInfo command. Even sending a refreshNodeInfo command when receiving an awake event from the device does not do anything. 

I never receive 'node ready' events, only 'value changed' events.

Does anyone have any clue how I can obtain manufacturer info? I need this to now how to treat the device and sub devices.

**Comment by Harel-M** [comment]
I have NEO COOLCAM Z-wave Door/Window Sensor and I do get the manufacturer info.
It received when the devices is waking up, so if I start the controller app I don't see the info, but when waking the devices by pressing its button (or just waiting for it to wake up) I get the info and it is updated in the nodes array.
Do you get the nop frame from your devices when it's waking up? the info is received after the nop...

**Comment by reneklootwijk** [comment]
You are right. Don't know why I did not see that before.
