### ISSUE TITLE
Ping device

### ISSUE THREAD

**Issue by ptorrent** [OpenZWave/node-openzwave-shared#252]
Hello there !

Is there a way to know when a device is deconnected (battery down etc..) ?

Thanks for support !

**Comment by Harel-M** [comment]
Battery powered devices shuts down their radio when they sleep, so you cannot communicate with them at all.
When they wake up (the time between the wake ups is usually configurable on the device) they will send a notification to the controller to know they are alive.
On some point if no update is received they should be changed from alive to dead (I don't know what is the criteria for this.. :)).

on power connected devices I guess you can send heal command and if they are OK you should get a response immediately... maybe there are also other commands you can send, need to check the standard.

**Comment by ptorrent** [comment]
Thanks for your answer. 

How to change the Wake-up Interval value ? 

I do not understand this function 

```javascript
zwave.setConfigParam(nodeId, paramId, paramValue, <sizeof paramValue>);
```
What's the paramId argument ?

**Comment by Harel-M** [comment]
Each device has configuration options (listed in it's user manual).
Every configuration has a parameter ID and accepted values.
Look in your device's manual what is the parameter ID for the wake up interval configuration, and set it accordingly with the setConfigParam function.

**Comment by ekarak** [comment]
thank you @Harel-M ,resolving
