### ISSUE TITLE
Name/Location deleted on restart

### ISSUE THREAD

**Issue by Harel-M** [OpenZWave/node-openzwave-shared#253]
According to the documentation, the the node's name and location are stored on the device itself.
But after I reset my node.js controller application I don't see this values anymore.

I tried fetching it with zwave.getNodeName(nodeid) and zwave.getNodeLocation(nodeid) - After setting the name and location I get the values, but after stop and starting the application the values are empty.

I also see nothing in the openZwave log after calling the getNodeName() and getNodeLocation() functions... (the set function results in one line NodeNaming in the log).

Anyone have any experience with this values?

Thanks,

**Comment by ekarak** [comment]
Apologies for the confusion, the readme needs changing here. 

The *node type and manufacturer info* are values fetched from the device when the node is first added to the network, and this happens only once. Its name and location are user-definable settings that *some* devices are able to store and retrieve, so the OZW library caches this in its node data (effectively the zwcfg-xxx.xml file that the underlying OpenZWave library uses to persist the ZWave network to disk). 
Therefore you need to 1) define the path to that file using the `UserPath` config property and 2) make sure to call `writeConfig()` to store that file before you exit your Node.JS app.

**Comment by ekarak** [comment]
https://github.com/OpenZWave/node-openzwave-shared/commit/01f49f4da5e5b350373adc8821cf2774c27e6b16
