### ISSUE TITLE
Changing poll intensity no effect

### ISSUE THREAD

**Issue by ptorrent** [OpenZWave/node-openzwave-shared#255]
Hello,

I'm trying to change poll intensity for a specific nodeValue : 

![image](https://user-images.githubusercontent.com/6083644/47886178-e701f480-de38-11e8-8b07-2b2d857a1eee.png)

```javascript
if(zwave.isPolled({value})){
	zwave.setPollIntensity({value}, pollingIntensity);			
}
else {
	zwave.enablePoll({value}, pollingIntensity);
}		
```
And if I disablePoll on the value it's work: 

![image](https://user-images.githubusercontent.com/6083644/47886309-8e7f2700-de39-11e8-86fa-ea4a535df8a4.png)

Is there something I did not understand?

Thanks for support.

**Comment by ekarak** [comment]
you wouldn't by any chance mean using `setPollInterval` instead?

**Comment by ekarak** [comment]
Anyway, I'm marking this as resolved as this issue tracker isn't the place to raise support requests for the core OZW library usage, but only for bugs related to NodeJS integration. 
BTW, This post seems to explain more:
https://community.home-assistant.io/t/z-wave-polling-questions-answered/2394
