### ISSUE TITLE
Eurotronics Spirit Thermostat - Thermostat Mode not changed

### ISSUE THREAD

**Issue by nezteew** [OpenZWave/node-openzwave-shared#257]
Hi,

there was already an issue about my problem in the openzwave repo (https://github.com/OpenZWave/open-zwave/issues/1559).

Me and some others in the german iobroker forum have the same problem:
We can not set the thermostat mode of the Eurotronics Spirit Thermostat using iobroker.

I can set it successfully using the OpenZWave Control Panel, so I guess it is implemented there correctly (?).

Since the reporter in the issue mentioned above has the same problem using nodejs directly, I guess it is a problem in the node-openzwave-shared wrapper.

This is the description in the eur_spiritz.xml configuration file of the device:

`
    <CommandClass id="64">
        <Instance index="1" />
        <Value type="list" genre="user" instance="1" index="0" label="Mode">
            <Help>
                Off: No heating, only frost protection.
                Heat: Room temperature will be kept at the configured setpoint.
                Heat Eco: Energy save heating mode. Room temperature will be lowered to the configured eco setpoint in order to save energy.
                Full Power: Full power heating. This mode is left automatically after 5 minutes.
                Manufacturer Specific: Direct valve control mode. The valve opening percentage can be controlled using the switch multilevel command class.
            </Help>
            <Item label="Off" value="0" />
            <Item label="Heat" value="1" />
            <Item label="Heat Eco" value="11" />
            <Item label="Full Power" value="15" />
            <Item label="Manufacturer Specific" value="31" />
        </Value>
        <SupportedModes>
            <Mode index="0" label="Off" />
            <Mode index="1" label="Heat" />
            <Mode index="11" label="Heat Eco" />
            <Mode index="15" label="Full Power" />
            <Mode index="31" label="Manufacturer Specific" />
        </SupportedModes>
    </CommandClass>`

Any ideas?
Let me know if you need more information.
I'm quite new to iobroker and zwave, but if you explain what you need, I will try to provide the information.

**Comment by Borck** [comment]
m_edas posted a [workaround](https://forum.iobroker.net/viewtopic.php?p=200170#p200170) in a german forum that also works for me. Just edit the raw data of the heat mode node as descriped.

If it turns out as a solution, I think this file should be fixed.
https://github.com/OpenZWave/open-zwave/blob/master/config/eurotronic/eur_spiritz.xml

**Comment by nezteew** [comment]
Great, the workaround works for me in iobroker.
How can this be transferred to the xml file you mentioned?

**Comment by ekarak** [comment]
resolving
