### ISSUE TITLE
First Step Report

### ISSUE THREAD

**Issue by cflurin** [OpenZWave/node-openzwave-shared#26]
Hi, 
Just to inform about my first experience.
I've successfully installed node-openzwave-shared on a RPI 2 running Jessie and node v4.1.1.
I had Z-Way already installed, so to access RaZberry I only had to define a symlink.
```sh
sudo ln -s /dev/ttyAMA0 /dev/ttyUSB0
```
So far I tested node-openzwave-shared using test2.js.

**Comment by ekarak** [comment]
Hi,
you can tweak the paths in the zwave.connect() calls instead. 
Thanks for the status report!
