### ISSUE TITLE
Trying to get a Nodon Wall Switch to work

### ISSUE THREAD

**Issue by CliffS** [OpenZWave/node-openzwave-shared#265]
I have added a Nodon Wall Switch to a working network.  I have been trying to configure it simply to fire a `value changed` event when a button is pressed.  It is successfully added in Gateway Mode.

After running a scan, the first time I press a button, I get a `notification` event for the node: "node awake", followed by `value changed` events for Powerlevel, Timeout and Battery Level.  I then get a `node ready` event.

The next press gives me a "node sleep" notification and further presses simply give "node awake" and "node sleep" notifications.

I have tried setting values to a simple setup:

```coffeescript
      zwave.setValue 11, 39, 1, 0, 3
      zwave.setValue 11, 112, 1, 1, 1
      zwave.setValue 11, 112, 1, 2, 1
      zwave.setValue 11, 112, 1, 3, 1
      zwave.setValue 11, 112, 1, 4, 1
      zwave.setValue 11, 112, 1, 5, 2
      zwave.setValue 11, 112, 1, 6, 1
      zwave.setValue 11, 112, 1, 7, 2
      zwave.setValue 11, 112, 1, 8, 3
```

These values do not seem to "stick"; they are not in the ozwcache file after saving and exiting.  Meanwhile, I don't get any `value changed` events when the buttons are pressed.

Can anyone help me by pointing out what I'm doing wrong?

**Comment by robertsLando** [comment]
Try to enable poll of the value you want updates from.

`zwave.enablePoll({valueId}, intensity);`
