### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by glitchracer** [OpenZWave/node-openzwave-shared#274]
Hi, everyone I'm trying to install OpenZWave at Node-Red but it fails.

```
> openzwave-shared@1.4.7 preinstall /home/pi/.node-red/node_modules/openzwave-shared
> node lib/install-ozw.js

> openzwave-shared@1.4.7 install /home/pi/.node-red/node_modules/openzwave-shared
> node-gyp rebuild

find: ‘/usr/*/include’: No such file or directory
gyp: Call to 'find /usr/*/include -name ZWSecurity.h | wc -l' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Linux 4.14.98-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/.node-red/node_modules/openzwave-shared
gyp ERR! node -v v11.10.1
gyp ERR! node-...
```

Console also failed:
`npm install openzwave-shared`

Can anyone help me please?!

**Comment by sjorge** [comment]
What does ```find /usr/*/include -name ZWSecurity.h | wc -l``` and ```find /usr/*/include -name ZWSecurity.h``` return?

**Comment by glitchracer** [comment]
No such file or directory

**Comment by sjorge** [comment]
Aha! That is probably why it is failing.

mkdir -p /usr/dummy/include

Should work around it,  but bindings.gyp probably needs updating then.

**Comment by carryonrewardless** [comment]
> mkdir -p /usr/dummy/include

I used this on a HassIO installation but it failed. Nothing got installed in the created directory.  I guess HassIO is a special case tho.
Any clues?

**Comment by robertsLando** [comment]
@sjorge could you help with that?

**Comment by GetUpdate** [comment]
me2  same problem  Hass.io + Node Red 

...
find: ‘/usr/*/include’: No such file or directory
gyp: Call to 'find /usr/*/include -name ZWSecurity.h | wc -l' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 


Any clues? 
Tx in advance
