### ISSUE TITLE
1.6 Update - ValueID index param changed to uint16_t (node-openzwave-shared)

### ISSUE THREAD

**Issue by Fishwaldo** [OpenZWave/node-openzwave-shared#282]
Per the OZW 1.6 Release Notes, [the index of all ValueID's has changed from a unt8_t to a uint_16_t](https://github.com/OpenZWave/open-zwave/wiki/OpenZWave-1.6-Release-Notes#valueid-index-range) 

Need to ensure no changes are required

**Comment by ekarak** [comment]
implemented in feature/295-new-notification-types

**Comment by ekarak** [comment]
mr #305 merged, resolving
