### ISSUE TITLE
1.6 Update - Handling Labels (node-openzwave-shared)

### ISSUE THREAD

**Issue by Fishwaldo** [OpenZWave/node-openzwave-shared#283]
Per the OZW 1.6 Release Notes, [all labels or user visible strings are dynamic and can be localized.](https://github.com/OpenZWave/open-zwave/wiki/OpenZWave-1.6-Release-Notes#localization-of-user-visible-strings)

Need to check no hard-coded string comparisons are made on things like ValueID's (eg, GetLabel() == "Switch" type calls). Instead you should be using the CommandClass, and Index values from a ValueID to determine what the ValueID represents. 

Please close this if its not relevant.

**Comment by robertsLando** [comment]
It's ok no hardcoded string compare is present
