### ISSUE TITLE
1.6 Update - Central Scene Command Class (node-openzwave-shared)

### ISSUE THREAD

**Issue by Fishwaldo** [OpenZWave/node-openzwave-shared#286]
As per the OZW 1.6 Release Notes, [The Central Scene CommandClass has undergone a complete rewrite](https://github.com/OpenZWave/open-zwave/wiki/OpenZWave-1.6-Release-Notes#central-scene-commandclass)

Need to confirm no changes are required.

**Comment by robertsLando** [comment]
@Fishwaldo if scenes are auto discovered as valueid as described there should be nothing to change here
