### ISSUE TITLE
1.6 Update - Associations (node-openzwave-shared)

### ISSUE THREAD

**Issue by Fishwaldo** [OpenZWave/node-openzwave-shared#289]
per the OZW 1.6 Release Notes, [a new method, IsMultiInstance has been created](https://github.com/OpenZWave/open-zwave/wiki/OpenZWave-1.6-Release-Notes#associations)

Need to export that for Applications.

**Comment by nouknouk** [comment]
As my pull request has been merged, I think this issue should be closed.
