### ISSUE TITLE
Fails to do secure pairing

### ISSUE THREAD

**Issue by g00dnatur3** [OpenZWave/node-openzwave-shared#29]
Hello,

Thank you for adding the AddNode() api.

Now, some background, I have a lock that works with the python-openzwave library, it does secure pairing, and i can control it.

However, from the looks of this, it seems as though this library fails to read the options.xml

If you read here:

https://github.com/OpenZWave/open-zwave/wiki/Adding-Security-Devices-to-OZW

The options.xml needs to be updated to allow for a NetworkKey config.

I will do more testing and post a log here.

**Comment by ekarak** [comment]
You could try passing the key into the addon constructor maybe?

Στις 13 Οκτωβρίου 2015 3:00:59 π.μ. EEST, ο/η g00dnatur3 <notifications@github.com> έγραψε:
>Hello,
>
>Thank you for adding the AddNode() api.
>
>Now, some background, I have a lock that works with the
>python-openzwave library, it does secure pairing, and i can control it.
>
>However, from the looks of is, it seems as though this library fails to
>read the options.xml
>
>If you read here:
>
>https://github.com/OpenZWave/open-zwave/wiki/Adding-Security-Devices-to-OZW
>
>The options.xml needs to be updated to allow for a NetworkKey config.
>
>I will do more testing and post a log here.
>
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/OpenZWave/node-openzwave-shared/issues/29

-- 
Sent from my mobile device with K-9 Mail. Please excuse my brevity.

**Comment by g00dnatur3** [comment]
Ok I got the secure pairing is working when I do it thru the constructor:

var networkKey = new Array(16);

for (var i=0; i<16; i++) {
	networkKey[i]=0xFF;
}

var zwave = new ZWave({
    Logging: true,     // disable file logging (OZWLog.txt)
    ConsoleOutput: true, // enable console logging
    NetworkKey: networkKey
});

I push on thru and try to control the lock.

Thanks for your help

**Comment by ekarak** [comment]
Although I have no secure devices, I think I know what's happening: You're setting up your array as a series of Numbers, not Strings. This should have caused OpenZWave to emit an error from the following snippet from Driver.cpp:
```c++
    for (std::vector<std::string>::iterator it = elems.begin(); it != elems.end(); it++) {
            if (0 == sscanf(OpenZWave::trim(*it).c_str(), "%x", &tempkey[i])) {
                    Log::Write(LogLevel_Warning, "Cannot Convert Network Key Byte %s to Key", (*it).c_str());
                    OZW_FATAL_ERROR(OZWException::OZWEXCEPTION_SECURITY_FAILED, "Failed to Convert Network Key");
```
Please try passing in a String instead:
```js
var zwave = new ZWave({
  Logging: true,
  ConsoleOutput: true,
  NetworkKey: "0xCA,0xFE,0xBA,0xBE,.... " // <16 bytes total>
});

**Comment by ekarak** [comment]
https://www.random.org/cgi-bin/randbyte?nbytes=16&format=h
should get a nice fresh set of hex numbers. Just prefix them with "0x" (zero-x) and join them with commas in one unique string.
Thanks for this, I've just updated the documentation as well.

**Comment by g00dnatur3** [comment]
In my initial code I did do that, but i got this error

```
var zwave = new ZWave({
    Logging: true,     // disable file logging (OZWLog.txt)
    ConsoleOutput: true, // enable console logging
    //NetworkKey: networkKey
    NetworkKey: "0x02, 0x02, 0x03, 0x03, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F, 0x10"
});
```

```
Initialising OpenZWave (1.3.0) binary addon for Node.JS.
	ZWave device db  : /usr/local/etc/openzwave
	User settings    : /home/developer/workspace/zwavedemo/node_modules/openzwave-shared/build/Release/../../
	Option Overrides : --Logging true --ConsoleOutput true --NetworkKey 0x02, 0x02, 0x03, 0x03, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F, 0x10
	OpenZWave Security API is ENABLED
2015-10-15 13:47:08.608 Always, OpenZwave Version 1.3.0 Starting Up
2015-10-15 13:47:08.609 Info, Setting Up Provided Network Key for Secure Communications
2015-10-15 13:47:08.609 Warning, Invalid Network Key. Does not contain 16 Bytes - Contains 1
2015-10-15 13:47:08.609 Warning, Raw Key: 0x10
2015-10-15 13:47:08.609 Warning, Parsed Key:
2015-10-15 13:47:08.609 Warning, 1) - 0x10
2015-10-15 13:47:08.609 Error, Exception: Driver.cpp:6683 - 103 - Failed to Read Network Key
Error: Driver.cpp:6683 - Failed to Read Network Key
```

**Comment by g00dnatur3** [comment]
This code works:

```
var zwave = new ZWave({
    Logging: true,     // disable file logging (OZWLog.txt)
    ConsoleOutput: false, // enable console logging
    //NetworkKey: networkKey
    NetworkKey: "0x02,0x02,0x03,0x03,0x05,0x06,0x07,0x08,0x09,0x0A,0x0B,0x0C,0x0D,0x0E,0x0F,0x10"
});
```

But this code will not work:

```
var zwave = new ZWave({
    Logging: true,     // disable file logging (OZWLog.txt)
    ConsoleOutput: false, // enable console logging
    //NetworkKey: networkKey
    NetworkKey: "0x02, 0x02, 0x03, 0x03, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F, 0x10"
});
``

I had tried to use the networkKey as a string in the beginning, but i was having the spaces between values and thats when tried using the hex numbers in an array instead.

**Comment by nayrnet** [comment]
here is a one liner for generating random security key via pwgen:

 pwgen -s 16 1| od -A n -t x1|sed 's/ /,0x/g'|sed 's/,//'|sed 's/0x0a//'
