### ISSUE TITLE
1.6 Update - BeginControllerCommand Depreciated (node-openzwave-shared)

### ISSUE THREAD

**Issue by Fishwaldo** [OpenZWave/node-openzwave-shared#290]
Per the OZW 1.6 Release Notes, [BeginControllerCommand has been depreciated and replaced with a number of dedicated calls instead](https://github.com/OpenZWave/open-zwave/wiki/OpenZWave-1.6-Release-Notes#controller-management)

Please refer to the [See Also section here](http://openzwave.com/dev/classOpenZWave_1_1Manager.html#aa11faf40f19f0cda202d2353a60dbf7b) for a list of new manager methods to implement.

**Comment by ekarak** [comment]
This is already being done, BeginControllerCommand is only being exposed when compiling against legacy OZW builds
