### ISSUE TITLE
1.6 Update - Device MetaData (node-openzwave-shared)

### ISSUE THREAD

**Issue by Fishwaldo** [OpenZWave/node-openzwave-shared#291]
Per the OZW 1.6 Release Notes - [MetaData about individual devices is now available](https://github.com/OpenZWave/open-zwave/wiki/OpenZWave-1.6-Release-Notes#device-metadata-information)

Need to export the [GetMetaData](http://openzwave.com/dev/classOpenZWave_1_1Manager.html#aca62303fb4ff70de821a9d0fcc683b1c), [GetChangeLog](http://openzwave.com/dev/classOpenZWave_1_1Manager.html#a163dcb56746025c5b9f7a799084282b8) and [NodeMetaData Enum](http://openzwave.com/dev/classOpenZWave_1_1Node.html#ac9196345e8f139a6e9e81e1480f4ff2a)

In addition, the Device Database includes pictures of each device. The path to the picture is exported via the MetaData_ProductPic  enum above. May want to normalize the path for applications.

**Comment by ekarak** [comment]
Code change is ready:
https://github.com/OpenZWave/node-openzwave-shared/tree/feature/291-device-metadata
but depends on https://github.com/OpenZWave/open-zwave/pull/1845

**Comment by mlankamp** [comment]
Created a PR : https://github.com/OpenZWave/node-openzwave-shared/pull/336
