### ISSUE TITLE
1.6 Update - SendRawData Method (node-openzwave-shared) 

### ISSUE THREAD

**Issue by Fishwaldo** [OpenZWave/node-openzwave-shared#294]
As per the OZW 1.6 Release Notes, [SendRawData method has been added](https://github.com/OpenZWave/open-zwave/wiki/OpenZWave-1.6-Release-Notes)

Need to update to expose this method.

**Comment by ekarak** [comment]
https://github.com/OpenZWave/node-openzwave-shared/pull/306
