### ISSUE TITLE
1.6 Update - New Notification Types (node-openzwave-shared)

### ISSUE THREAD

**Issue by Fishwaldo** [OpenZWave/node-openzwave-shared#295]
As Per the OZW 1.6 Release Notes, [the Notification class has some new types and a UserAlert type that should be displayed to the user](https://github.com/OpenZWave/open-zwave/wiki/OpenZWave-1.6-Release-Notes#notifications)

Need to update to support these.

**Comment by ekarak** [comment]
feature/295-new-notification-types

**Comment by ekarak** [comment]
MR #305 merged
