### ISSUE TITLE
1.6 Update - Depreciated Features (node-openzwave-shared)

### ISSUE THREAD

**Issue by Fishwaldo** [OpenZWave/node-openzwave-shared#296]
As per the OZW 1.6 Release Notes, [Several methods have been depreciated](https://github.com/OpenZWave/open-zwave/wiki/OpenZWave-1.6-Release-Notes#deprecated-featuresmethods)

Need to remove these calls to OZW.

**Comment by ekarak** [comment]
added preprocessor macro to mask deprecated API calls. Users can still override this at compilation time and get the calls back if necessary
