### ISSUE TITLE
1.6 Update - Support BitSet ValueID (node-openzwave-shared) 

### ISSUE THREAD

**Issue by Fishwaldo** [OpenZWave/node-openzwave-shared#297]
Per the OZW 1.6 Release Notes on the new [BitSet ValueID](https://github.com/OpenZWave/open-zwave/wiki/OpenZWave-1.6-Release-Notes#bitset-valueid)

Need to ensure that the BitSet ValueID is supported. 

Manager References:
[Manager::GetValueAsBitSet (ValueID const &_id, uint8 _pos, bool *o_value)](http://openzwave.com/dev/classOpenZWave_1_1Manager.html#a8d056bcf6b8bfcfc9ec1ec48377b0b03)
[SetValue (ValueID const &_id, uint8 _pos, bool const _value)](http://openzwave.com/dev/classOpenZWave_1_1Manager.html#a4c2e91010a20e5319e11c620de7e3ddf)
[GetBitMask (ValueID const &_id, int32 *o_mask)](http://openzwave.com/dev/classOpenZWave_1_1Manager.html#a80edc0086f387233378d2b7c85010f48)
[GetBitSetSize (ValueID const &_id, uint8 *o_size)](http://openzwave.com/dev/classOpenZWave_1_1Manager.html#a44acbf3a0e44619e8b88421a9e13bfe7)

**Comment by ekarak** [comment]
done

**Comment by sjorge** [comment]
This doesn't seem to be working yet via the node bindings, Robort gave it a go in https://github.com/OpenZWave/node-openzwave-shared/tree/feature/BitSet, but it just makes node segfault for me when it tries to load the initial values at startup.
