### ISSUE TITLE
AddNode() get added node informations

### ISSUE THREAD

**Issue by pascal-mormin** [OpenZWave/node-openzwave-shared#298]
Hi, 
My  question in focused on the way to add a node, i know there is some issues treating about this subject but i can't find exactly what i want.

I have to do something like  @jodyalbritton said in #224 

```
// POST to add a node
router.route('/commands/add')
  .post(function (req, res, next) {
    nodeServer.zwave.addNode()
    console.log('adding')
    res.send(200)
  })
// POST to remove a node
router.route('/commands/remove')
  .post(function (req, res, next) {
    nodeServer.zwave.removeNode()
    console.log('removing')
    res.send(200)
  })
```

but i want to know if there is a way, when i execute zwave.addNode(), to get  just added node informations ?

**Comment by robertsLando** [comment]
Add node starts the inclusion mode in the controller, if the node is discovered you will get the feedback on `nodeAdded` event callback and node info in `nodeReady` event callback and

**Comment by pascal-mormin** [comment]
@robertsLando Thank you for your reply. I now understand how this works.
