### ISSUE TITLE
Aeotec Smart Dimmer 6 Not Turning Load On/Off

### ISSUE THREAD

**Issue by scottbrumley** [OpenZWave/node-openzwave-shared#303]
Hi,

I'm using this project with the Node Red project (https://flows.nodered.org/node/node-red-contrib-openzwave-am).  I was able to turn the light on the Smart Dimmer on and off, but not the load with it.  Any ideas where to look to fix this?

**Comment by ekarak** [comment]
please note, this is not the place to ask usage questions. Please use the chatroom, but the best place to find answers is the main OpenZWave mailing list:
https://groups.google.com/forum/#!forum/openzwave
