### ISSUE TITLE
npm install failing: Mac OSX El Capitan

### ISSUE THREAD

**Issue by masterokami** [OpenZWave/node-openzwave-shared#308]
npm install fails on Mac OS X El Capitan

`bin/sh: ldconfig: command not found`
`gyp: Call to 'ldconfig -p | grep 'libopenzwave.so ' | awk '{print $4}' | xargs nm -g --demangle |grep OpenZWave::Value::GetTypeNameFromEnum | wc -l' returned exit status 0 while in binding.gyp. while trying to load binding.gyp`

**Comment by nouknouk** [comment]
had the same yesterday on one linix distro (debian) and not another (mint)
if i remember well, check /usr/sbin and /sbin are in your path environment, where your ldconfig executable is located.

**Comment by Pierre-Gilles** [comment]
I have the same issue since 1.5.1! 

ldconfig doesn't exist on MacOS

https://github.com/protocolbuffers/protobuf/issues/2570#issuecomment-325345373

**Comment by ekarak** [comment]
my fault, sorry... I just committed a fix, can you please try again?
oh and if anyone knows a free OSX CI/CD service for open source projects, do let me know...

**Comment by Pierre-Gilles** [comment]
Thanks for your quick reply!

I don't manage to do `npm install` on master, here is the error I get: (it's working with v1.4.8)

<img width="629" alt="Screenshot 2019-06-21 at 14 20 28" src="https://user-images.githubusercontent.com/7365207/59902069-c6ba9080-942f-11e9-8761-24513e9bf52c.png">

**Comment by ekarak** [comment]
ok, a fix for XCode flag for C++ exceptions was just merged. This should do the trick.
