### ISSUE TITLE
How to handle OPENZWAVE_SCENES preprocessor

### ISSUE THREAD

**Issue by robertsLando** [OpenZWave/node-openzwave-shared#328]
I saw that you have used `OPENZWAVE_SCENES` preoprocessor to include/exclude scenes management in the build but you never set it on `binding.gyp` file. How about this? Could we enable it at least for `scene_event` ? In zwave2mqtt I have set up a custom scenes management but some nodes need to receive `scene_event`, how can I handle this? Could we enable it by default or maybe add a gyp preprocessor? 

@Fishwaldo @ekarak

**Comment by Fishwaldo** [comment]
1.4 published changes to the SceneActivation CC class via Notifications. 
1.6 changes that to ValueID’s as per all the other CC, and the Notification is depreciated (But still there till I remove it)

**Comment by robertsLando** [comment]
@Fishwaldo so how do I get a scene event in 1.6?

**Comment by Fishwaldo** [comment]
It’s a ValueID for each scene detected on the node. (Specifically a ValueList with each entry representing single/double taps etc. )
