### ISSUE TITLE
NodeNeighborUpdate failed

### ISSUE THREAD

**Issue by cburghardt** [OpenZWave/node-openzwave-shared#339]
I have several Neo power plugs. For those the requestNodeNeigborUpdate fails:

command feedback for node 31: state: "The controller is communicating with the other device to carry out the command", error: "No error", helpmsg: "RequestNodeNeighborUpdate ControllerCommand - InProgress"
command feedback for node 31: state: "The command has failed", error: "No error", helpmsg: "RequestNodeNeighborUpdate ControllerCommand - Failed"

It works for other devices but all the ones from Neo CoolCam don't work. Is that an issue of the device or the library?

**Comment by ekarak** [comment]
Hi, 
this is a message reported from the underlying C++ library and does not indicate an issue with node-openzwave (the Node.js adapter). This message implies (if I'm not mistaken) that the device doesn't respond to that control request and isn't capable of routing.
