### ISSUE TITLE
openzwave-shared controls wall-switch, but the wall-switch buttons do nothing.

### ISSUE THREAD

**Issue by glhasson** [OpenZWave/node-openzwave-shared#343]
Used the test2.js that comes with openzwave-shared as a template for a simple program to control lights. The program controls the on and off of the lights perfectly. However, manual control of the lights using the buttons on the wall-switch fails to do anything. The program does not receive a message from the wall-switch that the buttons have been pressed, and the relays within the wall-switch do not change state.

Platform: Raspberry Pi 3, Ubuntu 16.04.6 LTS (GNU/Linux 4.14.27-v7+ armv7l)
OpenZwave Version 1.6-902-g9cdff83-dirty compiled on this Raspberry Pi.
openzwave-shared-1.5.6
Controller: /dev/ttyACM0 Aeotec Z-Stick Gen5
Wall-Switch: Wenzhou TKB Control System TZ57 Two channel switch, type=0311, id=0203

**Comment by velocityzen** [comment]
You have to set reporting parameter on the switch. Try to ask technical support for the parameter.

**Comment by glhasson** [comment]
Thank you for the guidance!
