### ISSUE TITLE
Build error on raspberry pi

### ISSUE THREAD

**Issue by jarvih** [OpenZWave/node-openzwave-shared#344]
Im tying to install zwave2mqtt but got this error evertime.
Also same error if i try to install node-red-contrib-openzwave-am which have dependency for node-openzwave-shared.

root@raspberrypi:~/ZWave2MQTT# npm install openzwave-shared

> openzwave-shared@1.5.6 preinstall /root/ZWave2MQTT/node_modules/openzwave-shared
> node lib/install-ozw.js

internal/modules/cjs/loader.js:775
    throw err;
    ^

Error: Cannot find module '/root/ZWave2MQTT/node_modules/openzwave-shared/lib/install-ozw.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! openzwave-shared@1.5.6 preinstall: `node lib/install-ozw.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the openzwave-shared@1.5.6 preinstall script.

**Comment by robertsLando** [comment]
Try with latest version of zwave2mqtt
