### ISSUE TITLE
Multi channel get end-points?

### ISSUE THREAD

**Issue by cburghardt** [OpenZWave/node-openzwave-shared#346]
This might be more of a question than an issue. ozwave supports the isMultiInstance since 1.6 and your library also supports adding and removing associations with an instance. However I am struggling to find out how to request the supported end-points of the device via your library. Basically I need the results of the inquiry data for multichannel/multi instance.

**Comment by robertsLando** [comment]
You mean this: https://github.com/OpenZWave/node-openzwave-shared/pull/349

**Comment by cburghardt** [comment]
I am sorry but this PR has nothing to do with it. It provides existing associations. But how do I find out which end-points are supported by a device?
