### ISSUE TITLE
OPENZWAVE16_DEPRECATED gyp flag broken install

### ISSUE THREAD

**Issue by robertsLando** [OpenZWave/node-openzwave-shared#355]
@ekarak There are several bug on `openzwave-scenes.cpp` and `utils.hpp` files inside `IFDEF OPENZWAVE16_DEPRECATED` blocks, I have tried to fix them but unfortunally I'm stucked, I need your help

I'm also unable to install the module with the flag `OPENZWAVE16_DEPRECATED` to enable methods like `writeConfig`. I have tryed with `npm install --OPNEZWAVE16_DEPRECATED=1` but it doesn't work

**Comment by robertsLando** [comment]
@ekarak I think you made a wrong find/replace on `openzwave-scenes.cpp` that has broke many things in this commit: 065c9178ec1792268b7fb3592025693a9512e21f

**Comment by ekarak** [comment]
are we ok to close this down @robertsLando ?

**Comment by robertsLando** [comment]
Sure
