### ISSUE TITLE
Heiman motion sensor HS1MS-Z problem 

### ISSUE THREAD

**Issue by Tomasz01** [OpenZWave/node-openzwave-shared#360]
I test Heiman Smart Motion Sensor, but I've a problem. Sensors is working, react for motion, but variable Binary Sensor / Sensor_1 is always FALSE. I test several pieces, they all behave the same. The sensor works, for example the sleep variable changes when it detects motion.

I use openzwave-1.6.994 with iobroker.zwave@1.6.3 (tested also 1.7.3), openzwave-shared@1.5.10 (tested also 1.5.7, 1.5.8)

Other devices z-wave works ok.

Log from tests. One device, clean install.
[OZW_Log.txt.zip](https://github.com/OpenZWave/node-openzwave-shared/files/4007101/OZW_Log.txt.zip)

**Comment by ekarak** [comment]
This place is a software bug tracking system, not a usage forum. Please research on this device's compatibility with OpenZWave (the main C++ library), test it with MinOZW (to verify it works as expected) and please report back if you suspect there's a problem with the Node.JS binding.
