### ISSUE TITLE
undefined symbol on Raspberry Pi 4

### ISSUE THREAD

**Issue by WojtekKozaczynski** [OpenZWave/node-openzwave-shared#378]
I am having the same issue as https://github.com/OpenZWave/node-openzwave-shared/issues/325 on Raspberry Pi 4. I have followed all instructions at https://github.com/OpenZWave/node-openzwave-shared/blob/master/README-raspbian.md#2-install-the-open-zwave-library-on-your-raspberry. Execution on test2.js results in the following (I am running as the ```pi``` su). 
``` 
Initialising OpenZWave 1.4.79 binary addon for Node.JS.
        OpenZWave Security API is ENABLED
        ZWave device db    : /usr/etc/openzwave
        User settings path : /home/pi/nodejs/openzwave/node_modules/openzwave-shared/build/Release/../../
        Option Overrides : --ConsoleOutput true
connecting to /dev/ttyACM0
node: symbol lookup error: /home/pi/nodejs/openzwave/node_modules/openzwave-shared/build/Release/openzwave_shared.node: undefined symbol: _ZN9OpenZWave7Options6CreateERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_S8_
```
I cannot find a resolution to the problem in issue #325. 
Are there different instructions for Pi 4 - the instructions say "Download and install the precompiled Raspbian/ARMv6 packages for __Raspberry 1__"?

**Comment by robertsLando** [comment]
I suggest yout to clone and manually install OZW 1.6 on your rpi
