### ISSUE TITLE
ERROR: Cannot get exclusive lock for serial port /dev/ttyUSB0

### ISSUE THREAD

**Issue by Ghada-Ch** [OpenZWave/node-openzwave-shared#383]
when I execute node test2.js I get :
ERROR: Cannot get exclusive lock for serial port /dev/ttyUSB0. Error code 11
2020-07-02 11:35:57.177 Error, ERROR: Failed to open serial port /dev/ttyUSB0
In the other side ,/dev/ttyUSB0 worked successfully with MinOZW
And I modified permission for dev/ttyUSB0
crwxrwxrwx 1 root dialout 188, 0 juil.  2 10:50 /dev/ttyUSB0

**Comment by robertsLando** [comment]
I think you have another process using the tty on background

**Comment by Ghada-Ch** [comment]
Yes ,It is and i fixed it thanks
