### ISSUE TITLE
Question about files

### ISSUE THREAD

**Issue by ptorrent** [OpenZWave/node-openzwave-shared#385]
Hello there,

I'm using this module at version 1.4.6 with nodejs 8.

In my UserPath, I've 3 files :

ozwcache_0xe7e4c71d.xml 
OZW_Log.txt  
zwscene.xml

What's "ozwcache_0xe7e4c71d.xml" file ? Where are store all my parameters ? I don't see any " zwcfg_.xml" file in the directory.

Thanks for your help and your work !

**Comment by robertsLando** [comment]
Ozwcache essentially is zwcfg in ozw 1.6, like the name says it’s a cache where nodes info are stored

---

Daniel

**Comment by ptorrent** [comment]
like I said, I'm at version 1.4.6...Is it the same with this version?

**Comment by robertsLando** [comment]
@ptorrent I'm speaking about Openzwave (ozw) version not openzwave-shared version
