### ISSUE TITLE
Type_ManufacturerSpecificDBRead in utils.cc

### ISSUE THREAD

**Issue by jmgiaever** [OpenZWave/node-openzwave-shared#390]
Is `Type_ManufacturerSpecificDBRead` at line 630 in [utils.cc](https://github.com/OpenZWave/node-openzwave-shared/blob/master/src/utils.cc#L630) supposed to be `Type_ManufacturerSpecificDBReady` (note the trailing `y`), ref [Notification.h](https://github.com/OpenZWave/open-zwave/blob/e3e34f6da799e7e3bd740350294407e104bc35d6/cpp/src/Notification.h#L122) line 122?

Getting a build error 
```
../src/utils.cc:630:21: error: ‘Type_ManufacturerSpecificDBRead’ is not a member of ‘OpenZWave::Notification’
  630 |  case Notification::Type_ManufacturerSpecificDBRead:
```

**Comment by robertsLando** [comment]
PR?
