### ISSUE TITLE
Can't connect my Zwave network after restore HA

### ISSUE THREAD

**Issue by OlliF69** [OpenZWave/node-openzwave-shared#394]
I've got a little problem. I can't connect my OpenZwave network after a fully restore of my HA config.
OpenZwave is started (and now updated to version 0.9.1), network key was saved and is inserted in the config again. Device path is correct. (I only disconnect an connect my USB tsick a few times)
But if I start openZwave (inside HA) and push the button CONNECT, the new window appears with the ConnectingState - nothing happened - only 0%.
What did I wrong?
problem of OpenZwave or Mosquitto broker?
Thanks for help and response

**Comment by OlliF69** [comment]
I started my OpenZWave new and checked the LOG:
Remote Connection Status:  QTOZWManager::ConnectingState QAbstractSocket::UnknownSocketError 
and the connectingState is still on 0%

**Comment by robertsLando** [comment]
@OlliF69 I suggest you to use zwavejs isntead https://github.com/zwave-js/node-zwave-js

**Comment by OlliF69** [comment]
Yeah, this I tried one day before. But after starten the ZWAVE newtwork my complete system (HA) hangs.
Therefore I decided to go back... But in the moment, I'm a little bit confused. Perhaps it's better to switch to **zwavejs** and to get this running...

**Comment by robertsLando** [comment]
I'm the only mantainer of this package (node-openzwave-shared) and I don't plan to maintain it anymore, so yep I suggest you to invest some time in make zwave-js working now instead of wasting time here

**Comment by OlliF69** [comment]
Ok, I start a new try.
