### ISSUE TITLE
I cant install openzwave on my computer :( !!

### ISSUE THREAD

**Issue by DaminicaG** [OpenZWave/node-openzwave-shared#395]
Can someone help me? Im new to macos and I cant install openzwave from my terminal. 

I properly installed open zwave using 'brew install open-zwave' 
Now Im trying to 'npm install openzwave-shared' and I get this error:

../src/openzwave.hpp:30:10: fatal error: 'Manager.h' file not found
#include "Manager.h"
         ^~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/openzwave_shared/src/callbacks.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
gyp ERR! System Darwin 20.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/dannig/node_modules/openzwave-shared
gyp ERR! node -v v14.18.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/Users/dannig/package.json'
npm WARN dannig No description
npm WARN dannig No repository field.
npm WARN dannig No README data
npm WARN dannig No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! openzwave-shared@1.7.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the openzwave-shared@1.7.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Can someone help? This might be a noob question but Ive been stuck on this for awhile now!

**Comment by robertsLando** [comment]
Openzwave is died, use zwavejs instead
