### ISSUE TITLE
Crashes when value not found

### ISSUE THREAD

**Issue by TonyFeestneus** [OpenZWave/node-openzwave-shared#397]
For Example: TypeError: OpenZWave valueId not found: 13-37-3-0

When you accidentally send a non-existent value, it crashes. Why not just throw an error and keep running?

(this particular error is due to a change in versions. Previously node 13 could be sent an instance of 3, now it should be 2. Solved in my code, but again: just an error should be the standard, not crash the app, right)

**Comment by robertsLando** [comment]
move to zwavejs https://github.com/zwave-js/zwavejs2mqtt

**Comment by TonyFeestneus** [comment]
Why?

**Comment by robertsLando** [comment]
@TonyFeestneus Because openzwave is not supported anymore and everyone is moving to zwavejs

**Comment by TonyFeestneus** [comment]
Alright, did not know that. Built my system entirely around openzwave so I'll just have to deal with it then
