### ISSUE TITLE
Dependencies: Incompatible with nan 2.0.0

### ISSUE THREAD

**Issue by RoboPhred** [OpenZWave/node-openzwave-shared#4]
Version 2.0.0 of nan has moved its classes into a namespace here:
https://github.com/nodejs/nan/commit/5cd3871ab4978d45077bbea3f1edc57675482b05

I was able to get node-gyp to compile by modifying the package.conf and specifying
"nan": "~1.9.0"
as the dependency

**Comment by ekarak** [comment]
unbelievable, isn't it? the **compatibility** layer breaks ... _compatibility_ for aesthetic reasons :)
Thanks for this information.

**Comment by ekarak** [comment]
Just published:  openzwave-shared@1.0.1
