### ISSUE TITLE
Redeploying nodes disconnects controller and never reconnects.

### ISSUE THREAD

**Issue by Stubbs** [OpenZWave/node-openzwave-shared#40]
Whenever I deploy nodes the z-wave controller disconnects and never connects again. Even if I remove & add a new input node it won't connect. There's nothing zwave related in the logs either.

If I restart Node-red the zwave node reconnects like it should.

**Comment by ekarak** [comment]
You're right there's a visual bug there, Have you actually tried sending commands? 
Actually the zwave controller never disconnects, but there's no event sent from NR for deployment, hence it's marked as disconnected  - BUT if you send a command, or there is some status update (eg from manual device operation) - then you'll see it connected.

**Comment by ekarak** [comment]
I've just pushed version 1.1.1 to npm, can you please update and retry? Node status should now be set when NR redeploys the flow(s) and if the zwave controller is alive it should appear as green/connected.

**Comment by Stubbs** [comment]
Sorry, I've opened this on the wrong repo haven't I. 

I'll install the new version and report back. If it's still having issues I'll open a new ticket on the right repo.
