### ISSUE TITLE
Get Devices

### ISSUE THREAD

**Issue by Cloudhomebr** [OpenZWave/node-openzwave-shared#43]
Hi,

How i can get a list of devices on zwave network?

Thanks

**Comment by ekarak** [comment]
The issue tracker is meant to track bugs, not substitute a user forum. Please read the documentation and examine the demo usage script, which contains a `nodes` variable. This variable is populated with all the nodes in the ZWave network:
```js
zwave.on('node added', function(nodeid) {
        console.log('=================== NODE ADDED! ====================');
        nodes[nodeid] = {
...
```
