### ISSUE TITLE
Getting Updates From Sleeping Device

### ISSUE THREAD

**Issue by scottpreston** [OpenZWave/node-openzwave-shared#46]
I have a battery powered door sensor Aeotec DSB29. I also have an Aeon z-stick. Your example program works fine, it reports the devices in the network, but by door sensor is sleeping and no Event is fired from your example program that detects when the sensor wakes up and communicates that the door opens or closes. I would think this would be a "value changed" event but there's no response.

Does your API support this?

**Comment by ekarak** [comment]
Could you please add debugging output to the test script by passing the relevant config options to the library as follows:
```js
var zwave = new OpenZWave({
	ConsoleOutput: true,
	Logging: true
});
```
and run the test script again? 

Thanks

**Comment by scottpreston** [comment]
I can't run the exact script, I had to comment out beginControllerCommand because of this error:

TypeError: Object #<OZW> has no method 'beginControllerCommand'

But after running the script the only thing I see about the device (Node2) is this:

2015-11-25 09:19:05.378 Info, Node002, WARNING: ZW_SEND_DATA failed. No ACK received - device may be asleep.
2015-11-25 09:19:05.378 Info, Node002,   Node 2 has been marked as asleep
2015-11-25 09:19:05.378 Info, Node002, Node not responding - moving QueryStageComplete command to Wake-Up queue

Nothing else in the console after opening and closing the door multiple times light coming on, going off, etc.

**Comment by scottpreston** [comment]
i was able to get this working by resetting my device and removing the old config.

**Comment by scottpreston** [comment]
secondarily I was able to add the event:

zwave.on('node event', function(nodeid, nodeEvt) {
    console.log(new Date(),  nodeid, nodeEvt);
});

then i could view the binary sensor data as it came in.

**Comment by ekarak** [comment]
Thanks Scott, this error about `beginControllerCommand` is because its a deprecated call, and its not included in the node.js addon, if the new security API is present. See the [README on security functions](https://github.com/OpenZWave/node-openzwave-shared/blob/master/README-security.md) for more details.
I'll fix the test script based on your feedback. Many thanks!
