### ISSUE TITLE
Not building on Node v4.2.2 / Raspberry Pi 2

### ISSUE THREAD

**Issue by nthx** [OpenZWave/node-openzwave-shared#47]
Hello there,

I'd like to report, that building fails on this environment:

    nthx@rpi-2 ~ $ node --version
    v4.2.2
    nthx@rpi-2 ~ $ npm --version
    2.14.7
    nthx@rpi-2 ~ $ uname -a
    Linux rpi-2 4.1.13-v7+ #826 SMP PREEMPT Fri Nov 13 20:19:03 GMT 2015 armv7l GNU/Linux

    nthx@rpi-2 ~ $ ldconfig -p | grep libopenzw
	libopenzwave.so.1.3 (libc6,hard-float) => /usr/local/lib/libopenzwave.so.1.3
	libopenzwave.so (libc6,hard-float) => /usr/local/lib/libopenzwave.so

npm-debug.log attached

[npm-debug.log.txt](https://github.com/OpenZWave/node-openzwave-shared/files/44035/npm-debug.log.txt)

**Comment by ekarak** [comment]
Unfortunately the npm debug log is of very little use. Can you please post the output of:
`cd /home/nthx/node_modules/openzwave-shared && node-gyp rebuild`

**Comment by ekarak** [comment]
I have a hunch that this is the error you're seeing?
```
../src/utils.cc: In function ‘const string OZW::getNotifHelpMsg(const OpenZWave::Notification*)’:
../src/utils.cc:310:25: error: passing ‘const OpenZWave::Notification’ as ‘this’ argument of ‘std::string OpenZWave::Notification::GetAsString()’ discards qualifiers [-fpermissive]
   return n->GetAsString();
                         ^
make: *** [Release/obj.target/openzwave_shared/src/utils.o] Error 1
make: Leaving directory `/home/ekarakou/src/node-openzwave-shared/build'
gyp ERR! build error 
```

If yes, this is a bug in OpenZWave#693 and you need to update to the latest master from Github

**Comment by nthx** [comment]
Hi. Thanks for response.

I attach output of `node-gyp rebuild`

    nthx@rpi-2 ~/github/node-openzwave-shared $ node --version                                                                                                                             
    v4.2.2
    nthx@rpi-2 ~/github/node-openzwave-shared $ node-gyp --version
    v3.1.0
    nthx@rpi-2 ~/github/node-openzwave-shared $ npm --version
    2.14.7
    nthx@rpi-2 ~/github/node-openzwave-shared $ git log | head -1
    
[node-openzwave-shared-master-a5929743fc26944b3aa090821e0acef6dd97ab5e-node-4.2.2-node-gyp-3.1.0-npm-2.14.7.txt](https://github.com/OpenZWave/node-openzwave-shared/files/44761/node-openzwave-shared-master-a5929743fc26944b3aa090821e0acef6dd97ab5e-node-4.2.2-node-gyp-3.1.0-npm-2.14.7.txt)
commit a5929743fc26944b3aa090821e0acef6dd97ab5e

**Comment by nthx** [comment]
Is this enough for you? I can still work on it if you need.

I have built it on earlier version of Node.js in the meantime (0.12.4)

**Comment by ekarak** [comment]
I've just compiled successfully with Node.js 4.2.2 (but on x64, not ARM). I have no spare RPi to experiment at the moment.
My gut feel here is that you have a bad compilation environment. All the heaps about missing Maybe and MaybeLocals suggests so:
```
/home/nthx/github/node-openzwave-shared/node_modules/nan/nan_maybe_43_inl.h:19:12: error: ‘Maybe’ does not name a type
/home/nthx/github/node-openzwave-shared/node_modules/nan/nan_maybe_43_inl.h:24:12: error: ‘Maybe’ does not name a type
/home/nthx/github/node-openzwave-shared/node_modules/nan/nan_maybe_43_inl.h:31:1: error: ‘MaybeLocal’ does not name a type
/home/nthx/github/node-openzwave-shared/node_modules/nan/nan_maybe_43_inl.h:36:1: error: ‘MaybeLocal’ does not name a type
```
