### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by aborovsky** [OpenZWave/node-openzwave-shared#48]
Latest master branch openzwave compiled (https://github.com/OpenZWave/open-zwave).
Executing slightly modified test.js (https://github.com/OpenZWave/node-openzwave-shared/blob/master/test.js).

Result:

```
Initialising OpenZWave 1.3.572 binary addon for Node.JS.
        OpenZWave Security API is ENABLED
        ZWave device db    : /usr/local/etc/openzwave/
        User settings path : /home/beetoo/beetoo-node-red/node_modules/openzwave-shared/build/Debug/../../
        Option Overrides : --ConsoleOutput false --Logging true --SaveConfiguration false --DriverMaxAttempts 3 --PollInterval 500 --SuppressValueRefresh true
connecting to /dev/ttyUSB0
=================== CONNECTED! ====================
=================== DRIVER READY! ====================
scanning homeid=0xf2d15a12...
=================== NODE ADDED! ====================
=================== NODE ADDED! ====================
=================== NODE ADDED! ====================
=================== NODE ADDED! ====================
node17: notification(2): Notification - NoOperation
node24: notification(2): Notification - NoOperation
node25: notification(2): Notification - NoOperation
node1: Z-Wave.Me, Z-Wave USB Stick
node1: name="", type="Static PC Controller", location=""
node1: class 32
node1:   Basic=0
scan complete, hit ^C to finish.
Segmentation fault
```

Crashing, when one try to setValue anything:
```
zwave.setValue(24, 64, 1, 0, 'Cool');
```

test.js attached

**Comment by aborovsky** [comment]
node -v
v0.12.8
npm --version
3.5.0
uname -a
Linux 4.1.13-v7+ #826 SMP PREEMPT Fri Nov 13 20:19:03 GMT 2015 armv7l GNU/Linux

Raspbian

**Comment by Irrelon** [comment]
I see the same thing with version 1.2.919 of OZW (the one this library has been tested against according to the docs):

```
Initialising OpenZWave 1.2.919 binary addon for Node.JS.
	Security API not found, using legacy BeginControllerCommand() instead
	ZWave device db    : /usr/local/etc/openzwave
	User settings path : /home/robevans/testozw/node_modules/openzwave-shared/build/Release/../../
	Option Overrides : --ConsoleOutput false --Logging true --NetworkKey 0x14, 0xc2, 0x48, 0x2a, 0x88, 0xb7, 0x38, 0x33, 0x39, 0x97, 0x4e, 0xd9, 0xfb, 0x8c, 0x9d, 0x13
connecting to /dev/ttyACM0
scanning homeid=0xd9735265...
node1: Z-Wave.Me, Unknown: type=0400, id=0001
node1: name="", type="Static PC Controller", location=""
node1: class 32
node1:   Basic=0
====> scan complete, hit ^C to finish.
Segmentation fault
```

**Comment by ekarak** [comment]
Apologies, this is probably related to a recent change I made in handling valueIDs in arguments. Please download and use the previous release https://github.com/OpenZWave/node-openzwave-shared/releases/tag/v1.1.2 until I replicate and test this.

**Comment by Irrelon** [comment]
:) awesome thanks. Will check and let you know results.

**Comment by aborovsky** [comment]
Yes!!!
It's works!!!
Only with v1.1.2 of node-openzwave-shared

**Comment by ekarak** [comment]
I think both reporters were using the wrong valueID.
New version 1.1.6 will now throw a proper TypeError about not being able to find the OpenZWave ValueID by constituents or object.
@aborovsky I don't see any message in the logs about the command class 64 (Thermostat) - can you please make sure this ValueID exists (by adding back the `console.log` in the `value added` handler)?
@Irrelon are you running the test.js unmodified? do you have a Zwave dimmer as node 5?

**Comment by Irrelon** [comment]
Hey, I was running test2.js only modified to use /dev/ttyACM0

**Comment by ekarak** [comment]
OK, so now, after the work I'm commiting shortly, you're going to get a proper error instead of a segfault when `setValue` is passed a missing/invalid valueID:
```
/home/ekarak/gh/OpenZWave/node-openzwave-shared/test2.js:120
    zwave.setValue(5,38);
          ^

TypeError: setValue: OpenZWave valueId not found
    at TypeError (native)
    at EventEmitter.<anonymous> (/home/ekarak/gh/OpenZWave/node-openzwave-shared/test2.js:120:11)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at addonModule.Emitter.emit (/home/ekarak/gh/OpenZWave/node-openzwave-shared/lib/openzwave-shared.js:39:5)
```
