### ISSUE TITLE
Security API not found

### ISSUE THREAD

**Issue by Irrelon** [OpenZWave/node-openzwave-shared#49]
I wonder if you might be able to help, I can't figure out why my Security API is not found. I've pasted the startup output below... other users seem to get theirs saying enabled.

```
Initialising OpenZWave 1.2.919 binary addon for Node.JS.
    Security API not found, using legacy BeginControllerCommand() instead
    ZWave device db    : /usr/local/etc/openzwave
    User settings path : /home/robevans/testozw/node_modules/openzwave-shared/build/Release/../../
    Option Overrides : --ConsoleOutput false --Logging true --NetworkKey 0x14, 0xc2, 0x48, 0x2a, 0x88, 0xb7, 0x38, 0x33, 0x39, 0x97, 0x4e, 0xd9, 0xfb, 0x8c, 0x9d, 0x13
connecting to /dev/ttyACM0
scanning homeid=0xd9735265...
node1: Z-Wave.Me, Unknown: type=0400, id=0001
node1: name="", type="Static PC Controller", location=""
node1: class 32
node1:   Basic=0
====> scan complete, hit ^C to finish.
Segmentation fault
```

I've uncommented the line in the options.xml with the network key and changed the values. I've also modified the init in the test2.js that came with the repo (purely for test purposes):

```
var zwave = new ZWave({
    ConsoleOutput: false,
    Logging: true,
    NetworkKey: "0x14, 0xc2, 0x48, 0x2a, 0x88, 0xb7, 0x38, 0x33, 0x39, 0x97, 0x4e, 0xd9, 0xfb, 0x8c, 0x9d, 0x13"
});
```

I'm using a UZB1 from zwave.me as the stick. I also have an Aeotec USB stick I could try but I'm hoping it's a software setting :)

**Comment by aborovsky** [comment]
Hi, Irrelon!
For me Security API is enabled.
Cause it's depends on your compiled openzwave driver.

Did you compiled openzwave by yourself?

**Comment by Irrelon** [comment]
Yes. I followed instructions to do a make && sudo make install. Should I do it differently? I'll pop over to the openzwave docs and take another look to see if I missed something :)

**Comment by aborovsky** [comment]
ekarak, how about appropriate fixes in nearest commit? :)

**Comment by aborovsky** [comment]
According to https://github.com/OpenZWave/node-openzwave-shared/blob/master/README-security.md:
```
As I currently do not own any security devices, please feel free to contribute your experience with openzwave-shared and the new features in OpenZWave 1.3
```
you need openzvawe 1.3

**Comment by Irrelon** [comment]
Aha! Of course. I actually remember seeing that! I'll give it a whirl. I've got a new Yale Keyfree: http://www.yale.co.uk/en/yale/couk/productsdb/smart-locks/keyfree-connected-smart-lock/

Really want to be able to do audits, user codes and lock/unlock :)

**Comment by ekarak** [comment]
ok, you probably have a stale version of OpenZWave lying around in your system.
You need to uninstall it and install the latest v1.3 master tarball instead.

Then, you can rebuild the node.js addon (`node-gyp rebuild` from within the addon's source directory) so as it can identify the new security API (hint: the addon is looking for a header file called `ZWSecurity.h` - if its there, then OpenZWave supports security devices). 

There's also a successful report from a user who raised an issue on using a zwave lock with secure inclusion, see #32 for details on how to use the API.
