### ISSUE TITLE
Node Symbol Lookup Error

### ISSUE THREAD

**Issue by stockmopar** [OpenZWave/node-openzwave-shared#50]
Just tried updating to the newest version from 1.1.1 and am now getting this error:

node: symbol lookup error: /home/joe/home/node_modules/openzwave-shared/build/Release/openzwave_shared.node: undefined symbol: _ZNK9OpenZWave12Notification11GetAsStringEv

I am on Ubuntu. Node version v0.12.8 and am using a UZB adapter.  I can revert to version 1.1.1 and it loads correctly.  Is there anything simple and obvious that I am doing wrong?

**Comment by stockmopar** [comment]
I believe I have the latest version of OZW: MinOZW with OpenZWave Version 1.3.491 .

**Comment by ekarak** [comment]
this is a linking error caused by compiling the addon with OpenZWave headers from a later version, but then at runtime an older OpenZWave shared library is found and loaded (and doesn't contain this specific call). Please reinstall (make && sudo make install) the latest OpenZWave and try again.

**Comment by stockmopar** [comment]
Thanks! That worked.
