### ISSUE TITLE
setValue not working

### ISSUE THREAD

**Issue by husky-koglhof** [OpenZWave/node-openzwave-shared#55]
Hi, I've tried to setValue with my own Implementation of iobroker.zwave.
Then I've tried the test2.js from your repository.
But always the same Error:

    zwave.setValue(5,38,1,0,50);
          ^

TypeError: setValue: OpenZWave valueId not found
    at TypeError (native)
    at EventEmitter.<anonymous> (/Users/christian/DEVELOPMENT/node_modules/iobroker.zwave/node_modules/openzwave-shared/test2.js:120:11)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at addonModule.Emitter.emit (/Users/christian/DEVELOPMENT/node_modules/iobroker.zwave/node_modules/openzwave-shared/lib/openzwave-shared.js:39:5)

**Comment by ekarak** [comment]
Can you please verify the values you're passing *correspond to a valid and existing ValueID?* Meaning that if you do a `console.log(...)` for the OpenZWave ValueIDs that the library emits with the 'value added' event handler, is there a value with nodeid=5,cmdclass=38 etc? 
(btw 38==MultiLevel ie, so is there a dimmer at node 5?)

I've added the ability to pass into `setValue` the ValueID object as it's reported from 'value added' (on top of the existing 4 arguments and target value) - and prior to this change I wasn't checking for the validity of the ValueID.

**Comment by husky-koglhof** [comment]
Hi, I've tried this too:

zwave.setValue({
                                        nodeid:   parseInt(obj.native.nodeid),
                                        class_id: parseInt(obj.native.comclass),
                                        instance: parseInt(obj.native.instance),
                                        index:    parseInt(obj.native.index)
                                    }, state.val);

The Parameters are all correct and known values.

**Comment by ekarak** [comment]
Could you please some logs? Is a 'node added' and 'value added' event being fired for node 5 and this valueID correspondigly?

**Comment by husky-koglhof** [comment]
Good Morning!

I've switched from my Mac to Raspberry with the same code and versions.
There runs all correct.

If i've time, i will analyse this and give you feedback.

**Comment by elnulo** [comment]
Actually, i'm having the exact same issue. Working on Raspberry Pi2
I see this value get updated:
value = {"value_id":"3-38-1-0","node_id":3,"class_id":38,"type":"byte","genre":"user","instance":1,"index":0,"label":"Level","units":"","help":"","read_only":false,"write_only":false,"is_polled":false,"min":0,"max":255,"value":99}

However, when i do:
zwave.setValue(3,38,1,0,25)
I get:
TypeError: setValue: OpenZWave valueId not found

any ideas?

**Comment by ekarak** [comment]
Unfortunately, due to lack of resources I still can't replicate this. The unfortunate thing is I only have 3 (three) zwave devices so my ability to test with a wide device range is limited. 
BTW, I've just committed some bugfixes into master. There's a slim chance the v8's garbage collector is kicking in and cleaning up the v8 Values produced by a couple of ancillary methods in utils.cc, so I can only ask you to retest with the latest code.

**Comment by lpw** [comment]
I'm still getting "TypeError: setValue: OpenZWave valueId not found" with the latest master branch here.  Ensuring the argument types match what's expected (and I've tried object-arg form too).  Seems the "value add" events for some random nodes are not getting called, hence no matching type.

**Comment by rgstephens** [comment]
@lpw Thanks for the post. I'm running into this issue with the ZStick 2, Pi and Node Red.

**Comment by Clancey** [comment]
This only happens on nodes with single digits. I have 2 identical switches one is NodeId 9 the other is 10. The same command works for 10, but fails on 9.
