### ISSUE TITLE
Emulate other devices

### ISSUE THREAD

**Issue by DaAwesomeP** [OpenZWave/node-openzwave-shared#56]
Hi,
I'm thinking about upgrading to a Z-Wave-based home automation system. However, I have existing UPB switches installed. I can communicate to the switches from my computer over RS232, and I even wrote a [library to make it easier](https://github.com/DaAwesomeP/node-upb).

I was thinking about making a simple proxy where I could translate the UPB devices to appear on the Z-Wave network. So, I would need to be able to emulate light switches and lamp modules. They would both need to be able to broadcast their events through the proxy and receive commands. Is this possible?

**Comment by ekarak** [comment]
Well I did more or less [the same thing by making KNX and ZWave interoperable](http://flows.nodered.org/flow/b993a7bd7a2832edb23a) using [Node-Red](http://nodered.org/). Node-Red is a fantastic experimentation platform for this kind of interoperability tests.
I've already written a Node-Red plugin for openzwave, my guess is you need to do the same for UPB :)
