### ISSUE TITLE
Issue with RemoveNode method.

### ISSUE THREAD

**Issue by navstev0** [OpenZWave/node-openzwave-shared#57]
After I run "removeNode()"
controller commmand feedback: ControllerComand - Starting node==0, retval=1, state=0
controller commmand feedback: ControllerCommand - Waiting node==0, retval=4, state=0
controller commmand feedback: ControllerCommand - InProgress node==0, retval=6, state=0
controller commmand feedback: ControllerCommand - InProgress node==0, retval=6, state=0
controller commmand feedback: ControllerCommand - Completed node==0, retval=7, state=0
Unhandled OpenZWave notification: 7

I always get "Unhandled OpenZWave notification: 7" this is with the latest source from openzwave. Because of this I have no way of knowing if a node was removed. Unsure if this is from OpenZWave lib or the nodejs port. I am using a Gen 5 Z-Stick.

**Comment by ekarak** [comment]
*You're so very right!* In callbacks.cc I've completely missed the `NotificationType::Type_NodeRemoved` switch case. Fixing it in a jiffy.

**Comment by navstev0** [comment]
Sweet thanks, I went and looked over that stuff as well and was just about to say where the issue was. I must say that the code is very well written in both OpenZWave and this node module.

**Comment by ekarak** [comment]
OK, can you please fetch the latest master from github and give it a try?

**Comment by navstev0** [comment]
Works great. Thanks a bunch!

**Comment by ekarak** [comment]
You're so welcome. I gotta thank you for this, as I also found out that I was missing four button-related (handheld controller) notifications!
