### ISSUE TITLE

Issues with more then one instance.

### ISSUE THREAD

**Issue by navstev0** [OpenZWave/node-openzwave-shared#59]
The purpose is for testing, however i can not test if creating two different ZWave objects trigger events for each other. The expected output of this program is
```
first scanning pass
Disconnecting from one
disconnect from one connecting to two
```

However the output is 

```
first scanning pass
second scanning pass
Disconnecting from one
```
As you can see the zwave.on and zwave2.on are both using the same memory.

```
var ZWave = require('openzwave-shared');

var zwave = new ZWave({
  ConsoleOutput : false
});
var zwave2 = new ZWave({
  ConsoleOutput : false
});

zwave.on('driver ready', function(homeid) {
  console.log('first scanning pass' );
  setTimeout( function() {
    console.log( "Disconnecting from one" );
    zwave.disconnect('/dev/cu.usbmodem1411');
    console.log( "disconnect from one connecting to two" );
    //zwave2.connect( '/dev/cu.usbmodem1411' );
  }, 1 );
});

zwave.on('driver failed', function() {
  console.log( "driver failed for one" );
  zwave.disconnect();
} );

zwave2.on( 'driver ready', function(homeid){
  console.log( 'second scanning pass' );
  setTimeout( function() {
    //zwave2.disconnect('/dev/cu.usbmodem1411' );
    process.exit();
  }, 2500 );
});

zwave2.on('driver failed', function() {
  console.log( "driver failed for two" );
  zwave2.disconnect();
} );

zwave.connect('/dev/cu.usbmodem1411');
```

**Comment by ekarak** [comment]
I'm not sure what you're trying to do here. I'm not even sure that OpenZWave supports more than one concurrent driver instance available.

**Comment by navstev0** [comment]
I don't want to have a concurrent driver. I want to create a set of events for one driver then run some tests. Then disconnect it and create a new drive with different events and run some different tests. However zwave1.on and zwave2.on events register it would appear in a global event trigger. So I cannot have zwave1 and zwave2 have different events.

**Comment by ekarak** [comment]
of course they do, as you're talking to the same C++ Node.JS addon underneath. Try using 
```
zwave.removeAllListeners();
```
after you unregister the first driver.

**Comment by navstev0** [comment]
That makes sense. I have tried to use a single zwave object and trigger removeAllListeners prior to writing creating the 2nd set of events, however found that doing zwave.disconnect and then at a later point doing another zwave.connect will cause one of two issues.
```
Segmentation fault: 11
```
or
```
2016-01-28 10:13:44.460 Error, Options have not been created and locked. Exiting...
2016-01-28 10:13:44.460 Error, Exception: Manager.cpp:95 - 0 - Options Not Created and Locked
Error: Manager.cpp:95 - Options Not Created and Locked
```

I have made changes to my test to reflect this. The different errors will show up when changing the timeout values, or removing the times all together.

```
var ZWave = require('openzwave-shared');

var zwave = new ZWave({
  ConsoleOutput : false
});

function setupEventsZ1(){
  zwave.removeAllListeners();
  zwave.on('driver ready', function(homeid) {
    console.log('first scanning pass' );
    setTimeout( function() {
      console.log( "Disconnecting from one" );
      zwave.disconnect('/dev/cu.usbmodem1411');
      setTimeout( function(){
        console.log( "disconnect from one connecting to two" );
        setupEventsZ2();
        zwave.connect( '/dev/cu.usbmodem1411' );
      }, 1000 );
    }, 1000 );
  });

  zwave.on('driver failed', function() {
    console.log( "driver failed for one" );
    zwave.disconnect();
  } );
}

function setupEventsZ2(){
  zwave.removeAllListeners();
  zwave.on( 'driver ready', function(homeid){
    console.log( 'second scanning pass' );
    setTimeout( function() {
      zwave2.disconnect('/dev/cu.usbmodem1411' );
      process.exit();
    }, 2500 );
  });

  zwave.on('driver failed', function() {
    console.log( "driver failed for two" );
    zwave.disconnect();
  } );
}

setupEventsZ1();
zwave.connect('/dev/cu.usbmodem1411');
```

**Comment by navstev0** [comment]
Agreed the event chain is similar to my issue as the one list above. But being unable to disconnect followed by removeAllListeners prevents me from being able to use removeAllListeners. I have tried to put removeAllListeners prior to disconnect but still get the same issues. So there also seems to be an issue with disconnecting from a device and attempting to reconnect to that device. This is due to error
```
2016-01-29 09:58:31.059 Error, Options have not been created and locked. Exiting...
2016-01-29 09:58:31.059 Error, Exception: Manager.cpp:95 - 0 - Options Not Created and Locked
Error: Manager.cpp:95 - Options Not Created and Locked
```

**Comment by ekarak** [comment]
I think what you need is a very difficult usage case scenario. OZW still uses a single global Manager instance and simply cant cope with multiple instantiations within one process lifecycle. 
Im marking this as closed.

**Comment by ekarak** [comment]
Out of curiosity,  what were you trying to do? Some sort of Wired tests?

**Comment by navstev0** [comment]
I was attempting to unit test my gateway, but without being able to shutdown and reopen it prevents me from being able to do all the tests in one call. I can try to do a work around though i will likely fork and create a call to do a proper shutdown so i can issue a new start up, which seems illogical that it won't fix having a proper shutdown command issued.

I can understand only having one instance running at a time, but you should be able to stop and start instances throughout the life time of your applications.

**Comment by navstev0** [comment]
Fixed in pull request
https://github.com/OpenZWave/node-openzwave-shared/pull/80

**Comment by japita-se** [comment]
Similar problem here.
node and openzwave-shared for Raspbian hangs after the first scan (by using the connect()) method.
