### ISSUE TITLE
Windows RT openzwave build issue.

### ISSUE THREAD

**Issue by vincemic** [OpenZWave/node-openzwave-shared#60]
New platform winRT in openwave causes build issues in node-openzwave-shared.

====Executing command 'npm install openzwave-shared@"^1.1.6"  '====

> openzwave-shared@1.1.6 preinstall \node_modules\.staging\openzwave-shared-68ae4223f475c5aeb47e0c2f74b58930
> node lib/install-ozw.js
Installing Open Z-Wave
Installing dependencies to C:\Users\\AppData\Local\Temp\ozwinstall-wgzd4ukrzfr
Temp Path: C:\Users\\AppData\Local\Temp\ozwinstall-wgzd4ukrzfr
Install Path: C:\Users\\AppData\Local\OpenZWave
Downloading open zwave source.
Extracting open zwave source.
Building open zwave
static library binding.gyp:openzwave#target has several files with the same basename:
gyp: Duplicate basenames in sources section, see list above
  EventImpl: cpp/src/platform/windows/EventImpl.cpp cpp/src/platform/winRT/EventImpl.cpp
  SerialControllerImpl: cpp/src/platform/windows/SerialControllerImpl.cpp cpp/src/platform/winRT/SerialControllerImpl.cpp
  ThreadImpl: cpp/src/platform/windows/ThreadImpl.cpp cpp/src/platform/winRT/ThreadImpl.cpp
  TimeStampImpl: cpp/src/platform/windows/TimeStampImpl.cpp cpp/src/platform/winRT/TimeStampImpl.cpp
  MutexImpl: cpp/src/platform/windows/MutexImpl.cpp cpp/src/platform/winRT/MutexImpl.cpp
  WaitImpl: cpp/src/platform/windows/WaitImpl.cpp cpp/src/platform/winRT/WaitImpl.cpp
  LogImpl: cpp/src/platform/windows/LogImpl.cpp cpp/src/platform/winRT/LogImpl.cpp
  FileOpsImpl: cpp/src/platform/windows/FileOpsImpl.cpp cpp/src/platform/winRT/FileOpsImpl.cpp
libtool on Mac cannot handle that. Use --no-duplicate-basename-check to disable this validation.
C:\Users\vmiceli\Source\Repos\bitdogSA\node_modules\.staging\openzwave-shared-68ae4223f475c5aeb47e0c2f74b58930\lib\install-ozw.js:144
  throw err;
        ^
Error: `gyp` failed with exit code: 1
    at ChildProcess.onCpExit (C:\Users\\AppData\Local\Temp\ozwinstall-wgzd4ukrzfr\node_modules\node-gyp\lib\configure.js:305:16)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "openzwave-shared@^1.1.6"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! openzwave-shared@1.1.6 preinstall: `node lib/install-ozw.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the openzwave-shared@1.1.6 preinstall script 'node lib/install-ozw.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the openzwave-shared package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/install-ozw.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls openzwave-shared
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\\Source\Repos\bitdogSA\npm-debug.log

====npm command completed with exit code 1====

**Comment by ekarak** [comment]
Looks like the script is failing trying to compile OpenZWave for this platform. Is WinRT supported for OpenZWave? Looks [this support for WinRT was comitted very recently](https://groups.google.com/forum/#!topic/openzwave/zvRLe81fg5c) and I'm not sure it has made it to the master branch yet.

**Comment by ekarak** [comment]
just saw you posted on the same thread :)

**Comment by vincemic** [comment]
I do have a quick question that I hope you might be able to help me with.  I have battery operated node that sleeps most of the time.  When I first start OZW, it scans the network and reports all the nodes, but the sleeping nodes information is incomplete.  If I wake the node all the information is completed  I was hoping that setting SaveConfiguration: true in the constructor would allow the initial scan to fill in the missing pieces from memory, but it doesn't seem to.  I see the zwcfg file being created and all the node information is there.  Is there a call I can make the would return node information based on the zwcfg file?Thank you for your time,vinceOn January 27, 2016 at 12:32 AM Elias Karakoulakis <notifications@github.com> wrote:just saw you posted on the same thread :)—Reply to this email directly or view it on GitHub.

**Comment by ekarak** [comment]
the zwcfg.xml file is OpenZWave's persistence mechanism. If you always point OZW to the same directory (where that XML file is stored), it will load it up when booting and reconstruct the information from all the nodes, incl. battery operated devices.

**Comment by vincemic** [comment]
I narrowed the WinRT platform problem to gyp configuration in install-ozw.js.  It needs to exclude the winRT platform directory for the windows platform during build.  I'd submit the correct js settings if I understood gyp options better.  I doubled checked what's in master for openzwave and it builds fine with its make file.

**Comment by sgrebnov** [comment]
same issue

**Comment by ekarak** [comment]
@vincemic can you please provide an update? are you working on a fix for the issue? Thanks

**Comment by ekarak** [comment]
I'm resolving this issue as Windows RT is and will remain unsupported (unless someone is willing to step in and help).
