### ISSUE TITLE
not getting updated value

### ISSUE THREAD

**Issue by eriksape** [OpenZWave/node-openzwave-shared#62]
Hi, thanks for the good job with this project.

I have an issue when a value on **ZXT-120** is updated let me explain the values

at first my device is Off

```
{ '0': 
   { value_id: '2-64-1-0',
     node_id: 2,
     class_id: 64,
     type: 'list',
     genre: 'user',
     instance: 1,
     index: 0,
     label: 'Mode',
     units: '',
     help: '',
     read_only: false,
     write_only: false,
     is_polled: false,
     min: 0,
     max: 0,
     values: 
      [ 'Off',
        'Heat',
        'Cool',
        'Resume',
        'Fan Only',
        'Dry Air',
        'Auto Changeover' ],
     value: 'Off'
   } 
}
```

then when i set a resume with 

`zwave.setValue(2, 64, 1, 0, 'Resume');`

the device is doing the action but the values are not updated neither getting the new values

But when I disconnect it and connect it again (it throw me an error but maybe it need to set again the config to connect on the device) the values are refreshed

```
{ '0': 
   { value_id: '2-64-1-0',
     node_id: 2,
     class_id: 64,
     type: 'list',
     genre: 'user',
     instance: 1,
     index: 0,
     label: 'Mode',
     units: '',
     help: '',
     read_only: false,
     write_only: false,
     is_polled: false,
     min: 0,
     max: 0,
     values: 
      [ 'Off',
        'Heat',
        'Cool',
        'Resume',
        'Fan Only',
        'Dry Air',
        'Auto Changeover' ],
     value: 'Cool'
   } 
}
```

I am running it with the latest version of this project and open-zwave, checked on control-panel and it update the value.

**Comment by ekarak** [comment]
Not all ZWave devices report back their state. When they do have a 'status' association group, then OZW automatically subscribes to it so that you get feedback from status state.
Please try to enable polling for these problematic nodes.

**Comment by japita-se** [comment]
And how we can know it the value has been set or not?
