### ISSUE TITLE
Auto detect adaptor?

### ISSUE THREAD

**Issue by polarathene** [OpenZWave/node-openzwave-shared#71]
I've used the adaptor usb stick I have on a few devices and the device path will vary `/dev/ttyUSB0`, `/dev/ttyACM0`, `/dev/ttyACM1`, and some other one. What would be the best way to go about it? Accessing each ttyUSB/ttyACM/etc and doing some check til I find the adaptor? `.connect()` each path until I stop getting an error or first success I guess?

I ask because it seems to be possible, I have access to a non node.js system that can use the adaptor and auto find the device plugged in. Might be a good feature to add :)

If this is not the appropriate place to ask as it's not a bug, could you advise where I should ask? It's rather specific to this package and there is no support link on the main readme. I doubt the project is popular enough to get a response on common community sites such as StackOverflow/Reddit.

**Comment by ekarak** [comment]
device detection varies wildly for each o/s and is certainly outside of the scope of OpenZWave (and thus this project too). 
Take a look at https://github.com/RoboPhred/node-openzwave-example, this is what you might need.
