### ISSUE TITLE
Decimals are passed a string

### ISSUE THREAD

**Issue by jbaron** [OpenZWave/node-openzwave-shared#75]
I noticed that values of the type decimal are passed as a string (and not a number). Is this on purpose (f.e to keep the precision)?

I can easily have a workaround at my application layer, but in general I would think to just handle it the same as byte, short, integer makes perhaps more sense.

P.S now running this library often and have to say it is performing very well without any crashes. So thanks.

**Comment by ekarak** [comment]
`(f.e to keep the precision)?`
Yes, precisely (*pun intended*). I generally try to avoid floats as long as the conversion back and forth to a String poses no significant performance penalty (and with ZWave's bandwidth of 9.6kbps that's hardly an issue).
If your app is written in JS and you're not running SETI@ZWave , then why do you need a Number?

**Comment by ekarak** [comment]
Closing this call, please feel free to submit a PR that doesn't break the existing API.

**Comment by jbaron** [comment]
The reason is I need to do some calculations and then it makes a big difference ;) Of course at the moment o the calculation I could do the transformation to a number but I don’t want to bloat my code with all kind of extra checks.


But I do understand the precision argument and I can easily transform it into a float when I initially get the nodevalue passed by the zwave driver. That way the rest of my application is unaware of this.

**Comment by ekarak** [comment]
the transformation you're referring to is called [type coercion](http://stackoverflow.com/questions/19915688/what-exactly-is-type-coercion-in-javascript) and is implicit. Once you're in Javascript, you don't need to explicitly convert datatypes (see my example above)

**Comment by jbaron** [comment]
var temp = "19.2"
console.log( 2 + temp);
console.log(temp + 2);


As you can see, type coercion is not really helping in these cases ;)

**Comment by ekarak** [comment]
```var temp = "19.2" console.log( 2 + temp); console.log(temp + 2);

**Comment by ekarak** [comment]
Ah yes, in which case you need to cast a 3rd order spell:
```
> console.log("1.5"*1 + 2)
3.5
```
