### ISSUE TITLE
Node ID

### ISSUE THREAD

**Issue by Edsardio** [OpenZWave/node-openzwave-shared#82]
Every time I add a new node the node id goes up but when I remove one and add another it skips the number I just removed... Is there a way to make it automatically use the next empty number in the nodes array?

Example: 
No nodes
New node ID: 2
New node ID: 3
Remove node ID: 3
New node ID: 4
New node ID: 5
Remove node ID: 4
Remove node ID: 5
New node ID: 6

**Comment by ekarak** [comment]
this is a design decision of the underlying [C++ OpenZWave library](http://www.openzwave.com), nothing to do with node-openzwave-shared which is the Node.JS binding. Closing issue.

**Comment by Fishwaldo** [comment]
Its not even driven by OZW. Its the controller that assigns node ID's. We have 0 control over that.
