### ISSUE TITLE
MinOZW /dev/ttyAMA0 works fine, but OpenZWave('/dev/ttyAMA0') does not

### ISSUE THREAD

**Issue by jdagerot** [OpenZWave/node-openzwave-shared#86]
I'm sorry if I'm troubling you guys with issues not connected to the node-openzwave module but I can't pin-point where the problem is.

If I just run  MinOZW it will connect to /dev/ttyUSB0 which wont work. But if I runt it like

    MinOZW /dev/ttyAMA0

it starts up and I get events from my zWave products (a single lamp switch actually).

However, if I try to run this within node.js it doesn't work, I get loads of status messages but it all boils down to 

    Always, OpenZwave Version 1.3.0 Starting Up
    Info, Setting Up Provided Network Key for Secure Communications
    Warning, Failed - Network Key Not Set
    Info, mgr,     Added driver for controller undefined
    Info,   Opening controller undefined
    Info, Trying to open serial port undefined (attempt 1)
    Error, ERROR: Cannot open serial port undefined. Error code 2
    Error, ERROR: Failed to open serial port undefined
    Warning, WARNING: Failed to init the controller (attempt 0) 

If anyone has an idea of what this is and how I can move on please let me know!

**Comment by ekarak** [comment]
`Added driver for controller undefined` means you haven't supplied a valid port argument to OpenZWave. Try the following code:
```js
var ZWave = require('openzwave-shared');
var zwave = new ZWave({
	ConsoleOutput: true,
	Logging: true
});
zwave.on('driver ready', function(homeid) {
    console.log('scanning homeid=0x%s...', homeid.toString(16));
});
zwave.connect( '/dev/ttyAMA0');
```

**Comment by jdagerot** [comment]
Worked directly. I guess my syntax new ZWave(port,{config}) was not valid. Anyway, thanks a lot for fast and correct help
