### ISSUE TITLE
Can't set UserPath

### ISSUE THREAD

**Issue by glennschmidt** [OpenZWave/node-openzwave-shared#87]
Not sure if this problem is with the Node module, or OZW, but when I try to set a value for UserPath in the object i pass to `new OZW()`, the result seems to be as though there is no user path at all.

* When I don't set a UserPath,  OZW creates zwcfg, zwscene and log files under `node_modules/openzwave-shared/`
* But when I *do* set a UserPath, those files don't get created...at all, as far as I can tell. They aren't in the original location, and they aren't in the custom location I have set.

Any idea what I'm doing wrong here?
The module is built against the 1.4.0 release of the OZW library.

**Comment by ekarak** [comment]
confirmed: Despite I'm passing `UserPath: "tmp"` to the arguments, its still using the `ozw_userpath` value:
```
... UserPath: "/tmp"
... });
Initialising OpenZWave 1.3.550 binary addon for Node.JS.
	OpenZWave Security API is ENABLED
	ZWave device db    : /usr/local/etc/openzwave
	User settings path : /home/ekarak/node_modules/openzwave-shared/build/Debug/../../
	Option Overrides : --ConsoleOutput true --Logging true --SaveConfiguration true --DriverMaxAttempts 3 --PollInterval 500 --SuppressValueRefresh true --UserPath /tmp
```

**Comment by ekarak** [comment]
Hello,
Could you please fetch the latest master and try again? I've pushed a change to properly handle the UserPath argument.

**Comment by glennschmidt** [comment]
Thanks, I have confirmed the problem is fixed in master

**Comment by ekarak** [comment]
Thanks, closing
