### ISSUE TITLE
TypeScript declaration file available

### ISSUE THREAD

**Issue by jbaron** [OpenZWave/node-openzwave-shared#88]
Not an issue, just a quick update

For those that want to use TypeScript, I created a declaration file for openzwave-shared that you can get from: https://github.com/jbaron/openzwave-shared-tsd

Nothing fancy, just a straight forward declaration file based on the source code of node-openzwave-shared. I myself used only a limited set of functions, so there could still be some bugs in there.

**Comment by ekarak** [comment]
That's great! Can you please submit a PR on the main README file to add a link to your project in case someone wants to use openzwave-shared from a TypeScript app? thanks!

**Comment by ekarak** [comment]
closing down, thanks a lot!
