### ISSUE TITLE
Share an instance of zwave with multiple applications?

### ISSUE THREAD

**Issue by jdagerot** [OpenZWave/node-openzwave-shared#90]
First, sorry for posting this as an issue, I would love to have a forum that we can discuss node-openzwave-shared but have failed to find one. Can anyone recommend a good discussion board?

What I would like to do is to have multiple instances of the zwave. One that takes care of production stuff and another, paralell that works with the same hardware but that I can restart etc as much as I want.

Is this possible in anyway? Today I'm using a sub/pub system, but it's not ultimate.

**Comment by ekarak** [comment]
I've created a gitter chatroom, lets close this ticket (as its not a real issue) and continue discussion there.
Thanks
