### ISSUE TITLE
Provide API for OpenZWave statistics functions

### ISSUE THREAD

**Issue by shanemadden** [OpenZWave/node-openzwave-shared#96]
Hopefully not too big of a task, but definitely a feature request: it'd be great to have the OpenZWave `GetDriverStatistics` and `GetNodeStatistics` API calls exposed through the library to be able to fetch the stats data.

Thanks for the great work on this!

**Comment by ekarak** [comment]
Hi Shane, why not give it a shot and add yourself to the Hall of Fame of OpenZwave Hackers by submitting a pull request? :)

**Comment by shanemadden** [comment]
Haha, fair enough - in that case, make sure my understanding is right before I start hacking at it..

Because these calls expect passed in pointers to `Driver::DriverData`/`Node::NodeData` structs for them to populate with the return data, the nan wrapper will need to create the struct, pass the pointer to the OZW call, then harvest the result data out of that struct into a nan object to be returned.  It looks like `GetNodeNeighbors` is working in a similar way, just using an int array instead of a struct (and returning an array instead of an object) - am I missing anything glaring?

**Comment by ekarak** [comment]
Yup, seems you're right. Just add the two missing calls in a new branch and be sure to wear your tuxedo, I hear that OHHF (OpenZWave Hackers Hall of Fame) have a  strict dress code for pull requests.

**Comment by ekarak** [comment]
only took me 6 months, I've just added the two new commands and pushed to master. Enjoy!

**Comment by shanemadden** [comment]
Thanks a lot, sorry I didn't get around to trying the implementation myself!
