### ISSUE TITLE
Error running on raspberry pi 2 with razberry

### ISSUE THREAD

**Issue by leothlon** [OpenZWave/node-openzwave-shared#97]
Hi.
i have tried getting this to run on my raspberry pi 2 with razberry for 3 days now..

I have installed OZW like in the instructions but when i try to run test2.js i get this:

> 2016-05-21 10:23:19.450 Always, OpenZwave Version 1.4.164 Starting Up
> 2016-05-21 10:23:19.450 Info, Setting Up Provided Network Key for Secure Communications
> 2016-05-21 10:23:19.451 Warning, Failed - Network Key Not Set
> 2016-05-21 10:23:19.451 Info, mgr,     Added driver for controller /dev/ttyAMA0
> 2016-05-21 10:23:19.451 Info,   Opening controller /dev/ttyAMA0
> 2016-05-21 10:23:19.451 Info, Trying to open serial port /dev/ttyAMA0 (attempt 1)
> 2016-05-21 10:23:19.451 Error, ERROR: Cannot open serial port /dev/ttyAMA0. Error code 13
> 2016-05-21 10:23:19.451 Error, ERROR: Failed to open serial port /dev/ttyAMA0
> 2016-05-21 10:23:19.452 Warning, WARNING: Failed to init the controller (attempt 0)

(its the same if i use ttyUSB0 that i have symlinked to AMA0 for razberry)

when i run "MinOZW /dev/ttyAMA0" i get the output:

> Starting MinOZW with OpenZWave Version 1.4.164
> 2016-05-21 10:31:05.730 Error, Cannot find a path to the configuration files at ../../../config/, Using config/ instead...
> 2016-05-21 10:31:05.734 Info, Reading config/options.xml for Options
> 2016-05-21 10:31:05.734 Warning, Failed to Parse options.xml: Failed to open file

**Comment by ekarak** [comment]
Just a reminder, this is the *Node.js (Javascript) addon* for OpenZWave, you're having problems booting the OpenZWave C++ library itself, so once you can't get the MinOZW example code working, I doubt this is a problem with the Node.JS addon. 

What does the `ls -l /dev/ttyAMA0`  command say?

**Comment by ekarak** [comment]
Googling for "Openzwave Error 13" yields back https://groups.google.com/forum/#!topic/openzwave/qG9y2ODkGCc which saysQ `Error code 13 is EACCESS which is typically permissions.`
So this suggests that the device (/dev/ttyAMA0) is owned by a different user/group than the current user.
