### ISSUE TITLE
Cannot find libopenzwave.so.1.4 even though it was installed

### ISSUE THREAD

**Issue by physiii** [OpenZWave/node-openzwave-shared#98]
I get the following error when running the test program in the readme:

> module.js:435
  return process.dlopen(module, path._makeLong(filename));

>Error: libopenzwave.so.1.4: cannot open shared object file: No such file or directory
    at Error (native)
    at Object.Module._extensions..node (module.js:435:18)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/pi/home-gateway/node_modules/openzwave-shared/lib/openzwave-shared.js:26:19)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)

ls /usr/local/lib/ gives me this so I am not sure why it can't find the object file.
>arm-linux-gnueabihf  libopenzwave.so  libopenzwave.so.1.4  node_modules  python2.7  python3.4  site_ruby

ld -lopenzwave --verbose gives me:

>attempt to open //usr/arm-linux-gnueabihf/lib/libopenzwave.so failed
attempt to open //usr/arm-linux-gnueabihf/lib/libopenzwave.a failed
attempt to open //usr/local/lib/arm-linux-gnueabihf/libopenzwave.so failed
attempt to open //usr/local/lib/arm-linux-gnueabihf/libopenzwave.a failed
attempt to open //usr/local/lib/libopenzwave.so succeeded
-lopenzwave (//usr/local/lib/libopenzwave.so)
libudev.so.1 needed by //usr/local/lib/libopenzwave.so
found libudev.so.1 at //lib/arm-linux-gnueabihf/libudev.so.1
libstdc++.so.6 needed by //usr/local/lib/libopenzwave.so
found libstdc++.so.6 at //usr/lib/arm-linux-gnueabihf/libstdc++.so.6
libm.so.6 needed by //usr/local/lib/libopenzwave.so
found libm.so.6 at //lib/arm-linux-gnueabihf/libm.so.6
libgcc_s.so.1 needed by //usr/local/lib/libopenzwave.so
found libgcc_s.so.1 at //lib/arm-linux-gnueabihf/libgcc_s.so.1
libc.so.6 needed by //usr/local/lib/libopenzwave.so
found libc.so.6 at //lib/arm-linux-gnueabihf/libc.so.6
librt.so.1 needed by //lib/arm-linux-gnueabihf/libudev.so.1
found librt.so.1 at //lib/arm-linux-gnueabihf/librt.so.1
libdl.so.2 needed by //lib/arm-linux-gnueabihf/libudev.so.1
found libdl.so.2 at //lib/arm-linux-gnueabihf/libdl.so.2
libpthread.so.0 needed by //lib/arm-linux-gnueabihf/libudev.so.1
found libpthread.so.0 at //lib/arm-linux-gnueabihf/libpthread.so.0
ld-linux-armhf.so.3 needed by //usr/lib/arm-linux-gnueabihf/libstdc++.so.6
found ld-linux-armhf.so.3 at //lib/arm-linux-gnueabihf/ld-linux-armhf.so.3
ld: warning: cannot find entry symbol _start; defaulting to 000101ec

**Comment by ekarak** [comment]
what was the problem after all?

**Comment by physiii** [comment]
I needed to update my library path:

sudo sed -i '$a LD_LIBRARY_PATH=/usr/local/lib' /etc/environment

**Comment by physiii** [comment]
I get the error unless I am in the program directory when started, so this gives an error:

su pi -c 'cd ~/home-gateway && node gateway -p 3017 >> gateway.log 2>&1 &'

but if I cd into the folder and run "node gateway" it works.
